CREATE TABLE [Transacao].[FinanciamentoAuto] (
    [ID]              INT             IDENTITY (1, 1) NOT NULL,
    [IDTipoTransacao] INT             NOT NULL,
    [IDMunicipio]     INT             NOT NULL,
    [IDUF]            INT             NOT NULL,
    [IDUnidade]       SMALLINT        NOT NULL,
    [NumeroContrato]  VARCHAR (50)    NOT NULL,
    [EstadoCivil]     VARCHAR (100)   NOT NULL,
    [DataLiberacao]   DATE            NOT NULL,
    [Nome]            VARCHAR (300)   NOT NULL,
    [CPF]             VARCHAR (20)    NOT NULL,
    [DataNascimento]  DATE            NOT NULL,
    [Endereco]        VARCHAR (500)   NOT NULL,
    [Complemento]     VARCHAR (200)   NOT NULL,
    [CEP]             VARCHAR (12)    NOT NULL,
    [DDD]             INT             NOT NULL,
    [Telefone]        VARCHAR (20)    NOT NULL,
    [AnoFabricacao]   INT             NOT NULL,
    [AnoModelo]       INT             NOT NULL,
    [Chassi]          VARCHAR (100)   NOT NULL,
    [PrazoVencimento] INT             NOT NULL,
    [ValorContrato]   DECIMAL (18, 2) NOT NULL,
    [DataImportacao]  DATETIME        DEFAULT (getdate()) NOT NULL,
    [Sexo]            VARCHAR (1)     NOT NULL,
    [Ativo]           BIT             DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_FinanciamentoAuto] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Municipio_FinanciamentoAuto] FOREIGN KEY ([IDMunicipio]) REFERENCES [Transacao].[MunicipioIBGE] ([ID]),
    CONSTRAINT [FK_TipoTransacaoFinanciamentoAuto] FOREIGN KEY ([IDTipoTransacao]) REFERENCES [Transacao].[TipoTransacao] ([ID]),
    CONSTRAINT [FK_UFFinanciamentoAuto] FOREIGN KEY ([IDUF]) REFERENCES [Transacao].[UF] ([ID]),
    CONSTRAINT [FK_UnidadeFinanciamentoAuto] FOREIGN KEY ([IDUnidade]) REFERENCES [Dados].[Unidade] ([ID])
);

