CREATE TABLE [Marketing].[FuncionarioMundoCaixa] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [IDEmpresa]             SMALLINT      NULL,
    [IDCargo]               SMALLINT      NULL,
    [IDEstadoCivil]         TINYINT       NULL,
    [IDSexo]                TINYINT       NULL,
    [IDUnidadeLotacao]      INT           NULL,
    [Nome]                  VARCHAR (500) NULL,
    [CPF]                   VARCHAR (50)  NULL,
    [DataNascimento]        DATE          NULL,
    [Matricula]             INT           NULL,
    [TelefoneComercial]     VARCHAR (50)  NULL,
    [TelefonePessoal]       VARCHAR (50)  NULL,
    [TelefoneCelular]       VARCHAR (50)  NULL,
    [TipoPessoa]            VARCHAR (50)  NULL,
    [Escolaridade]          VARCHAR (500) NULL,
    [Formacao]              VARCHAR (500) NULL,
    [EmailPessoal]          VARCHAR (500) NULL,
    [EmailComercial]        VARCHAR (500) NULL,
    [IsAssociadoFENAE]      BIT           DEFAULT ((0)) NULL,
    [IsAssociadoFUNCEF]     BIT           DEFAULT ((0)) NULL,
    [DataUltimoLogin]       DATE          NULL,
    [IsAposentado]          BIT           DEFAULT ((0)) NULL,
    [IsPensionista]         BIT           DEFAULT ((0)) NULL,
    [IsBloqueadoResgate]    BIT           DEFAULT ((0)) NULL,
    [IsPositivado]          BIT           DEFAULT ((0)) NULL,
    [IsSenhaExpirada]       BIT           DEFAULT ((0)) NULL,
    [ExigeCodigoSms]        BIT           DEFAULT ((0)) NULL,
    [DataUltimaAtualizacao] DATE          NULL,
    [DataArquivo]           DATE          NULL,
    [IsAtivo]               BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_MundoCaixa] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CargoMundoCaixa] FOREIGN KEY ([IDCargo]) REFERENCES [Dados].[Cargo] ([ID]),
    CONSTRAINT [FK_EmpresaMundoCaixa] FOREIGN KEY ([IDEmpresa]) REFERENCES [Dados].[Empresa] ([ID]),
    CONSTRAINT [FK_EstadoCivilMundoCaixa] FOREIGN KEY ([IDEstadoCivil]) REFERENCES [Dados].[EstadoCivil] ([ID]),
    CONSTRAINT [FK_SexoMundoCaixa] FOREIGN KEY ([IDSexo]) REFERENCES [Dados].[Sexo] ([ID]),
    CONSTRAINT [FK_UnidadeLotacaoMundoCaixa] FOREIGN KEY ([IDUnidadeLotacao]) REFERENCES [Marketing].[UnidadeLotacao] ([ID])
);

