CREATE TABLE [Marketing].[RelatorioMulticalculoMS] (
    [Codigo]                                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [IdSexo]                                           TINYINT         NULL,
    [IdSexoPrincipalCondutor]                          TINYINT         NULL,
    [Calculo]                                          INT             NULL,
    [DataCalculo]                                      DATE            NULL,
    [Cliente]                                          BIGINT          NULL,
    [Nome]                                             VARCHAR (200)   NULL,
    [CGC_CPF]                                          VARCHAR (20)    NULL,
    [DataNascimento]                                   DATE            NULL,
    [Estado_Civil]                                     VARCHAR (10)    NULL,
    [Telefone]                                         VARCHAR (10)    NULL,
    [Telefone_cel]                                     VARCHAR (10)    NULL,
    [Telefone_Com]                                     VARCHAR (10)    NULL,
    [e_mail]                                           VARCHAR (200)   NULL,
    [Estado]                                           VARCHAR (10)    NULL,
    [Cidade]                                           VARCHAR (100)   NULL,
    [CodigoProduto]                                    INT             NULL,
    [NomeProduto]                                      VARCHAR (100)   NULL,
    [ProdutoEfetivado]                                 VARCHAR (100)   NULL,
    [PremioTotal]                                      DECIMAL (18, 2) NULL,
    [PremioTotal_II]                                   DECIMAL (18, 2) NULL,
    [Franquia]                                         DECIMAL (18, 2) NULL,
    [Franquia_II]                                      DECIMAL (18, 2) NULL,
    [DanosMateriais]                                   DECIMAL (18, 2) NULL,
    [DanosCorporais]                                   DECIMAL (18, 2) NULL,
    [APP_Morte]                                        DECIMAL (18, 2) NULL,
    [App_Invalidez]                                    DECIMAL (18, 2) NULL,
    [DanosMorais]                                      DECIMAL (18, 2) NULL,
    [Assitencia]                                       INT             NULL,
    [DanosVidros]                                      INT             NULL,
    [CarroReserva]                                     INT             NULL,
    [ExtensaoReboque]                                  INT             NULL,
    [Situacao]                                         VARCHAR (1)     NULL,
    [ZeroKm]                                           VARCHAR (1)     NULL,
    [CodigoFipe]                                       INT             NULL,
    [Modelo]                                           VARCHAR (200)   NULL,
    [Combustivel]                                      VARCHAR (50)    NULL,
    [Placa]                                            VARCHAR (10)    NULL,
    [UFPlaca]                                          VARCHAR (2)     NULL,
    [AnoFabricacao]                                    INT             NULL,
    [AnoModelo]                                        INT             NULL,
    [Chassi]                                           VARCHAR (200)   NULL,
    [TipoSeguro]                                       VARCHAR (50)    NULL,
    [NomeOperador]                                     VARCHAR (200)   NULL,
    [GrupoProducao]                                    INT             NULL,
    [InicioVigencia]                                   DATE            NULL,
    [FinalVigencia]                                    DATE            NULL,
    [Tipo_Cobertura]                                   INT             NULL,
    [Cobertura]                                        INT             NULL,
    [Padrao]                                           INT             NULL,
    [PadraoDescricao]                                  VARCHAR (200)   NULL,
    [CEPResidencia]                                    VARCHAR (10)    NULL,
    [ChassiRemarcado]                                  INT             NULL,
    [Antifurto]                                        INT             NULL,
    [VeiculosResidencia]                               INT             NULL,
    [QuilometroMes]                                    INT             NULL,
    [CoberturaBlindagem]                               INT             NULL,
    [KitGas]                                           INT             NULL,
    [TipoCalculo]                                      INT             NULL,
    [TipoSeguro_II]                                    INT             NULL,
    [PrincipalCondutorConsiderado]                     INT             NULL,
    [PrincipalCondutorEstuda]                          INT             NULL,
    [PrincipalCondutorTipoResidencia]                  INT             NULL,
    [PrincipalCondutorRoubo2Anos]                      INT             NULL,
    [PessoasResidentesConduzirVeiculo]                 INT             NULL,
    [OutrasPessoasConduzir]                            INT             NULL,
    [KmVeiculoCirculaMes]                              INT             NULL,
    [UtilizacaoVeiculo]                                INT             NULL,
    [RelacaoPrincipalCondutorcomSegurado]              INT             NULL,
    [CPFPRincipalCondutor]                             VARCHAR (20)    NULL,
    [NomePrincipalCondutor]                            VARCHAR (200)   NULL,
    [DataNascimentoPrincipalCondutor]                  DATE            NULL,
    [EstadoCivilPrincipalCondutor]                     VARCHAR (1)     NULL,
    [TempoHabilitacaoPrincipalCondutor]                INT             NULL,
    [RelacaoPessoaComCondutor]                         INT             NULL,
    [PessoaResideComCondutor]                          INT             NULL,
    [PessoaPossuiVeiculo]                              INT             NULL,
    [PessoaConduzVeiculo]                              INT             NULL,
    [Acessorios]                                       VARCHAR (1)     NULL,
    [ValorRadioAM_FM]                                  DECIMAL (18, 2) NULL,
    [ValorCDPlayer]                                    DECIMAL (18, 2) NULL,
    [ValorDVDPlayer]                                   DECIMAL (18, 2) NULL,
    [ValorBlindagem]                                   DECIMAL (18, 2) NULL,
    [ValorKitGas]                                      DECIMAL (18, 2) NULL,
    [ValorRodaEspeciais]                               DECIMAL (18, 2) NULL,
    [ValorRodaLigaLeve]                                DECIMAL (18, 2) NULL,
    [ValorAutoFalantes]                                DECIMAL (18, 2) NULL,
    [AirBagMotorista]                                  VARCHAR (1)     NULL,
    [FreiosAbs]                                        VARCHAR (1)     NULL,
    [VidrosEletricos]                                  VARCHAR (1)     NULL,
    [DirecaoHidraulica]                                VARCHAR (1)     NULL,
    [ArCondicionado]                                   VARCHAR (1)     NULL,
    [TetoSolar]                                        VARCHAR (1)     NULL,
    [BancosCouro]                                      VARCHAR (1)     NULL,
    [CambioAutomaticoHidraulico]                       VARCHAR (1)     NULL,
    [TravasEletricasPortas]                            VARCHAR (1)     NULL,
    [QtdeSinistroApoliceAnterior]                      INT             NULL,
    [PercAjusteTabelaFIPE]                             INT             NULL,
    [GuardaVeiculoGaragemColegioFaculdadePosgraduacao] INT             NULL,
    [GuardaVeiculoGaragemTrabalho]                     INT             NULL,
    [ClasseBonusApoliceAnterior]                       INT             NULL,
    [FinalVigenciaApoliceAnterior]                     DATE            NULL,
    [ModalidadeVR_VD]                                  INT             NULL,
    [DespesasExtras]                                   INT             NULL,
    [IsencaoFranquia]                                  VARCHAR (1)     NULL,
    [DespesasLocomocao]                                VARCHAR (1)     NULL,
    [HigienizacaoVeiculo]                              VARCHAR (1)     NULL,
    [NomeFraqnuia_1]                                   VARCHAR (50)    NULL,
    [NomeFranquia_2]                                   VARCHAR (100)   NULL,
    [MensagemFranquia_1]                               VARCHAR (MAX)   NULL,
    [MensagemFranquia_2]                               VARCHAR (MAX)   NULL,
    [Franquiaescolhida]                                VARCHAR (100)   NULL,
    [PremioEscolhido]                                  DECIMAL (18, 2) NULL,
    [ValorFranquiaEscolhido]                           DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_MultiCalculoMS] PRIMARY KEY CLUSTERED ([Codigo] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [idx_ProdutoCpf]
    ON [Marketing].[RelatorioMulticalculoMS]([CGC_CPF] ASC, [ProdutoEfetivado] ASC, [NomeProduto] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [idx_Produto]
    ON [Marketing].[RelatorioMulticalculoMS]([ProdutoEfetivado] ASC, [NomeProduto] ASC) WITH (FILLFACTOR = 90);

