CREATE TABLE [Marketing].[RenovacaoMrEmpresarial] (
    [Codigo]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDContrato]        BIGINT          NOT NULL,
    [CodigoCliente]     BIGINT          NOT NULL,
    [IDProduto]         INT             NOT NULL,
    [NumeroRg]          VARCHAR (30)    NULL,
    [OrgaoRg]           VARCHAR (30)    NULL,
    [DiaProtecao]       VARCHAR (100)   NULL,
    [ValorIof]          DECIMAL (18, 2) NULL,
    [NumeroCodigoBarra] VARCHAR (200)   NULL,
    [LocalPagamento]    VARCHAR (300)   NULL,
    [DataVencimento]    DATE            NULL,
    [NomeCedente]       VARCHAR (300)   NULL,
    [Cedente]           VARCHAR (50)    NULL,
    [DataDocumento]     DATE            NULL,
    [NumeroDocumento]   VARCHAR (50)    NULL,
    [DataPRocessamento] DATE            NULL,
    [NossoNumero]       VARCHAR (50)    NULL,
    [ValorDocumento]    DECIMAL (18, 2) NULL,
    [ValorCobrado]      DECIMAL (18, 2) NULL,
    [ValorDesconto]     DECIMAL (18, 2) NULL,
    [CustoApolice]      DECIMAL (18, 2) NULL,
    [Encargos]          DECIMAL (18, 2) NULL,
    [Desconto]          DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_RenovacaoEmpresarial] PRIMARY KEY CLUSTERED ([Codigo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Contrato_RenovacaoMrEmpresarial] FOREIGN KEY ([IDContrato]) REFERENCES [Dados].[Contrato] ([ID]),
    CONSTRAINT [FK_Produto_RenovacaoMrEmpresarial] FOREIGN KEY ([IDProduto]) REFERENCES [Dados].[Produto] ([ID])
);

