CREATE TABLE [Indicadores].[ExtratoAnalitico] (
    [ID]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [Matricula]             VARCHAR (20)    NULL,
    [CPF]                   CHAR (14)       NULL,
    [Nome]                  VARCHAR (100)   NULL,
    [LotacaoUF]             VARCHAR (4)     NULL,
    [LotacaoCidade]         VARCHAR (60)    NULL,
    [LotacaoDataInicio]     DATE            NULL,
    [Cargo]                 VARCHAR (100)   NULL,
    [DataAtualizacaoFuncao] DATE            NULL,
    [DataInicioFuncao]      DATE            NULL,
    [IndicadorArea]         VARCHAR (30)    NULL,
    [CodigoUnidade]         SMALLINT        NOT NULL,
    [Produto]               VARCHAR (5)     NOT NULL,
    [NomeProduto]           VARCHAR (100)   NULL,
    [DataArquivo]           DATE            NOT NULL,
    [NumeroParcela]         INT             NULL,
    [NumeroApolice]         VARCHAR (20)    NULL,
    [NumeroTitulo]          VARCHAR (20)    NULL,
    [ValorBrutoAnalitico]   DECIMAL (19, 9) NULL,
    [ValorLiquidoAnalitico] DECIMAL (19, 6) NULL,
    [IRFAnalitico]          DECIMAL (19, 6) NULL,
    [ISSAnalitico]          DECIMAL (19, 6) NULL,
    [INSSAnalitico]         DECIMAL (19, 6) NULL,
    [Tipo]                  VARCHAR (2)     NULL,
    [ValorTeto]             DECIMAL (19, 4) NULL,
    [Retroativo]            BIT             DEFAULT ((0)) NOT NULL
);

