
CREATE VIEW Dados.vw_MailingBackSeg
AS
select 
AGENCIA                                                                                                                                                                                                                                                          
,NOME_AGENCIA                                                                                                                                                                                                                                                     
,FILIAL                                                                                                                                                                                                                                                           
,NOME_FILIAL                                                                                                                                                                                                                                                      
,ESCRIT                                                                                                                                                                                                                                                           
,NOME_ESCRIT                                                                                                                                                                                                                                                      
,TER_VIG                                                                                                                                                                                                                                                          
,APOLICE                                                                                                                                                                                                                                                          
,CPFCNPJ                                                                                                                                                                                                                                                          
,SEGURADO                                                                                                                                                                                                                                                         
,ENDERECO                                                                                                                                                                                                                                                         
,BAIRRO                                                                                                                                                                                                                                                           
,CIDADE                                                                                                                                                                                                                                                           
,UF                                                                                                                                                                                                                                                               
,CEP                                                                                                                                                                                                                                                              
,DDD                                                                                                                                                                                                                                                              
,FONE                                                                                                                                                                                                                                                             
,EMAIL                                                                                                                                                                                                                                                            
,VEICULO                                                                                              
,ANO_MOD                                                                                                                                                                                                  
,PLACA                                                                                                                                                                                                    
,CHASSI                                                                                               
,FORMA_COBR                                                                                           
,CONTA_DEBITO                                                                                         
,PRODUTO                                                                                              
,CL_BONUS_A_CONCEDER                                                                                  
,APP                                                                                                  
,RCDM                                                                                                 
,RCDP                                                                                                 
,VL_MERCADO                                                                                           
,ECONOMIARIO                                                                                          
,MATRICULA                                                                                            
,DDD_UNIDADE                                                                                          
,FONE_UNIDADE                                                                                         
,TEM_SINISTRO                                                                                         
,TP_FRANQUIA                                                                                          
,TEM_ENDOSSO                                                                                          
,TEM_PARC_PEND                                                                                        
,DDD_CELULAR                                                                                          
,CELULAR                                                                                              
,DDD_COMERCIAL                                                                                                                                                                                                                                                    
,TEL_COMERCIAL                                                                                                                                                                                                                                                    
,DDD_RES_1 
,TEL_RES_1 
,DDD_RES_2 
,TEL_RES_2 
,DDD_COM_1 
,TEL_COM_1 
,DDD_COM_2 
,TEL_COM_2 
,EMAIL_1                                                                                                                                                                                                                                                         
,ELEGIVEL_DESCONTO 
,VALOR_PARA_DESCONTO    
,FLAG_VIP 
,TIPO_CONTATO    
,FAIXA                                                                                                                                                                                                                                                           
,OBJETIVO             
,NOME_CAMPANHA                                                                                        
,COD_CAMPANHA     
,COD_MAILING
,SUBSTRING(COD_MAILING,18,4) + '-' + SUBSTRING(COD_MAILING,22,2) + '-' + SUBSTRING(COD_MAILING,24,2) AS DataMailing
from dw.FABRICA_CAMP.dbo.RENAUTVIN20130401 
