CREATE TABLE [Dados].[AtendimentoPARIndica] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [Protocolo]                CHAR (10)       NULL,
    [TMA]                      INT             NULL,
    [CPF]                      VARCHAR (18)    NOT NULL,
    [DataNascimento]           DATE            NULL,
    [Status_Ligacao]           TINYINT         NULL,
    [Status_Final]             TINYINT         NULL,
    [IDTelefoneEfetivo]        INT             NULL,
    [IDTelefone]               INT             NULL,
    [IDTelefoneAdicional]      INT             NULL,
    [IDEmail]                  INT             NULL,
    [DateTime_Contato_Efetivo] DATETIME        NULL,
    [IDAgenciaIndicacao]       SMALLINT        NULL,
    [Contato_Mkt_Direto]       VARCHAR (80)    NULL,
    [Produto_Efetivado]        VARCHAR (60)    NULL,
    [NumeroProposta]           VARCHAR (20)    NULL,
    [IDVeiculo]                INT             NULL,
    [BitVistoria]              CHAR (2)        NULL,
    [ProdutoOferta]            VARCHAR (60)    NULL,
    [Termino_Vigencia]         DATE            NULL,
    [Data_Renovacao]           DATE            NULL,
    [Premio_Atual]             DECIMAL (18, 6) NULL,
    [Premio_Sem_Desconto]      DECIMAL (18, 6) NULL,
    [FormaPagamento]           CHAR (30)       NULL,
    [QtdParcelas]              CHAR (4)        NULL,
    [Seguradora_Atual]         VARCHAR (30)    NULL,
    [CodigoMailing]            VARCHAR (60)    NULL,
    [CodigoCampanha]           VARCHAR (60)    NULL,
    [Regional_Par]             VARCHAR (100)   NULL,
    [Nome]                     VARCHAR (150)   NULL,
    [IDTipoCliente]            TINYINT         NULL,
    [DataArquivo]              DATE            NULL,
    [Arquivo]                  VARCHAR (60)    NULL,
    [CPF_NOFORMAT]             AS              (CONVERT([varchar](18),replace(replace([CPF],'.',''),'-',''))) PERSISTED,
    [DataArquivoCalculada]     AS              (CONVERT([date],(((('20'+substring([arquivo],(2),(2)))+'-')+substring([arquivo],(4),(2)))+'-')+substring([arquivo],(6),(2)),(101))) PERSISTED,
    [ContatoPossuiOutrosCS]    VARCHAR (50)    NULL,
    [SuperintendenciaRegional] VARCHAR (50)    NULL,
    [ServicoReceptivo]         VARCHAR (50)    NULL,
    [MilisegundosNaFila]       INT             NULL,
    [ChaveCliente]             INT             NULL,
    [ChaveIndicacao]           VARCHAR (100)   NULL,
    CONSTRAINT [PK_AtendimentoPARIndica_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_DadosAtendimentoPARIndica_DadosAtendimentoPARIndicaContatos_IDEmail] FOREIGN KEY ([IDEmail]) REFERENCES [Dados].[AtendimentoContatosPARIndica] ([ID]),
    CONSTRAINT [FK_DadosAtendimentoPARIndica_DadosAtendimentoPARIndicaContatos_IDTelefone] FOREIGN KEY ([IDTelefone]) REFERENCES [Dados].[AtendimentoContatosPARIndica] ([ID]),
    CONSTRAINT [FK_DadosAtendimentoPARIndica_DadosAtendimentoPARIndicaContatos_IDTelefoneAdicional] FOREIGN KEY ([IDTelefoneAdicional]) REFERENCES [Dados].[AtendimentoContatosPARIndica] ([ID]),
    CONSTRAINT [FK_DadosAtendimentoPARIndica_DadosAtendimentoPARIndicaContatos_IDTelefoneEfetivo] FOREIGN KEY ([IDTelefoneEfetivo]) REFERENCES [Dados].[AtendimentoContatosPARIndica] ([ID])
);

