CREATE TABLE [Dados].[CargoPROPAY] (
    [ID]        SMALLINT      IDENTITY (1, 1) NOT NULL,
    [Codigo]    VARCHAR (10)  NULL,
    [Descricao] VARCHAR (150) NOT NULL,
    [IDEmpresa] SMALLINT      NULL,
    CONSTRAINT [PK_CargoPROPAY] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_CARGOPROPAY_REFERENCE_EMPRESA] FOREIGN KEY ([IDEmpresa]) REFERENCES [Dados].[Empresa] ([ID])
);

