CREATE TABLE [Dados].[DetalhesCorrespondente] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [IDCorrespondente]         INT             NOT NULL,
    [Socio1Nome]               VARCHAR (200)   NULL,
    [Socio1Telefone]           VARCHAR (50)    NULL,
    [Socio1Celular]            VARCHAR (50)    NULL,
    [Socio1Email]              VARCHAR (50)    NULL,
    [Socio2Nome]               VARCHAR (200)   NULL,
    [Socio2Telefone]           VARCHAR (50)    NULL,
    [Socio2Celular]            VARCHAR (50)    NULL,
    [Socio2Email]              VARCHAR (200)   NULL,
    [Pedra]                    VARCHAR (50)    NULL,
    [QtdMediaConsignado_2016]  DECIMAL (19, 2) NULL,
    [VolumeConsignado_2016]    DECIMAL (19, 2) NULL,
    [QTDPrestamista_2016]      DECIMAL (19, 2) NULL,
    [VolumePrestamista_2016]   DECIMAL (19, 2) NULL,
    [QTDVida_2016]             DECIMAL (19, 2) NULL,
    [PerPenetracaoFisica_2016] DECIMAL (19, 2) NULL,
    [QtdMediaConsignado_2015]  DECIMAL (19, 2) NULL,
    [VolumeConsignado_2015]    DECIMAL (19, 2) NULL,
    [QTDPrestamista_2015]      DECIMAL (19, 2) NULL,
    [VolumePrestamista_2015]   DECIMAL (19, 2) NULL,
    [QTDVida_2015]             DECIMAL (19, 2) NULL,
    [PerPenetracaoFisica_2015] DECIMAL (19, 2) NULL,
    [DataSistema]              DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [Socio1CPF]                VARCHAR (20)    NULL,
    [Socio2CPF]                VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_DetalhesCorrespondente_Correspondente] FOREIGN KEY ([IDCorrespondente]) REFERENCES [Dados].[Correspondente] ([ID])
);

