CREATE TABLE [Dados].[funcionario_bkp_fabio] (
    [ID]                            INT              IDENTITY (1, 1) NOT NULL,
    [Nome]                          VARCHAR (100)    NULL,
    [CPF]                           CHAR (14)        NULL,
    [Email]                         VARCHAR (100)    NULL,
    [Matricula]                     VARCHAR (20)     NULL,
    [PIS]                           VARCHAR (20)     NULL,
    [IDEmpresa]                     SMALLINT         NOT NULL,
    [DDD]                           VARCHAR (5)      NULL,
    [Telefone]                      VARCHAR (20)     NULL,
    [IDMediaFile]                   UNIQUEIDENTIFIER NULL,
    [IDUsuario]                     UNIQUEIDENTIFIER NULL,
    [Salario]                       DECIMAL (20, 2)  NULL,
    [IDCentroCusto]                 SMALLINT         NULL,
    [IDGerenteRegional]             INT              NULL,
    [IDGerenteVenda]                INT              NULL,
    [IDGerenteNacional]             INT              NULL,
    [DataCriacao]                   DATE             NULL,
    [UltimoCargo]                   VARCHAR (100)    NULL,
    [DataAdmissao]                  DATE             NULL,
    [IDTipoVinculo]                 TINYINT          NULL,
    [IDUltimaFuncao]                SMALLINT         NULL,
    [IDUltimaSituacaoFuncionario]   SMALLINT         NULL,
    [DataAtualizacaoCentroCusto]    DATE             NULL,
    [DataAtualizacaoCargo]          DATE             NULL,
    [DataAtualizacaoVolta]          DATE             NULL,
    [DataSistema]                   DATETIME2 (7)    NULL,
    [IDSexo]                        TINYINT          NULL,
    [DataNascimento]                DATE             NULL,
    [IDUltimaUnidade]               SMALLINT         NULL,
    [UltimoLotacaoEmail]            VARCHAR (100)    NULL,
    [UltimoParticipanteEmail]       VARCHAR (100)    NULL,
    [FuncaoIndicadorFaixa]          VARCHAR (30)     NULL,
    [NomeArquivo]                   VARCHAR (60)     NULL,
    [DataArquivo]                   DATE             NULL,
    [IDCargoPROPAY]                 SMALLINT         NULL,
    [DataUltimaSituacaoFuncionario] DATE             NULL,
    [IDEstadoCivil]                 TINYINT          NULL,
    [IDCargo]                       SMALLINT         NULL,
    [IDLotacao]                     SMALLINT         NULL,
    [DDDCelular]                    VARCHAR (5)      NULL,
    [Celular]                       VARCHAR (20)     NULL,
    [Endereco]                      VARCHAR (100)    NULL,
    [ComplementoEndereco]           VARCHAR (80)     NULL,
    [CEP]                           VARCHAR (9)      NULL,
    [Municipio]                     VARCHAR (80)     NULL,
    [Bairro]                        VARCHAR (80)     NULL,
    [UF]                            CHAR (2)         NULL,
    [IDIndicadorArea]               TINYINT          NULL,
    [VIP]                           BIT              NULL,
    [SiglaLotacao]                  VARCHAR (10)     NULL,
    [Hierarquia]                    VARCHAR (50)     NULL
);

