CREATE TABLE [Dados].[Parentesco] (
    [ID]        TINYINT      NOT NULL,
    [Descricao] VARCHAR (15) NULL,
    CONSTRAINT [PK_PARENTESCO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

