CREATE TABLE [Dados].[ProdutoSegmento] (
    [ID]        TINYINT      IDENTITY (1, 1) NOT NULL,
    [Descricao] VARCHAR (60) NULL,
    CONSTRAINT [PK_ProdutoSegmento] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [UNQ_Descricao] UNIQUE NONCLUSTERED ([Descricao] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

