CREATE TABLE [Dados].[PropostaPlano] (
    [ID]         BIGINT IDENTITY (1, 1) NOT NULL,
    [IDPlano]    INT    NOT NULL,
    [IDProposta] BIGINT NOT NULL,
    CONSTRAINT [PK_PROPOSTAPLANO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE) ON [PRIMARY],
    CONSTRAINT [FK_PROPOSTA_FK_PROPOS_PLANO] FOREIGN KEY ([IDPlano]) REFERENCES [Dados].[Plano] ([ID])
);

