CREATE TABLE [Dados].[Sinistro] (
    [ID]                        BIGINT         IDENTITY (1, 1) NOT NULL,
    [NumeroSinistro]            BIGINT         NULL,
    [NumeroProtocolo]           INT            NULL,
    [IDContrato]                BIGINT         NOT NULL,
    [NumeroItem]                SMALLINT       NULL,
    [IDCertificado]             INT            NULL,
    [NumeroEndosso]             INT            NULL,
    [IDRamo]                    SMALLINT       NULL,
    [DataAviso]                 DATE           NULL,
    [DataSinistro]              DATE           NULL,
    [IDSituacaoSinistro]        SMALLINT       NULL,
    [IDSinistroCausa]           SMALLINT       NULL,
    [IDNaturezaSinistro]        SMALLINT       NULL,
    [NumeroSinistroMAPFRE]      BIGINT         NULL,
    [NumeroContratoResidencial] VARCHAR (30)   NULL,
    [NomeBeneficiario]          VARCHAR (40)   NULL,
    [CPFCNPJBeneficiario]       VARCHAR (18)   NULL,
    [PercentualParticipacao]    DECIMAL (5, 2) NULL,
    [CidadeBeneficiario]        VARCHAR (40)   NULL,
    [UFBeneficiario]            VARCHAR (2)    NULL,
    [IDFilialSinistro]          SMALLINT       NULL,
    [IDNaturezaHabitacional]    TINYINT        NULL,
    [CodigoFonte]               SMALLINT       NULL,
    [DataArquivo]               DATE           NULL,
    [Arquivo]                   VARCHAR (100)  NULL,
    CONSTRAINT [PK_SINISTRO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_SINISTRO_FK_SINIST_CERTIFIC] FOREIGN KEY ([IDCertificado]) REFERENCES [Dados].[Certificado] ([ID]),
    CONSTRAINT [FK_SINISTRO_FK_SINIST_CONTRATO] FOREIGN KEY ([IDContrato]) REFERENCES [Dados].[Contrato] ([ID]),
    CONSTRAINT [FK_SINISTRO_FK_SINIST_NATUREZA] FOREIGN KEY ([IDNaturezaHabitacional]) REFERENCES [Dados].[NaturezaHabitacional] ([ID]),
    CONSTRAINT [FK_SINISTRO_FK_SINIST_RAMO] FOREIGN KEY ([IDRamo]) REFERENCES [Dados].[Ramo] ([ID]),
    CONSTRAINT [FK_SINISTRO_FK_SINIST_SITUACAO] FOREIGN KEY ([IDSituacaoSinistro]) REFERENCES [Dados].[SituacaoSinistro] ([ID]),
    CONSTRAINT [FK_SINISTRO_REFERENCE_FILIALSI] FOREIGN KEY ([IDFilialSinistro]) REFERENCES [Dados].[FilialSinistro] ([ID]),
    CONSTRAINT [FK_SINISTRO_REFERENCE_SINISTRO] FOREIGN KEY ([IDSinistroCausa]) REFERENCES [Dados].[SinistroCausa] ([ID]),
    CONSTRAINT [UNQ_Sinistro] UNIQUE NONCLUSTERED ([NumeroSinistro] ASC, [NumeroProtocolo] ASC, [DataArquivo] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

