CREATE TABLE [Dados].[TipoVida] (
    [ID]        INT          IDENTITY (1, 1) NOT NULL,
    [Codigo]    VARCHAR (1)  NULL,
    [Descricao] VARCHAR (10) NULL,
    CONSTRAINT [PK_TIPOVIDA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE) ON [PRIMARY]
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20141112-173008]
    ON [Dados].[TipoVida]([Codigo] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
    ON [PRIMARY];

