CREATE TABLE [Dados].[TipoSituacaoSeguradoOdonto] (
    [ID]        SMALLINT     IDENTITY (1, 1) NOT NULL,
    [Descricao] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TIPOSITUACAOSEGURADOODONTO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

