CREATE TABLE [Dados].[TipoElegibilidade] (
    [ID]        SMALLINT     IDENTITY (1, 1) NOT NULL,
    [Descricao] VARCHAR (20) NULL,
    CONSTRAINT [PK_TIPOELEGIBILIDADE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

