CREATE TABLE [Dados].[TipoSegmento] (
    [ID]   SMALLINT     IDENTITY (1, 1) NOT NULL,
    [Nome] VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_TipoSegmento_ID] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

