CREATE TABLE [Dados].[TipoKit] (
    [ID]        INT          IDENTITY (1, 1) NOT NULL,
    [CodigoKIT] INT          NULL,
    [Descricao] VARCHAR (20) NULL,
    CONSTRAINT [PK_TIPOKIT] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE) ON [PRIMARY]
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20140806-105759]
    ON [Dados].[TipoKit]([ID] ASC)
    INCLUDE([CodigoKIT], [Descricao]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
    ON [PRIMARY];


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20141112-172924]
    ON [Dados].[TipoKit]([CodigoKIT] ASC, [Descricao] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
    ON [PRIMARY];

