CREATE TABLE [Dados].[TipoProdutor] (
    [ID]        TINYINT      NOT NULL,
    [Descricao] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

