CREATE TABLE [Dados].[TipoAdesao] (
    [ID]        INT          NOT NULL,
    [Descricao] VARCHAR (20) NULL,
    CONSTRAINT [PK_TIPOADESAO] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE) ON [PRIMARY]
);

