CREATE TABLE [Dados].[TipoModalidadePagamentoPropostaOdonto] (
    [ID]        SMALLINT     IDENTITY (1, 1) NOT NULL,
    [Descricao] VARCHAR (30) NULL,
    CONSTRAINT [PK_TIPOMODALIDADEPAGAMENTOPROP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

