CREATE TABLE [Dados].[Tmp_Certificado] (
    [ID]                                 INT             IDENTITY (1, 1) NOT NULL,
    [IDContrato]                         BIGINT          NULL,
    [IDProposta]                         BIGINT          NULL,
    [IDSeguradora]                       SMALLINT        NOT NULL,
    [NumeroCertificado]                  VARCHAR (20)    NOT NULL,
    [NumeroSICOB]                        VARCHAR (9)     NULL,
    [CPF]                                VARCHAR (18)    NULL,
    [NomeCliente]                        VARCHAR (140)   NULL,
    [DataNascimento]                     DATE            NULL,
    [IDAgencia]                          SMALLINT        NULL,
    [MatriculaIndicador]                 VARCHAR (20)    NULL,
    [MatriculaIndicadorGerente]          VARCHAR (20)    NULL,
    [MatriculaSuperintendenteRegional]   VARCHAR (20)    NULL,
    [MatriculaFuncionarioCaixa]          VARCHAR (20)    NULL,
    [DataInicioVigencia]                 DATE            NULL,
    [DataFimVigencia]                    DATE            NULL,
    [ValorPremioBruto]                   DECIMAL (19, 2) NULL,
    [ValorPremioLiquido]                 DECIMAL (19, 2) NULL,
    [IDIndicador]                        INT             NULL,
    [IDIndicadorGerente]                 INT             NULL,
    [IDIndicadorSuperintendenteRegional] INT             NULL,
    [IDFuncionarioCaixa]                 INT             NULL,
    [IDTipoSegurado]                     INT             NULL,
    [CodigoMoedaSegurada]                SMALLINT        NULL,
    [CodigoMoedaPremio]                  SMALLINT        NULL,
    [TipoBeneficio]                      CHAR (1)        NULL,
    [DataArquivo]                        DATE            NOT NULL,
    [Arquivo]                            VARCHAR (80)    NOT NULL
);

