CREATE TABLE [Dados].[Tmp_FinanceiroExtrato] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDProposta]             BIGINT          NOT NULL,
    [IDISMip]                TINYINT         NOT NULL,
    [PremioMip]              NUMERIC (16, 2) NULL,
    [IOFMip]                 NUMERIC (16, 2) NULL,
    [PremioMipAtrasado]      NUMERIC (16, 2) NULL,
    [IOFMipAtrasado]         NUMERIC (16, 2) NULL,
    [IDISInad]               TINYINT         NOT NULL,
    [PremioInad]             NUMERIC (16, 2) NULL,
    [IOFInad]                NUMERIC (16, 2) NULL,
    [PremioInadAtrasado]     NUMERIC (16, 2) NULL,
    [IOFInadAtrasado]        NUMERIC (16, 2) NULL,
    [PremioCancelado]        NUMERIC (16, 2) NULL,
    [IOFCancelado]           NUMERIC (16, 2) NULL,
    [IDISDfi]                TINYINT         NULL,
    [PremioDfi]              NUMERIC (16, 2) NULL,
    [IOFDfi]                 NUMERIC (16, 2) NULL,
    [IDISDfiAtrasado]        TINYINT         NOT NULL,
    [PremioDfiAtrasado]      NUMERIC (16, 2) NULL,
    [IOFDfiAtrasado]         NUMERIC (16, 2) NULL,
    [PercentualResseguro]    NUMERIC (5, 2)  NULL,
    [ValorPrRessMipMes]      NUMERIC (16, 2) NULL,
    [ValorPrRessMipAtrasado] NUMERIC (16, 2) NULL,
    [ValorPrRessDfiMes]      NUMERIC (16, 2) NULL,
    [ValorPrRessDfiAtrasado] NUMERIC (16, 2) NULL,
    [DataAmortizacao]        DATE            NULL,
    [DataArquivo]            DATE            NOT NULL,
    [Arquivo]                VARCHAR (100)   NULL,
    [DataInclusao]           DATE            NULL,
    [NumeroRI]               VARCHAR (5)     NULL,
    [NumeroOrdemInclusao]    VARCHAR (10)    NULL,
    [DataExclusao]           DATE            NULL,
    [NumeroRE]               VARCHAR (5)     NULL,
    [NumeroOrdemExclusao]    VARCHAR (10)    NULL
);

