CREATE TABLE [Troubleshooting].[ProblemaMailingBgek_15122014] (
    [CodCampanha]              VARCHAR (50)   NULL,
    [NomeCampanha]             VARCHAR (50)   NOT NULL,
    [CodMailing]               VARCHAR (58)   NULL,
    [Produto]                  VARCHAR (4)    NOT NULL,
    [Objetivo]                 VARCHAR (9)    NOT NULL,
    [CPF]                      VARCHAR (8000) NULL,
    [Nome]                     VARCHAR (150)  NULL,
    [Telefone1]                VARCHAR (20)   NOT NULL,
    [TipoTelefone1]            VARCHAR (5)    NOT NULL,
    [Telefone2]                VARCHAR (20)   NOT NULL,
    [TipoTelefone2]            VARCHAR (5)    NOT NULL,
    [Telefone3]                VARCHAR (20)   NOT NULL,
    [TipoTelefone3]            VARCHAR (5)    NOT NULL,
    [Telefone4]                VARCHAR (20)   NOT NULL,
    [TipoTelefone4]            VARCHAR (5)    NOT NULL,
    [Email]                    VARCHAR (70)   NOT NULL,
    [DataNascimento]           DATE           NULL,
    [ProdutoOferta]            VARCHAR (50)   NULL,
    [Produtos GCS]             VARCHAR (8000) NULL,
    [TipoCliente]              VARCHAR (10)   NULL,
    [CodigoAgenciaIndicacao]   SMALLINT       NOT NULL,
    [CodigoAgenciaCliente]     SMALLINT       NOT NULL,
    [IndicadorCaixa]           VARCHAR (20)   NULL,
    [ASVENIndicacao]           VARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [RegionalPar]              VARCHAR (100)  NULL,
    [TerminoVigenciaAtual]     VARCHAR (3)    NOT NULL,
    [SuperintendenciaRegional] SMALLINT       NULL,
    [DataCalculo]              DATE           NULL,
    [Veiculo]                  VARCHAR (100)  NULL,
    [CampoX3]                  VARCHAR (1)    NOT NULL,
    [CampoX4]                  VARCHAR (1)    NOT NULL,
    [CampoX5]                  VARCHAR (1)    NOT NULL,
    [CampoX6]                  VARCHAR (1)    NOT NULL,
    [CampoX7]                  VARCHAR (1)    NOT NULL,
    [CampoX8]                  VARCHAR (1)    NOT NULL,
    [CampoX9]                  VARCHAR (1)    NOT NULL,
    [CampoX10]                 VARCHAR (1)    NOT NULL,
    [CampoX11]                 VARCHAR (1)    NOT NULL,
    [CampoX12]                 VARCHAR (1)    NOT NULL,
    [CampoX13]                 VARCHAR (1)    NOT NULL,
    [CampoX14]                 VARCHAR (1)    NOT NULL,
    [CampoX15]                 VARCHAR (1)    NOT NULL,
    [CampoX16]                 VARCHAR (1)    NOT NULL,
    [CampoX17]                 VARCHAR (1)    NOT NULL,
    [CampoX18]                 VARCHAR (1)    NOT NULL,
    [CampoX19]                 VARCHAR (1)    NOT NULL,
    [CampoX20]                 VARCHAR (1)    NOT NULL,
    [CampoX21]                 VARCHAR (1)    NOT NULL,
    [CampoX22]                 VARCHAR (1)    NOT NULL,
    [CampoX23]                 VARCHAR (1)    NOT NULL,
    [CampoX24]                 VARCHAR (1)    NOT NULL,
    [CampoX25]                 VARCHAR (1)    NOT NULL,
    [CampoX26]                 VARCHAR (1)    NOT NULL,
    [CampoX27]                 VARCHAR (1)    NOT NULL,
    [CampoX28]                 VARCHAR (1)    NOT NULL,
    [CampoX29]                 VARCHAR (1)    NOT NULL,
    [CampoX30]                 VARCHAR (1)    NOT NULL,
    [CampoX31]                 VARCHAR (1)    NOT NULL,
    [CampoX32]                 VARCHAR (1)    NOT NULL,
    [CampoX33]                 VARCHAR (1)    NOT NULL,
    [CampoX34]                 VARCHAR (1)    NOT NULL,
    [CampoX35]                 VARCHAR (1)    NOT NULL,
    [CampoX36]                 VARCHAR (1)    NOT NULL,
    [CampoX37]                 VARCHAR (1)    NOT NULL,
    [CampoX38]                 VARCHAR (1)    NOT NULL,
    [CampoX39]                 VARCHAR (1)    NOT NULL,
    [CampoX40]                 VARCHAR (1)    NOT NULL,
    [CampoX41]                 VARCHAR (1)    NOT NULL,
    [CampoX42]                 VARCHAR (1)    NOT NULL,
    [DataRefMailing]           DATE           NULL,
    [Economiario]              BIT            NULL
);

