CREATE TABLE [Mailing].[MailingAutoKPN_Teste] (
    [ID]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [CodCampanha]              VARCHAR (50)   NULL,
    [NomeCampanha]             VARCHAR (50)   NOT NULL,
    [CodMailing]               VARCHAR (58)   NULL,
    [Produto]                  VARCHAR (4)    NOT NULL,
    [Objetivo]                 VARCHAR (9)    NOT NULL,
    [CPF]                      VARCHAR (18)   NULL,
    [Nome]                     VARCHAR (150)  NULL,
    [Telefone1]                VARCHAR (20)   NOT NULL,
    [TipoTelefone1]            VARCHAR (5)    NOT NULL,
    [Telefone2]                VARCHAR (20)   NOT NULL,
    [TipoTelefone2]            VARCHAR (5)    NOT NULL,
    [Telefone3]                VARCHAR (20)   NOT NULL,
    [TipoTelefone3]            VARCHAR (5)    NOT NULL,
    [Telefone4]                VARCHAR (20)   NOT NULL,
    [TipoTelefone4]            VARCHAR (5)    NOT NULL,
    [Email]                    VARCHAR (70)   NOT NULL,
    [DataNascimento]           DATE           NULL,
    [ProdutoOferta]            VARCHAR (100)  NULL,
    [Produtos GCS]             VARCHAR (8000) NULL,
    [TipoCliente]              VARCHAR (5)    NULL,
    [CodigoAgenciaIndicacao]   SMALLINT       NOT NULL,
    [CodigoAgenciaCliente]     SMALLINT       NOT NULL,
    [IndicadorCaixa]           VARCHAR (20)   NULL,
    [ASVENIndicacao]           VARCHAR (100)  NOT NULL,
    [RegionalPar]              VARCHAR (100)  NULL,
    [TerminoVigenciaAtual]     VARCHAR (3)    NOT NULL,
    [SuperintendenciaRegional] SMALLINT       NULL,
    [DataCalculo]              DATE           NULL,
    [Veiculo]                  VARCHAR (100)  NULL,
    [CampoX3]                  VARCHAR (100)  NOT NULL,
    [CampoX4]                  VARCHAR (100)  NOT NULL,
    [CampoX5]                  VARCHAR (100)  NOT NULL,
    [CampoX6]                  VARCHAR (100)  NOT NULL,
    [CampoX7]                  VARCHAR (100)  NOT NULL,
    [CampoX8]                  VARCHAR (100)  NOT NULL,
    [CampoX9]                  VARCHAR (100)  NOT NULL,
    [CampoX10]                 VARCHAR (100)  NOT NULL,
    [CampoX11]                 VARCHAR (100)  NOT NULL,
    [CampoX12]                 VARCHAR (100)  NOT NULL,
    [CampoX13]                 VARCHAR (100)  NOT NULL,
    [CampoX14]                 VARCHAR (100)  NOT NULL,
    [CampoX15]                 VARCHAR (100)  NOT NULL,
    [CampoX16]                 VARCHAR (100)  NOT NULL,
    [CampoX17]                 VARCHAR (100)  NOT NULL,
    [CampoX18]                 VARCHAR (100)  NOT NULL,
    [CampoX19]                 VARCHAR (100)  NOT NULL,
    [CampoX20]                 VARCHAR (100)  NOT NULL,
    [CampoX21]                 VARCHAR (100)  NOT NULL,
    [CampoX22]                 VARCHAR (100)  NOT NULL,
    [CampoX23]                 VARCHAR (100)  NOT NULL,
    [CampoX24]                 VARCHAR (100)  NOT NULL,
    [CampoX25]                 VARCHAR (100)  NOT NULL,
    [CampoX26]                 VARCHAR (100)  NOT NULL,
    [CampoX27]                 VARCHAR (100)  NOT NULL,
    [CampoX28]                 VARCHAR (100)  NOT NULL,
    [CampoX29]                 VARCHAR (100)  NOT NULL,
    [CampoX30]                 VARCHAR (100)  NOT NULL,
    [CampoX31]                 VARCHAR (100)  NOT NULL,
    [CampoX32]                 VARCHAR (100)  NOT NULL,
    [CampoX33]                 VARCHAR (100)  NOT NULL,
    [CampoX34]                 VARCHAR (100)  NOT NULL,
    [CampoX35]                 VARCHAR (100)  NOT NULL,
    [CampoX36]                 VARCHAR (100)  NOT NULL,
    [CampoX37]                 VARCHAR (100)  NOT NULL,
    [CampoX38]                 VARCHAR (100)  NOT NULL,
    [CampoX39]                 VARCHAR (100)  NOT NULL,
    [CampoX40]                 VARCHAR (100)  NULL,
    [CampoX41]                 VARCHAR (100)  NOT NULL,
    [CampoX42]                 VARCHAR (100)  NOT NULL,
    [DataRefMailing]           DATE           NULL,
    [DataEnvioMailing]         DATE           NULL,
    [DDDTelefone1]             CHAR (2)       NULL,
    [TelefoneSemDDD1]          VARCHAR (10)   NULL,
    [DDDTelefone2]             CHAR (2)       NULL,
    [TelefoneSemDDD2]          VARCHAR (10)   NULL,
    [DDDTelefone3]             CHAR (2)       NULL,
    [TelefoneSemDDD3]          VARCHAR (10)   NULL,
    [Economiario]              BIT            NULL,
    [MailingBGek]              BIT            NULL,
    [IDTipoSeguro]             TINYINT        NULL
);

