CREATE TABLE [Mailing].[MailingAutoKPN] (
    [ID]                              BIGINT          IDENTITY (1, 1) NOT NULL,
    [CodCampanha]                     VARCHAR (50)    NULL,
    [NomeCampanha]                    VARCHAR (50)    NOT NULL,
    [CodMailing]                      VARCHAR (58)    NULL,
    [Produto]                         VARCHAR (4)     NOT NULL,
    [Objetivo]                        VARCHAR (9)     NOT NULL,
    [CPF]                             VARCHAR (18)    NULL,
    [Nome]                            VARCHAR (150)   NULL,
    [Telefone1]                       VARCHAR (20)    NOT NULL,
    [TipoTelefone1]                   VARCHAR (5)     NOT NULL,
    [Telefone2]                       VARCHAR (20)    NOT NULL,
    [TipoTelefone2]                   VARCHAR (5)     NOT NULL,
    [Telefone3]                       VARCHAR (20)    NOT NULL,
    [TipoTelefone3]                   VARCHAR (5)     NOT NULL,
    [Telefone4]                       VARCHAR (20)    CONSTRAINT [DF_MailingAutoKPN_Telefone4] DEFAULT ('') NOT NULL,
    [TipoTelefone4]                   VARCHAR (5)     CONSTRAINT [DF_MailingAutoKPN_TipoTelefone4] DEFAULT ('') NOT NULL,
    [Email]                           VARCHAR (70)    NOT NULL,
    [DataNascimento]                  DATE            NULL,
    [ProdutoOferta]                   VARCHAR (100)   NULL,
    [Produtos GCS]                    VARCHAR (8000)  NULL,
    [TipoCliente]                     VARCHAR (5)     NULL,
    [CodigoAgenciaIndicacao]          SMALLINT        NOT NULL,
    [CodigoAgenciaCliente]            SMALLINT        NOT NULL,
    [IndicadorCaixa]                  VARCHAR (20)    NULL,
    [ASVENIndicacao]                  VARCHAR (100)   NOT NULL,
    [RegionalPar]                     VARCHAR (100)   NULL,
    [TerminoVigenciaAtual]            VARCHAR (3)     NOT NULL,
    [SuperintendenciaRegional]        SMALLINT        NULL,
    [DataCalculo]                     DATE            NULL,
    [Veiculo]                         VARCHAR (100)   NULL,
    [CampoX3]                         VARCHAR (100)   NOT NULL,
    [CampoX4]                         VARCHAR (100)   NOT NULL,
    [CampoX5]                         VARCHAR (100)   NOT NULL,
    [CampoX6]                         VARCHAR (100)   NOT NULL,
    [CampoX7]                         VARCHAR (100)   NOT NULL,
    [CampoX8]                         VARCHAR (100)   NOT NULL,
    [CampoX9]                         VARCHAR (100)   NOT NULL,
    [CampoX10]                        VARCHAR (100)   NOT NULL,
    [CampoX11]                        VARCHAR (100)   NOT NULL,
    [CampoX12]                        VARCHAR (100)   NOT NULL,
    [CampoX13]                        VARCHAR (100)   NOT NULL,
    [CampoX14]                        VARCHAR (100)   NOT NULL,
    [CampoX15]                        VARCHAR (100)   NOT NULL,
    [CampoX16]                        VARCHAR (100)   NOT NULL,
    [CampoX17]                        VARCHAR (100)   NOT NULL,
    [CampoX18]                        VARCHAR (100)   NOT NULL,
    [CampoX19]                        VARCHAR (100)   NOT NULL,
    [CampoX20]                        VARCHAR (100)   NOT NULL,
    [CampoX21]                        VARCHAR (100)   NOT NULL,
    [CampoX22]                        VARCHAR (100)   NOT NULL,
    [CampoX23]                        VARCHAR (100)   NOT NULL,
    [CampoX24]                        VARCHAR (100)   NOT NULL,
    [CampoX25]                        VARCHAR (100)   NOT NULL,
    [CampoX26]                        VARCHAR (100)   NOT NULL,
    [CampoX27]                        VARCHAR (100)   NOT NULL,
    [CampoX28]                        VARCHAR (100)   NOT NULL,
    [CampoX29]                        VARCHAR (100)   NOT NULL,
    [CampoX30]                        VARCHAR (100)   NOT NULL,
    [CampoX31]                        VARCHAR (100)   NOT NULL,
    [CampoX32]                        VARCHAR (100)   NOT NULL,
    [CampoX33]                        VARCHAR (100)   NOT NULL,
    [CampoX34]                        VARCHAR (100)   NOT NULL,
    [CampoX35]                        VARCHAR (100)   NOT NULL,
    [CampoX36]                        VARCHAR (100)   NOT NULL,
    [CampoX37]                        VARCHAR (100)   NOT NULL,
    [CampoX38]                        VARCHAR (100)   NOT NULL,
    [CampoX39]                        VARCHAR (100)   NOT NULL,
    [CampoX40]                        VARCHAR (100)   NULL,
    [CampoX41]                        VARCHAR (100)   NOT NULL,
    [CampoX42]                        VARCHAR (100)   NOT NULL,
    [DataRefMailing]                  DATE            NULL,
    [DataGeracao]                     DATETIME2 (7)   CONSTRAINT [DF_MailingAutoKPN_DataGeracao] DEFAULT (getdate()) NOT NULL,
    [DataEnvioMailing]                DATE            NULL,
    [DDDTelefone1]                    AS              (CONVERT([char](2),left([Telefone1],(2)))) PERSISTED,
    [TelefoneSemDDD1]                 AS              (CONVERT([varchar](10),substring([Telefone1],(3),len(rtrim([Telefone1]))))) PERSISTED,
    [DDDTelefone2]                    AS              (CONVERT([char](2),left([Telefone2],(2)))) PERSISTED,
    [TelefoneSemDDD2]                 AS              (CONVERT([varchar](10),substring([Telefone2],(3),len(rtrim([Telefone2]))))) PERSISTED,
    [DDDTelefone3]                    AS              (CONVERT([char](2),left([Telefone3],(2)))) PERSISTED,
    [TelefoneSemDDD3]                 AS              (CONVERT([varchar](10),substring([Telefone3],(3),len(rtrim([Telefone3]))))) PERSISTED,
    [Economiario]                     BIT             NULL,
    [MailingBGek]                     BIT             NULL,
    [IDTipoSeguro]                    TINYINT         NULL,
    [DataNascimentoPrincipalCondutor] DATE            NULL,
    [EstadoCivilPrincipalCondutor]    VARCHAR (50)    NULL,
    [PrincipalCondutorTrabalha]       VARCHAR (50)    NULL,
    [PrincipalCondutorEstuda]         VARCHAR (50)    NULL,
    [CadastroOpcionais]               VARCHAR (200)   NULL,
    [ValorFranquia]                   DECIMAL (19, 2) NULL,
    [DataArquivo]                     DATE            NULL,
    [CPF_Format]                      AS              ((((((substring([CPF],(1),(3))+'.')+substring([CPF],(4),(3)))+'.')+substring([CPF],(7),(3)))+'-')+substring([CPF],(10),(2))),
    [CPF_Format_CS]                   AS              ((((((substring([CPF],(1),(3))+'.')+substring([CPF],(4),(3)))+'.')+substring([CPF],(7),(3)))+'-')+substring([CPF],(10),(2)) collate SQL_Latin1_General_CP1_CS_AS),
    CONSTRAINT [PK_MailingAutoKPN] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE),
    CONSTRAINT [FK_MailingAutoKPN_TipoSeguro] FOREIGN KEY ([IDTipoSeguro]) REFERENCES [Dados].[TipoSeguro] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IDX_NCL_MailingAutoKPN]
    ON [Mailing].[MailingAutoKPN]([DataRefMailing] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IDX_NCL_MailingAutoKPN_SuportMS]
    ON [Mailing].[MailingAutoKPN]([DataCalculo] ASC, [CPF] ASC)
    INCLUDE([Nome], [DataNascimento], [Telefone1], [Telefone2], [Telefone3], [Telefone4], [Email]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IdxNCL_MailingAutoKPN_Economiario]
    ON [Mailing].[MailingAutoKPN]([Economiario] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IDX_Nonclustered_DataRefMailing]
    ON [Mailing].[MailingAutoKPN]([DataRefMailing] ASC)
    INCLUDE([CPF]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IDX_Nonclustered_Mailing_CPF_20151014]
    ON [Mailing].[MailingAutoKPN]([CPF] ASC, [DataRefMailing] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IDX_NCL_DataRefMailing_MailingAutoKPN]
    ON [Mailing].[MailingAutoKPN]([DataRefMailing] ASC)
    INCLUDE([CPF]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE ON PARTITIONS (33), DATA_COMPRESSION = PAGE ON PARTITIONS (34), DATA_COMPRESSION = PAGE ON PARTITIONS (35), DATA_COMPRESSION = PAGE ON PARTITIONS (36), DATA_COMPRESSION = PAGE ON PARTITIONS (37), DATA_COMPRESSION = PAGE ON PARTITIONS (38), DATA_COMPRESSION = PAGE ON PARTITIONS (39), DATA_COMPRESSION = PAGE ON PARTITIONS (40), DATA_COMPRESSION = PAGE ON PARTITIONS (41), DATA_COMPRESSION = PAGE ON PARTITIONS (42), DATA_COMPRESSION = PAGE ON PARTITIONS (43), DATA_COMPRESSION = PAGE ON PARTITIONS (44), DATA_COMPRESSION = PAGE ON PARTITIONS (45), DATA_COMPRESSION = PAGE ON PARTITIONS (46), DATA_COMPRESSION = PAGE ON PARTITIONS (47), DATA_COMPRESSION = PAGE ON PARTITIONS (48), DATA_COMPRESSION = PAGE ON PARTITIONS (49), DATA_COMPRESSION = PAGE ON PARTITIONS (50), DATA_COMPRESSION = PAGE ON PARTITIONS (51), DATA_COMPRESSION = PAGE ON PARTITIONS (52), DATA_COMPRESSION = PAGE ON PARTITIONS (53), DATA_COMPRESSION = PAGE ON PARTITIONS (54), DATA_COMPRESSION = PAGE ON PARTITIONS (55), DATA_COMPRESSION = PAGE ON PARTITIONS (56), DATA_COMPRESSION = PAGE ON PARTITIONS (57), DATA_COMPRESSION = PAGE ON PARTITIONS (58), DATA_COMPRESSION = PAGE ON PARTITIONS (59), DATA_COMPRESSION = PAGE ON PARTITIONS (60), DATA_COMPRESSION = PAGE ON PARTITIONS (61), DATA_COMPRESSION = PAGE ON PARTITIONS (62), DATA_COMPRESSION = PAGE ON PARTITIONS (63), DATA_COMPRESSION = PAGE ON PARTITIONS (64), DATA_COMPRESSION = PAGE ON PARTITIONS (65), DATA_COMPRESSION = PAGE ON PARTITIONS (66), DATA_COMPRESSION = PAGE ON PARTITIONS (67), DATA_COMPRESSION = PAGE ON PARTITIONS (68), DATA_COMPRESSION = PAGE ON PARTITIONS (69), DATA_COMPRESSION = PAGE ON PARTITIONS (70), DATA_COMPRESSION = PAGE ON PARTITIONS (71), DATA_COMPRESSION = PAGE ON PARTITIONS (72), DATA_COMPRESSION = PAGE ON PARTITIONS (73), DATA_COMPRESSION = PAGE ON PARTITIONS (74), DATA_COMPRESSION = PAGE ON PARTITIONS (75), DATA_COMPRESSION = PAGE ON PARTITIONS (76), DATA_COMPRESSION = PAGE ON PARTITIONS (77), DATA_COMPRESSION = PAGE ON PARTITIONS (78), DATA_COMPRESSION = PAGE ON PARTITIONS (79), DATA_COMPRESSION = PAGE ON PARTITIONS (80), DATA_COMPRESSION = PAGE ON PARTITIONS (81), DATA_COMPRESSION = PAGE ON PARTITIONS (82), DATA_COMPRESSION = PAGE ON PARTITIONS (83), DATA_COMPRESSION = PAGE ON PARTITIONS (84), DATA_COMPRESSION = PAGE ON PARTITIONS (85), DATA_COMPRESSION = PAGE ON PARTITIONS (86), DATA_COMPRESSION = PAGE ON PARTITIONS (87), DATA_COMPRESSION = PAGE ON PARTITIONS (88), DATA_COMPRESSION = PAGE ON PARTITIONS (89), DATA_COMPRESSION = PAGE ON PARTITIONS (90), DATA_COMPRESSION = PAGE ON PARTITIONS (91), DATA_COMPRESSION = PAGE ON PARTITIONS (92), DATA_COMPRESSION = PAGE ON PARTITIONS (93), DATA_COMPRESSION = PAGE ON PARTITIONS (94), DATA_COMPRESSION = PAGE ON PARTITIONS (95), DATA_COMPRESSION = PAGE ON PARTITIONS (96), DATA_COMPRESSION = PAGE ON PARTITIONS (97), DATA_COMPRESSION = PAGE ON PARTITIONS (98), DATA_COMPRESSION = PAGE ON PARTITIONS (99), DATA_COMPRESSION = PAGE ON PARTITIONS (100), DATA_COMPRESSION = PAGE ON PARTITIONS (101), DATA_COMPRESSION = PAGE ON PARTITIONS (102), DATA_COMPRESSION = PAGE ON PARTITIONS (103), DATA_COMPRESSION = PAGE ON PARTITIONS (104), DATA_COMPRESSION = PAGE ON PARTITIONS (105), DATA_COMPRESSION = PAGE ON PARTITIONS (106), DATA_COMPRESSION = PAGE ON PARTITIONS (107), DATA_COMPRESSION = PAGE ON PARTITIONS (108), DATA_COMPRESSION = PAGE ON PARTITIONS (109), DATA_COMPRESSION = PAGE ON PARTITIONS (110), DATA_COMPRESSION = PAGE ON PARTITIONS (111), DATA_COMPRESSION = PAGE ON PARTITIONS (112), DATA_COMPRESSION = PAGE ON PARTITIONS (113), DATA_COMPRESSION = PAGE ON PARTITIONS (114), DATA_COMPRESSION = PAGE ON PARTITIONS (115), DATA_COMPRESSION = PAGE ON PARTITIONS (116), DATA_COMPRESSION = PAGE ON PARTITIONS (117), DATA_COMPRESSION = PAGE ON PARTITIONS (118), DATA_COMPRESSION = PAGE ON PARTITIONS (119), DATA_COMPRESSION = PAGE ON PARTITIONS (120), DATA_COMPRESSION = PAGE ON PARTITIONS (121), DATA_COMPRESSION = PAGE ON PARTITIONS (122), DATA_COMPRESSION = PAGE ON PARTITIONS (123), DATA_COMPRESSION = PAGE ON PARTITIONS (124), DATA_COMPRESSION = PAGE ON PARTITIONS (125), DATA_COMPRESSION = PAGE ON PARTITIONS (126), DATA_COMPRESSION = PAGE ON PARTITIONS (127), DATA_COMPRESSION = PAGE ON PARTITIONS (128), DATA_COMPRESSION = PAGE ON PARTITIONS (129), DATA_COMPRESSION = PAGE ON PARTITIONS (130), DATA_COMPRESSION = PAGE ON PARTITIONS (131), DATA_COMPRESSION = PAGE ON PARTITIONS (132), DATA_COMPRESSION = PAGE ON PARTITIONS (133), DATA_COMPRESSION = PAGE ON PARTITIONS (134), DATA_COMPRESSION = PAGE ON PARTITIONS (135), DATA_COMPRESSION = PAGE ON PARTITIONS (136), DATA_COMPRESSION = PAGE ON PARTITIONS (137), DATA_COMPRESSION = PAGE ON PARTITIONS (138), DATA_COMPRESSION = PAGE ON PARTITIONS (139), DATA_COMPRESSION = PAGE ON PARTITIONS (140), DATA_COMPRESSION = PAGE ON PARTITIONS (141), DATA_COMPRESSION = PAGE ON PARTITIONS (142), DATA_COMPRESSION = PAGE ON PARTITIONS (143), DATA_COMPRESSION = PAGE ON PARTITIONS (144), DATA_COMPRESSION = PAGE ON PARTITIONS (145), DATA_COMPRESSION = PAGE ON PARTITIONS (146), DATA_COMPRESSION = PAGE ON PARTITIONS (147), DATA_COMPRESSION = PAGE ON PARTITIONS (148), DATA_COMPRESSION = PAGE ON PARTITIONS (149), DATA_COMPRESSION = PAGE ON PARTITIONS (150), DATA_COMPRESSION = PAGE ON PARTITIONS (151), DATA_COMPRESSION = PAGE ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2), DATA_COMPRESSION = PAGE ON PARTITIONS (3), DATA_COMPRESSION = PAGE ON PARTITIONS (4), DATA_COMPRESSION = PAGE ON PARTITIONS (5), DATA_COMPRESSION = PAGE ON PARTITIONS (6), DATA_COMPRESSION = PAGE ON PARTITIONS (7), DATA_COMPRESSION = PAGE ON PARTITIONS (8), DATA_COMPRESSION = PAGE ON PARTITIONS (9), DATA_COMPRESSION = PAGE ON PARTITIONS (10), DATA_COMPRESSION = PAGE ON PARTITIONS (11), DATA_COMPRESSION = PAGE ON PARTITIONS (12), DATA_COMPRESSION = PAGE ON PARTITIONS (13), DATA_COMPRESSION = PAGE ON PARTITIONS (14), DATA_COMPRESSION = PAGE ON PARTITIONS (15), DATA_COMPRESSION = PAGE ON PARTITIONS (16), DATA_COMPRESSION = PAGE ON PARTITIONS (17), DATA_COMPRESSION = PAGE ON PARTITIONS (18), DATA_COMPRESSION = PAGE ON PARTITIONS (19), DATA_COMPRESSION = PAGE ON PARTITIONS (20), DATA_COMPRESSION = PAGE ON PARTITIONS (21), DATA_COMPRESSION = PAGE ON PARTITIONS (22), DATA_COMPRESSION = PAGE ON PARTITIONS (23), DATA_COMPRESSION = PAGE ON PARTITIONS (24), DATA_COMPRESSION = PAGE ON PARTITIONS (25), DATA_COMPRESSION = PAGE ON PARTITIONS (26), DATA_COMPRESSION = PAGE ON PARTITIONS (27), DATA_COMPRESSION = PAGE ON PARTITIONS (28), DATA_COMPRESSION = PAGE ON PARTITIONS (29), DATA_COMPRESSION = PAGE ON PARTITIONS (30), DATA_COMPRESSION = PAGE ON PARTITIONS (31), DATA_COMPRESSION = PAGE ON PARTITIONS (32))
    ON [PS_DADOS_DataCompetencia] ([DataRefMailing]);


GO
CREATE NONCLUSTERED INDEX [ncl_idx_MailingAutoKPN_cpf_CS]
    ON [Mailing].[MailingAutoKPN]([CPF_Format_CS] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

