CREATE TABLE [dbo].[AcompanhamentoApoVig20151103] (
    [CodigoProduto]                  VARCHAR (300) NULL,
    [DescricaoProduto]               VARCHAR (300) NULL,
    [NumeroProposta]                 VARCHAR (300) NULL,
    [NumeroApolice]                  VARCHAR (300) NULL,
    [CPFCNPJSegurado]                VARCHAR (300) NULL,
    [NomeSegurado]                   VARCHAR (300) NULL,
    [DDDTelefone]                    VARCHAR (300) NULL,
    [TelefoneSegurado]               VARCHAR (300) NULL,
    [NroParcelas]                    VARCHAR (300) NULL,
    [DataInicioVigencia]             VARCHAR (300) NULL,
    [DataTerminoVigencia]            VARCHAR (300) NULL,
    [BonusAtual]                     VARCHAR (300) NULL,
    [ImportanciaSegurada]            VARCHAR (300) NULL,
    [PremioTotalBruto]               VARCHAR (300) NULL,
    [TipoApolice]                    VARCHAR (300) NULL,
    [RenovacaoAutomatica]            VARCHAR (300) NULL,
    [FormaDeCobrança]                VARCHAR (300) NULL,
    [NomeAgenciaVenda ]              VARCHAR (300) NULL,
    [NumeroAgenciaVenda ]            VARCHAR (300) NULL,
    [NomeSuperintendenciaRegional]   VARCHAR (300) NULL,
    [NumeroSuperintendenciaRegional] VARCHAR (300) NULL,
    [NomeFilial ]                    VARCHAR (300) NULL,
    [NumeroFilial]                   VARCHAR (300) NULL,
    [NomeCanalVenda]                 VARCHAR (300) NULL,
    [MatriculaIndicador]             VARCHAR (300) NULL,
    [NomeIndicador]                  VARCHAR (300) NULL,
    [UsuarioEmissao]                 VARCHAR (300) NULL,
    [Ramo]                           VARCHAR (300) NULL,
    [CidadeBemSegurado]              VARCHAR (300) NULL,
    [EnderecoBemSegurado]            VARCHAR (300) NULL,
    [BairroBemSegurado]              VARCHAR (300) NULL,
    [CEPBemSegurado]                 VARCHAR (300) NULL,
    [UFBemSegurado]                  VARCHAR (300) NULL,
    [TipoImovelBemSegurado]          VARCHAR (300) NULL,
    [DataEmissao]                    VARCHAR (300) NULL,
    [PremioLiquido]                  VARCHAR (300) NULL,
    [Custos]                         VARCHAR (300) NULL,
    [Adicional]                      VARCHAR (300) NULL,
    [IOF]                            VARCHAR (300) NULL,
    [Comissao]                       VARCHAR (300) NULL,
    [TarifaBalcao]                   VARCHAR (300) NULL,
    [ComissaoIndicador]              VARCHAR (300) NULL,
    [PessoaFisicaJuridica ]          VARCHAR (300) NULL,
    [FaixaRendaIndividual]           VARCHAR (300) NULL,
    [FaixaRendaFamiliar]             VARCHAR (300) NULL,
    [Ocupacao]                       VARCHAR (300) NULL,
    [NomeEmpreendimento]             VARCHAR (300) NULL,
    [Setor]                          VARCHAR (300) NULL,
    [Rubrica]                        VARCHAR (300) NULL,
    [DescricaoRubrica]               VARCHAR (300) NULL,
    [DataProposta]                   VARCHAR (300) NULL,
    [Sexo]                           VARCHAR (300) NULL,
    [DataNascimento]                 VARCHAR (300) NULL,
    [EstadoCivil]                    VARCHAR (300) NULL,
    [Email]                          VARCHAR (300) NULL
);

