CREATE TABLE [dbo].[APOLICE_MAPFRE_TEMP] (
    [ID]                        INT             NOT NULL,
    [TipoRegistro]              VARCHAR (2)     NULL,
    [NumeroProduto]             VARCHAR (3)     NULL,
    [NumeroApolice]             VARCHAR (13)    NULL,
    [NumeroEndosso]             VARCHAR (5)     NULL,
    [CodigoCorretor]            VARCHAR (5)     NULL,
    [CodigoMoeda]               VARCHAR (2)     NULL,
    [DataEmissao]               DATE            NULL,
    [DataInicioVigencia]        DATE            NULL,
    [DataFimVigencia]           DATE            NULL,
    [CPFCNPJ]                   VARCHAR (18)    NULL,
    [ApoliceAnterior]           VARCHAR (13)    NULL,
    [SinalComissao]             VARCHAR (1)     NULL,
    [PercentualComissao]        DECIMAL (28, 8) NULL,
    [SinalImportanciaSegurada]  VARCHAR (1)     NULL,
    [SomaImportanciasSeguradas] DECIMAL (28, 8) NULL,
    [SinalPremioLiquido]        VARCHAR (1)     NULL,
    [PremioLiquido]             DECIMAL (28, 8) NULL,
    [SinalEncargosNegativos]    VARCHAR (1)     NULL,
    [ValorEncargosFinanceiros]  DECIMAL (28, 8) NULL,
    [SinalCustoNegativa]        VARCHAR (1)     NULL,
    [ValorCustoApolice]         VARCHAR (17)    NULL,
    [SinalIOFNegativo]          VARCHAR (1)     NULL,
    [SinalPremioTotalNegativo]  VARCHAR (1)     NULL,
    [PremioTotal]               DECIMAL (28, 8) NULL,
    [QuantidadeItens]           VARCHAR (4)     NULL,
    [QuantidadeParcelas]        VARCHAR (2)     NULL,
    [TipoEndosso]               VARCHAR (2)     NULL,
    [UsuarioEmissor]            VARCHAR (2)     NULL,
    [CodigoNegocio]             VARCHAR (3)     NULL,
    [NumeroPropostaConvenio]    VARCHAR (20)    NULL,
    [FormaPagamento]            VARCHAR (2)     NULL,
    [SinalValorComissao]        VARCHAR (1)     NULL,
    [ValorComissao]             DECIMAL (28, 8) NULL,
    [TipoSeguro]                VARCHAR (1)     NULL,
    [SegmentoCliente]           VARCHAR (1)     NULL,
    [TipoPessoa]                VARCHAR (1)     NULL,
    [NomeTomador]               VARCHAR (30)    NULL,
    [NumeroPropostaVeraCruz]    VARCHAR (30)    NULL,
    [ApoliceProvisoria]         VARCHAR (1)     NULL,
    [CodSistemaCooperativo]     VARCHAR (1)     NULL,
    [CodigoAgenciaPAC]          VARCHAR (4)     NULL,
    [PAC]                       VARCHAR (2)     NULL,
    [NomeAgenciaPAC]            VARCHAR (50)    NULL,
    [CodigoProdutor]            VARCHAR (11)    NULL,
    [NomeProdutor]              VARCHAR (50)    NULL,
    [NumeroRamo]                VARCHAR (3)     NULL,
    [CPFCampanha]               VARCHAR (18)    NULL,
    [NumeroSorteio]             VARCHAR (10)    NULL,
    [NumeroSerieSorteio]        VARCHAR (3)     NULL,
    [NumeroBancoDebito]         VARCHAR (4)     NULL,
    [NumeroAgenciaDebito]       VARCHAR (4)     NULL,
    [DigitoAgenciaDebito]       VARCHAR (2)     NULL,
    [NumeroContaDebito]         VARCHAR (15)    NULL,
    [DigitoContaDebito]         VARCHAR (2)     NULL,
    [DataArquivo]               DATE            NULL,
    [NomeArquivo]               VARCHAR (50)    NULL,
    [ProdutoMrRural]            VARCHAR (3)     NULL,
    [NumeroEndossoMRRural]      VARCHAR (5)     NULL,
    [CodigoItem]                VARCHAR (4)     NULL,
    [Segurado]                  VARCHAR (18)    NULL,
    [AtividadeEmpresa]          VARCHAR (7)     NULL,
    [CEP]                       VARCHAR (8)     NULL,
    [Estado]                    VARCHAR (2)     NULL,
    [ComplementoRisco]          VARCHAR (50)    NULL,
    [DataVistoria]              DATE            NULL,
    [DescricaoRisco]            VARCHAR (50)    NULL,
    [EnderecoRisco]             VARCHAR (50)    NULL,
    [NumeroRisco]               VARCHAR (9)     NULL,
    [PercentualIR]              VARCHAR (10)    NULL,
    [BairroCidade]              VARCHAR (50)    NULL,
    [TipoRisco]                 VARCHAR (2)     NULL,
    [PropriedadeEmpresa]        VARCHAR (50)    NULL
);


GO
CREATE CLUSTERED INDEX [IDX_APOLICE_MAPFRE_TEMP_ID]
    ON [dbo].[APOLICE_MAPFRE_TEMP]([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IDX_APOLICE_MAPFRE_TEMP_Apolice]
    ON [dbo].[APOLICE_MAPFRE_TEMP]([NumeroApolice] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

