CREATE TABLE [dbo].[BackUpRegistrosPremiacaoCNPJsVAzios_20150919] (
    [IDCorrespondenteErrado]    INT             NOT NULL,
    [CPFCNPJErrado]             VARCHAR (18)    NULL,
    [IDcorrespondenteCerto]     INT             NOT NULL,
    [Matricula]                 BIGINT          NOT NULL,
    [CPFCNPJ]                   VARCHAR (18)    NULL,
    [Nome]                      VARCHAR (140)   NULL,
    [IDTipoCorrespondente]      TINYINT         NULL,
    [IDUnidade]                 SMALLINT        NULL,
    [UF]                        CHAR (2)        NULL,
    [Cidade]                    VARCHAR (70)    NULL,
    [NomeArquivo]               VARCHAR (100)   NOT NULL,
    [DataArquivoCorrespondente] DATE            NULL,
    [MatriculaErrada]           BIGINT          NULL,
    [ORDEM]                     INT             NOT NULL,
    [ID]                        BIGINT          NOT NULL,
    [IDProdutor]                INT             NOT NULL,
    [IDOperacao]                TINYINT         NOT NULL,
    [IDCorrespondente]          INT             NOT NULL,
    [IDFilialFaturamento]       SMALLINT        NULL,
    [NumeroRecibo]              INT             NULL,
    [IDContrato]                BIGINT          NULL,
    [IDProposta]                BIGINT          NULL,
    [NumeroEndosso]             INT             NULL,
    [NumeroParcela]             SMALLINT        NULL,
    [NumeroBilhete]             VARCHAR (20)    NULL,
    [Grupo]                     INT             NULL,
    [Cota]                      INT             NULL,
    [ValorCorretagem]           DECIMAL (19, 2) NULL,
    [DataProcessamento]         DATE            NULL,
    [NumeroContrato]            VARCHAR (20)    NULL,
    [NumeroProposta]            VARCHAR (20)    NULL,
    [Arquivo]                   VARCHAR (80)    NOT NULL,
    [DataArquivo]               DATE            NOT NULL,
    [IDTipoProduto]             TINYINT         NOT NULL
);

