CREATE TABLE [dbo].[BASE_RISCOS_OUTUBRO] (
    [SUK_CONTRATO_VIDA]            INT             NOT NULL,
    [NUM_BIL_CERTIF]               DECIMAL (15)    NOT NULL,
    [NUM_APOLICE]                  DECIMAL (15)    NULL,
    [NUM_PROPOSTA_SIVPF]           DECIMAL (15)    NULL,
    [NUM_CONTRATO]                 DECIMAL (15)    NULL,
    [DTH_PROPOSTA]                 DATETIME        NULL,
    [DTH_VENDA]                    DATETIME        NULL,
    [DTH_QUITACAO]                 DATETIME        NULL,
    [DTH_EMISSAO]                  DATETIME        NULL,
    [DTH_CANCELAMENTO]             DATETIME        NULL,
    [DTH_INI_VIGENCIA]             DATETIME        NULL,
    [DTH_FIM_VIGENCIA]             DATETIME        NULL,
    [VLR_PREMIO_BRUTO_INICIAL]     DECIMAL (15, 2) NULL,
    [VLR_PREMIO_LIQ_INICIAL]       DECIMAL (15, 2) NULL,
    [VLR_PREMIO_BRUTO_ATUAL]       DECIMAL (15, 2) NULL,
    [VLR_PREMIO_LIQ_ATUAL]         DECIMAL (15, 2) NULL,
    [VLR_IOF]                      DECIMAL (8, 2)  NULL,
    [VLR_CUSTO_EMISSAO]            DECIMAL (8, 2)  NULL,
    [COD_SUBGRUPO]                 SMALLINT        NULL,
    [IND_PERI_PAGAMENTO]           SMALLINT        NULL,
    [COD_OPCAO_PAGAMENTO]          CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_MATRICULA_VENDEDOR]       DECIMAL (15)    NULL,
    [NUM_MATRICULA_ECONOM]         DECIMAL (15)    NULL,
    [NUM_MATRICULA_PDV]            VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_APOLICE_ANTERIOR]         DECIMAL (15)    NULL,
    [IND_RENOVACAO]                CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_ADIMPLENTE]               CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_QTD_PARCELAS]             SMALLINT        NULL,
    [IND_ORIGEM_REGISTRO_CONTRATO] CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [STA_ANTECIPACAO]              INT             NULL,
    [STA_MUDANCA_PLANO]            INT             NULL,
    [PCT_PART_CORRETOR]            DECIMAL (5, 2)  NULL,
    [PCT_COM_CORRETOR]             DECIMAL (5, 2)  NULL,
    [NOM_PRODUTOR]                 VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [COD_PRODUTO_SIAS]             SMALLINT        NULL,
    [COD_PRODUTO_SIVPF]            SMALLINT        NULL,
    [COD_RAMO_EMISSOR]             SMALLINT        NULL,
    [COD_EMPRESA_SIAS]             SMALLINT        NULL,
    [COD_CPF_CNPJ_VENDEDOR]        DECIMAL (16)    NULL,
    [COD_MATRICULA_VENDEDOR]       VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_ORIGEM_REGISTRO_VENDEDOR] CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_VENDEDOR]            CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IDSUBSITUACAO]                VARCHAR (11)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DATA_SITUACAO]                DATETIME        NULL,
    [DATA_ATUALIZACAO]             DATETIME        NULL,
    [QTD_CONTRATO]                 INT             NULL,
    [QTD_PROPOSTA]                 INT             NULL,
    [COD_AGENCIA]                  SMALLINT        NULL,
    [COD_CLIENTE_PE]               INT             NULL,
    [NUM_OCORR_ENDERECO_PE]        SMALLINT        NULL,
    [NOM_PESSOA_PE]                VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PE]              VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PE]            DATETIME        NULL,
    [COD_SEXO_PE]                  CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PE]          CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PE]          VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PE]           CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PE]                 VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PE]            VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PE]       VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PE]         CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PE]             DATETIME        NULL,
    [COD_DDD_TELEFONE_PE]          SMALLINT        NULL,
    [COD_TELEFONE_PE]              INT             NULL,
    [COD_DDD_CELULAR_PE]           SMALLINT        NULL,
    [COD_CELULAR_PE]               INT             NULL,
    [COD_CBO_PE]                   INT             NULL,
    [DES_ENDERECO_PE]              VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PE]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PE]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PE]                    CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PE]  VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PE]                SMALLINT        NULL,
    [COD_CEP_PE]                   VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PE]                 SMALLINT        NULL,
    [COD_AGENCIA_PE]               SMALLINT        NULL,
    [NUM_CONTA_PE]                 DECIMAL (15)    NULL,
    [NUM_DV_CONTA_PE]              SMALLINT        NULL,
    [NUM_OPERACAO_CONTA_PE]        SMALLINT        NULL,
    [COD_ORIGEM_PESSOA_PE]         SMALLINT        NULL,
    [COD_CLIENTE_PSE]              INT             NULL,
    [NUM_OCORR_ENDERECO_PSE]       SMALLINT        NULL,
    [NOM_PESSOA_PSE]               VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PSE]             VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PSE]           DATETIME        NULL,
    [COD_SEXO_PSE]                 CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PSE]         CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PSE]         VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PSE]          CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PSE]                VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PSE]           VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PSE]      VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PSE]        CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PSE]            DATETIME        NULL,
    [COD_DDD_TELEFONE_PSE]         SMALLINT        NULL,
    [COD_TELEFONE_PSE]             INT             NULL,
    [COD_DDD_CELULAR_PSE]          SMALLINT        NULL,
    [COD_CELULAR_PSE]              INT             NULL,
    [COD_CBO_PSE]                  INT             NULL,
    [DES_ENDERECO_PSE]             VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PSE]               VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PSE]               VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PSE]                   CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PSE] VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PSE]               SMALLINT        NULL,
    [COD_CEP_PSE]                  VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PSE]                SMALLINT        NULL,
    [COD_AGENCIA_PSE]              SMALLINT        NULL,
    [NUM_CONTA_PSE]                DECIMAL (15)    NULL,
    [NUM_DV_CONTA_PSE]             SMALLINT        NULL,
    [NUM_OPERACAO_CONTA_PSE]       SMALLINT        NULL,
    [COD_ORIGEM_PSESSOA_PSE]       SMALLINT        NULL,
    [COD_CLIENTE_PS]               INT             NULL,
    [NUM_OCORR_ENDERECO_PS]        SMALLINT        NULL,
    [NOM_PESSOA_PS]                VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PS]              VARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PS]            DATETIME        NULL,
    [COD_SEXO_PS]                  CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PS]          CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PS]          VARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PS]           CHAR (1)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PS]                 VARCHAR (200)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PS]            VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PS]       VARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PS]         CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PS]             DATETIME        NULL,
    [COD_DDD_TELEFONE_PS]          SMALLINT        NULL,
    [COD_TELEFONE_PS]              INT             NULL,
    [COD_DDD_CELULAR_PS]           SMALLINT        NULL,
    [COD_CELULAR_PS]               INT             NULL,
    [COD_CBO_PS]                   INT             NULL,
    [DES_ENDERECO_PS]              VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PS]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PS]                VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PS]                    CHAR (2)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PS]  VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PS]                SMALLINT        NULL,
    [COD_CEP_PS]                   VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PS]                 SMALLINT        NULL,
    [COD_AGENCIA_PS]               SMALLINT        NULL,
    [NUM_CONTA_PS]                 DECIMAL (15)    NULL,
    [NUM_DV_CONTA_PS]              SMALLINT        NULL,
    [NUM_OPERACAO_CONTA_PS]        SMALLINT        NULL,
    [COD_ORIGEM_PESSOA_PS]         SMALLINT        NULL,
    [NOM_PRODUTO_SIAS]             VARCHAR (100)   NULL,
    [NOM_PRODUTO_SIVPF]            VARCHAR (100)   NULL
);

