CREATE TABLE [dbo].[bkppremiacao201611101] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDFuncionario]            INT             NULL,
    [IDUnidade]                SMALLINT        NULL,
    [TipoPagamento]            CHAR (1)        NULL,
    [Banco]                    SMALLINT        NOT NULL,
    [Operacao]                 VARCHAR (10)    NOT NULL,
    [ContaCorrente]            VARCHAR (20)    NOT NULL,
    [ValorBruto]               DECIMAL (19, 2) NULL,
    [ValorISS]                 DECIMAL (19, 2) NOT NULL,
    [ValorIRF]                 DECIMAL (19, 2) NOT NULL,
    [ValorLiquido]             DECIMAL (19, 2) NOT NULL,
    [ValorINSS]                DECIMAL (19, 2) NOT NULL,
    [ValorINSSRecolhidoCEF]    DECIMAL (19, 2) NULL,
    [NomeArquivo]              VARCHAR (60)    NOT NULL,
    [DataArquivo]              DATE            NOT NULL,
    [NomeIndicador]            VARCHAR (200)   NULL,
    [CPF]                      VARCHAR (20)    NULL,
    [DataReferencia]           DATE            NULL,
    [Autorizado]               BIT             NULL,
    [CalculadoAliquotaISS]     DECIMAL (19, 2) NULL,
    [CalculadoValorISS]        DECIMAL (19, 2) NULL,
    [CalculadoAliquotaIRRF]    DECIMAL (19, 2) NULL,
    [CalculadoValorIRRF]       DECIMAL (19, 2) NULL,
    [CalculadoAliquotaINSS]    DECIMAL (19, 2) NULL,
    [CalculadoValorINSS]       DECIMAL (19, 2) NULL,
    [CalculadoTetoINSS]        DECIMAL (19, 2) NULL,
    [CodigoEmpresaProtheus]    VARCHAR (2)     NULL,
    [CodigoFilialProtheus]     VARCHAR (2)     NULL,
    [CodigoImportacaoPROTHEUS] VARCHAR (6)     NULL,
    [LoteImportacaoPROTHEUS]   VARCHAR (6)     NULL,
    [ItemImportacaoPROTHEUS]   VARCHAR (6)     NULL,
    [DataCalculo]              DATETIME2 (7)   NULL,
    [Cancelado]                BIT             NULL,
    [DataCompetencia]          DATE            NULL,
    [Gerente]                  BIT             NULL,
    [IDLote]                   INT             NULL,
    [AnoMesArquivo]            VARCHAR (12)    NULL
);

