CREATE TABLE [dbo].[cap04] (
    [EMPRESA]           VARCHAR (200) NULL,
    [CAMPANHA]          VARCHAR (200) NULL,
    [ORIGEM]            VARCHAR (200) NULL,
    [PARCEIRO]          VARCHAR (200) NULL,
    [NOME]              VARCHAR (200) NULL,
    [LOGIN]             VARCHAR (200) NULL,
    [CPF]               VARCHAR (200) NULL,
    [ID_PEDIDO]         VARCHAR (200) NULL,
    [DATA_PEDIDO]       VARCHAR (200) NULL,
    [ VALOR_RESGATADO ] VARCHAR (200) NULL,
    [ VALOR_ESTORNADO ] VARCHAR (200) NULL,
    [PRODUTO]           VARCHAR (200) NULL,
    [QTDE]              VARCHAR (200) NULL,
    [VALOR_PRODUTO]     VARCHAR (200) NULL,
    [VALOR_FRETE]       VARCHAR (200) NULL,
    [VALOR_TOTAL]       VARCHAR (200) NULL,
    [LOGRADOURO]        VARCHAR (200) NULL,
    [NUMERO]            VARCHAR (200) NULL,
    [COMPLEMENTO]       VARCHAR (200) NULL,
    [BAIRRO]            VARCHAR (200) NULL,
    [CIDADE]            VARCHAR (200) NULL,
    [ESTADO]            VARCHAR (200) NULL,
    [CEP]               VARCHAR (200) NULL,
    [DDD_TEL_RES]       VARCHAR (200) NULL,
    [TEL_RES]           VARCHAR (200) NULL,
    [STATUS_ENTREGA]    VARCHAR (200) NULL
);

