CREATE TABLE [dbo].[CertificadosContratoDELETADOS_MVSTA_Errados] (
    [ID]                                 BIGINT          NOT NULL,
    [IDContratoAnterior]                 BIGINT          NULL,
    [IDProposta]                         BIGINT          NULL,
    [IDSeguradora]                       SMALLINT        NOT NULL,
    [IDRamo]                             SMALLINT        NULL,
    [NumeroContrato]                     VARCHAR (20)    NOT NULL,
    [CodigoFonteProdutora]               SMALLINT        NULL,
    [NumeroBilhete]                      VARCHAR (20)    NULL,
    [NumeroSICOB]                        VARCHAR (9)     NULL,
    [DataEmissao]                        DATE            NULL,
    [DataInicioVigencia]                 DATE            NULL,
    [DataFimVigencia]                    DATE            NULL,
    [ValorPremioLiquido]                 DECIMAL (19, 2) NULL,
    [ValorPremioTotal]                   DECIMAL (19, 2) NULL,
    [DataInicioVigenciaAtual]            DATE            NULL,
    [ValorPremioTotalAtual]              DECIMAL (19, 2) NULL,
    [IDSituacaEndosso]                   TINYINT         NULL,
    [QuantidadeParcelas]                 TINYINT         NULL,
    [IDAgencia]                          SMALLINT        NULL,
    [IDIndicador]                        INT             NULL,
    [IDIndicadorGerente]                 INT             NULL,
    [IDIndicadorSuperintendenteRegional] INT             NULL,
    [CodigoMoedaSegurada]                SMALLINT        NULL,
    [CodigoMoedaPremio]                  SMALLINT        NULL,
    [LayoutRisco]                        VARCHAR (10)    NULL,
    [DataArquivo]                        DATE            NOT NULL,
    [Arquivo]                            VARCHAR (80)    NOT NULL
);

