CREATE TABLE [dbo].[Cliente_Cliente_Tipo1] (
    [NUMERO_GRUPO]            INT           NULL,
    [NUMERO_COTA]             INT           NULL,
    [NUMERO_VERSAO]           INT           NULL,
    [BRANCOS]                 VARCHAR (20)  NULL,
    [CPFCNPJ]                 VARCHAR (20)  NULL,
    [DataNascimento]          DATE          NULL,
    [NOME]                    VARCHAR (50)  NULL,
    [TipoPessoa]              CHAR (2)      NULL,
    [IDENTIDADE]              VARCHAR (20)  NULL,
    [ORGAO_EXPEDIDOR]         VARCHAR (10)  NULL,
    [UF_ORGAO_EXPEDIDOR]      VARCHAR (2)   NULL,
    [ESTADO_CIVIL]            TINYINT       NULL,
    [SEXO]                    TINYINT       NULL,
    [PROFISSAO]               INT           NULL,
    [DDD_RESIDENCIA]          CHAR (3)      NULL,
    [TELEFONE_RESIDENCIA]     VARCHAR (10)  NULL,
    [DDD_COMERCIAL]           CHAR (3)      NULL,
    [TELEFONE_COMERCIAL]      VARCHAR (10)  NULL,
    [DDD_FAX]                 CHAR (3)      NULL,
    [TELEFONE_FAX]            VARCHAR (10)  NULL,
    [DATA_EXPEDICAO_RG]       DATE          NULL,
    [CODIGO_SEGMENTO]         CHAR (4)      NULL,
    [NOME_CONJUGE]            VARCHAR (50)  NULL,
    [DATA_NASCIMENTO_CONJUGE] DATE          NULL,
    [PROFISSAO_CONJUGE]       INT           NULL,
    [EMAIL]                   VARCHAR (100) NULL,
    [DESCRICAO_DE_PROFISSAO]  VARCHAR (50)  NULL,
    [RENDA_INDIVIDUAL]        TINYINT       NULL,
    [RENDA_FAMILIAR]          TINYINT       NULL,
    [BRANCOS_B]               VARCHAR (50)  NULL,
    [Codigo]                  INT           NULL,
    [NomeArquivo]             VARCHAR (200) NULL,
    [Chave]                   VARCHAR (90)  NULL,
    [DataArquivo]             DATE          NULL,
    [NumeroProposta]          VARCHAR (24)  NULL
);

