CREATE TABLE [dbo].[ComissaoProtheus_TEMP] (
    [ID]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDRamo]                 INT             NULL,
    [ValorCorretagem]        DECIMAL (38, 6) NULL,
    [PercentualCorretagem]   DECIMAL (5, 2)  NULL,
    [ValorBase]              DECIMAL (38, 6) NULL,
    [ValorComissaoPAR]       DECIMAL (38, 6) NULL,
    [ValorRepasse]           DECIMAL (38, 6) NULL,
    [DataCompetencia]        VARCHAR (10)    NULL,
    [DataRecibo]             DATE            NULL,
    [NumeroRecibo]           INT             NULL,
    [NumeroEndosso]          INT             NULL,
    [NumeroParcela]          INT             NULL,
    [DataCalculo]            DATE            NULL,
    [DataQuitacaoParcela]    DATE            NULL,
    [TipoCorretagem]         INT             NULL,
    [IDOperacao]             INT             NULL,
    [IDProdutor]             INT             NULL,
    [IDFilialFaturamento]    INT             NULL,
    [CodigoSubgrupoRamoVida] INT             NULL,
    [IDProduto]              INT             NULL,
    [IDUnidadeVenda]         SMALLINT        NULL,
    [IDProposta]             BIGINT          NULL,
    [IDCanalVendaPAR]        INT             NULL,
    [NumeroProposta]         VARCHAR (20)    NULL,
    [CodigoProduto]          VARCHAR (5)     NULL,
    [LancamentoManual]       BIT             NULL,
    [Repasse]                BIT             NULL,
    [Arquivo]                VARCHAR (80)    NULL,
    [DataArquivo]            DATE            NULL,
    [Operadora]              VARCHAR (4)     NOT NULL,
    [Empresa]                VARCHAR (2)     NOT NULL,
    [Segmento]               VARCHAR (2)     NOT NULL,
    [NomeContrato]           VARCHAR (70)    NULL,
    [IDEmpresa]              INT             NOT NULL,
    [DescricaoCanalVenda]    VARCHAR (100)   NOT NULL,
    [IDSeguradora]           INT             NULL,
    [QtApolices]             INT             NULL,
    CONSTRAINT [PK_Comissao_TEMP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);

