CREATE TABLE [dbo].[ComissaoApoliceCertificadoProduto2013] (
    [COD_PRODUTO]     VARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
    [NUM_APOLICE]     VARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
    [NUM_CERTIFICADO] VARCHAR (20) NULL
);


GO
CREATE NONCLUSTERED INDEX [IDXCERTI]
    ON [dbo].[ComissaoApoliceCertificadoProduto2013]([NUM_CERTIFICADO] ASC)
    INCLUDE([NUM_APOLICE], [COD_PRODUTO]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

