CREATE TABLE [dbo].[CONTRATOSDISTINTOSMRCAROL] (
    [NumeroContrato] VARCHAR (24) NOT NULL
);


GO
CREATE CLUSTERED INDEX [cl_idx_NumeroContrato]
    ON [dbo].[CONTRATOSDISTINTOSMRCAROL]([NumeroContrato] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

