CREATE TABLE [dbo].[CONTRATOSDISTINTOSMRDANIEL] (
    [NumeroContrato] VARCHAR (24) NOT NULL
);


GO
CREATE CLUSTERED INDEX [CL_IX_CONTRATOS_DANIEL]
    ON [dbo].[CONTRATOSDISTINTOSMRDANIEL]([NumeroContrato] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

