CREATE TABLE [dbo].[D160201.AU1406B] (
    [PRODUTO]          VARCHAR (50) NULL,
    [NR-CONTRATO-SEG]  VARCHAR (50) NULL,
    [NR-ENDOSSO]       VARCHAR (50) NULL,
    [SEQUENCIA]        VARCHAR (50) NULL,
    [DT-ULT-MOV]       VARCHAR (50) NULL,
    [DT-ADESAO]        VARCHAR (50) NULL,
    [NR-CONTRATO-APOL] VARCHAR (50) NULL,
    [PREMIO-TARIF]     VARCHAR (50) NULL,
    [VLOR-IOF]         VARCHAR (50) NULL
);

