CREATE TABLE [dbo].[DC_PRODUTORES] (
    [COD_PRODUTOR]     VARCHAR (100) NULL,
    [NOME_PRODUTOR]    VARCHAR (100) NULL,
    [COD_HIERARQUIA]   VARCHAR (100) NULL,
    [CIDADE]           VARCHAR (100) NULL,
    [SIGLA_UF]         VARCHAR (50)  NULL,
    [CGCCPF]           VARCHAR (50)  NULL,
    [TAB_COMISSIONADO] VARCHAR (100) NULL
);

