CREATE TABLE [dbo].[DE_PARA_PRODUTOS_AIC_ONLINE] (
    [PRODUTO]         NVARCHAR (255) NULL,
    [TIPO_PAGAMENTO]  NVARCHAR (255) NULL,
    [DES_TIPO_PESSOA] FLOAT (53)     NULL,
    [DE_PARA]         VARCHAR (50)   NULL,
    [DE_PARA_AIC]     VARCHAR (30)   NULL
);

