CREATE TABLE [dbo].[Destination - D170908 LT3179B S1805S1] (
    [PROD]                                                         VARCHAR (200) NULL,
    [CODIGO   ]                                                    VARCHAR (200) NULL,
    [UF  ]                                                         VARCHAR (200) NULL,
    [REG ]                                                         VARCHAR (200) NULL,
    [APOLICE      ]                                                VARCHAR (200) NULL,
    [CLASSE ANT]                                                   VARCHAR (200) NULL,
    [CLASSE GER]                                                   VARCHAR (200) NULL,
    [CLASSE ATU]                                                   VARCHAR (200) NULL,
    [QTDSIN]                                                       VARCHAR (200) NULL,
    [TOTAL INDENIZ]                                                VARCHAR (200) NULL,
    [VL PREMIO PAG]                                                VARCHAR (200) NULL,
    [% SINISTRO    ]                                               VARCHAR (200) NULL,
    [SITUACAO    ]                                                 VARCHAR (200) NULL,
    [RAZAO SOCIAL                            ]                     VARCHAR (200) NULL,
    [DTINIVIG  ]                                                   VARCHAR (200) NULL,
    [DTTERVIG  ]                                                   VARCHAR (200) NULL,
    [  PRMTOTAL]                                                   VARCHAR (200) NULL,
    [ PARCELA-1]                                                   VARCHAR (200) NULL,
    [ PARCELA-N]                                                   VARCHAR (200) NULL,
    [QTDPCL]                                                       VARCHAR (200) NULL,
    [D FID ]                                                       VARCHAR (200) NULL,
    [D EXP ]                                                       VARCHAR (200) NULL,
    [D COB ]                                                       VARCHAR (200) NULL,
    [D COF ]                                                       VARCHAR (200) NULL,
    [D BLI ]                                                       VARCHAR (200) NULL,
    [TRVAL ]                                                       VARCHAR (200) NULL,
    [IS -INC,RAIO EXP  ]                                           VARCHAR (200) NULL,
    [IS -IMPSEG ANTIGA ]                                           VARCHAR (200) NULL,
    [IS -DAN ELET      ]                                           VARCHAR (200) NULL,
    [IS -IMPSEG ANTIGA 2]                                          VARCHAR (200) NULL,
    [IS -IMPSEG ANTIGA 3]                                          VARCHAR (200) NULL,
    [IS -RC-OPERACOES  ]                                           VARCHAR (200) NULL,
    [IS -ROUBO INT ESTB]                                           VARCHAR (200) NULL,
    [IS -ROUBO MAO PORT]                                           VARCHAR (200) NULL,
    [IS -ROUBO MAQ MOV ]                                           VARCHAR (200) NULL,
    [IS -VENDAVAL      ]                                           VARCHAR (200) NULL,
    [IS -DIAS PARALIS  ]                                           VARCHAR (200) NULL,
    [IS -PERDA PAG ALUG]                                           VARCHAR (200) NULL,
    [IS -TUMULTOS      ]                                           VARCHAR (200) NULL,
    [IS -QUEBRA VIDROS ]                                           VARCHAR (200) NULL,
    [IS -DERRAME SPRINK]                                           VARCHAR (200) NULL,
    [IS -RC-GUARDA VEIC]                                           VARCHAR (200) NULL,
    [IS -EQ MOV EST-TFL]                                           VARCHAR (200) NULL,
    [IS -EQ MOV EST-COF]                                           VARCHAR (200) NULL,
    [IS -EQ MOV EST-DEM]                                           VARCHAR (200) NULL,
    [IS -IMPSEG ANTIGA 4]                                          VARCHAR (200) NULL,
    [TX -INC,RAIO EXP  ]                                           VARCHAR (200) NULL,
    [TX -TAXA  ANTIGA  ]                                           VARCHAR (200) NULL,
    [TX -DAN ELET      ]                                           VARCHAR (200) NULL,
    [TX -TAXA  ANTIGA  2]                                          VARCHAR (200) NULL,
    [TX -TAXA  ANTIGA  3]                                          VARCHAR (200) NULL,
    [TX -RC-OPERACOES  ]                                           VARCHAR (200) NULL,
    [TX -ROUBO INT ESTB]                                           VARCHAR (200) NULL,
    [TX -ROUBO MAO PORT]                                           VARCHAR (200) NULL,
    [TX -ROUBO MAQ MOV ]                                           VARCHAR (200) NULL,
    [TX -VENDAVAL      ]                                           VARCHAR (200) NULL,
    [TX -DIAS PARALIS  ]                                           VARCHAR (200) NULL,
    [TX -PERDA PAG ALUG]                                           VARCHAR (200) NULL,
    [TX -TUMULTOS      ]                                           VARCHAR (200) NULL,
    [TX -QUEBRA VIDROS ]                                           VARCHAR (200) NULL,
    [TX -DERRAME SPRINK]                                           VARCHAR (200) NULL,
    [TX -RC-GUARDA VEIC]                                           VARCHAR (200) NULL,
    [TX -EQ MOV EST-TFL]                                           VARCHAR (200) NULL,
    [TX -EQ MOV EST-COF]                                           VARCHAR (200) NULL,
    [TX -EQ MOV EST-DEM]                                           VARCHAR (200) NULL,
    [TX -TAXA  ANTIGA  4]                                          VARCHAR (200) NULL,
    [PR -INC,RAIO EXP  ]                                           VARCHAR (200) NULL,
    [PR -PREMIO ANTIGO ]                                           VARCHAR (200) NULL,
    [PR -DAN ELET      ]                                           VARCHAR (200) NULL,
    [PR -PREMIO ANTIGO 2]                                          VARCHAR (200) NULL,
    [PR -PREMIO ANTIGO 3]                                          VARCHAR (200) NULL,
    [PR -RC-OPERACOES  ]                                           VARCHAR (200) NULL,
    [PR -ROUBO INT ESTB]                                           VARCHAR (200) NULL,
    [PR -ROUBO MAO PORT]                                           VARCHAR (200) NULL,
    [PR -ROUBO MAQ MOV ]                                           VARCHAR (200) NULL,
    [PR -VENDAVAL      ]                                           VARCHAR (200) NULL,
    [PR -DIAS PARALIS  ]                                           VARCHAR (200) NULL,
    [PR -PERDA PAG ALUG]                                           VARCHAR (200) NULL,
    [PR -TUMULTOS      ]                                           VARCHAR (200) NULL,
    [PR -QUEBRA VIDROS ]                                           VARCHAR (200) NULL,
    [PR -DERRAME SPRINK]                                           VARCHAR (200) NULL,
    [PR -RC-GUARDA VEIC]                                           VARCHAR (200) NULL,
    [PR -EQ MOV EST-TFL]                                           VARCHAR (200) NULL,
    [PR -EQ MOV EST-COF]                                           VARCHAR (200) NULL,
    [PR -EQ MOV EST-DEM]                                           VARCHAR (200) NULL,
    [PR -PREMIO ANTIGO 4]                                          VARCHAR (200) NULL,
    [ENDERECO                                                    ] VARCHAR (200) NULL,
    [BAIRRO                        ]                               VARCHAR (200) NULL,
    [CIDADE                        ]                               VARCHAR (200) NULL,
    [CEP      ]                                                    VARCHAR (200) NULL,
    [EMAIL                                                       ] VARCHAR (200) NULL,
    [DDD ]                                                         VARCHAR (200) NULL,
    [TELEFONE  ]                                                   VARCHAR (200) NULL,
    [TIPO    ]                                                     VARCHAR (200) NULL,
    [VL PREMIO 2013]                                               VARCHAR (200) NULL,
    [VL PREMIO 2014]                                               VARCHAR (200) NULL,
    [VL PREMIO 2015]                                               VARCHAR (200) NULL,
    [VL PREMIO 2016]                                               VARCHAR (200) NULL,
    [VL PREMIO 2017]                                               VARCHAR (200) NULL,
    [VL SINISTRO 2013]                                             VARCHAR (200) NULL,
    [VL SINISTRO 2014]                                             VARCHAR (200) NULL,
    [VL SINISTRO 2015]                                             VARCHAR (200) NULL,
    [VL SINISTRO 2016]                                             VARCHAR (200) NULL,
    [VL SINISTRO 2017]                                             VARCHAR (200) NULL,
    [a]                                                            VARCHAR (200) NULL,
    [UF2]                                                          VARCHAR (200) NULL,
    [UF3]                                                          VARCHAR (200) NULL
);

