CREATE TABLE [dbo].[EmissaoAuto_COL_TEMP] (
    [CODIGOSEGURADORA]          SMALLINT        NULL,
    [CODIGOPRODUTO]             SMALLINT        NULL,
    [NOMEPRODUTO]               VARCHAR (50)    NULL,
    [NUMEROAPOLICE]             VARCHAR (20)    NULL,
    [NUMEROPROPOSTA]            VARCHAR (20)    NULL,
    [NUMEROENDOSSO]             VARCHAR (20)    NULL,
    [APOLICEANTERIOR]           VARCHAR (20)    NULL,
    [SITUACAOENDOSSO]           SMALLINT        NULL,
    [DATAINICIOVIGENCIAENDOSSO] DATE            NULL,
    [DATAFIMVIGENCIAENDOSSO]    DATE            NULL,
    [DATAEMISSAO]               DATE            NULL,
    [DATAVENDA]                 DATE            NULL,
    [DATAPROPOSTA]              DATE            NULL,
    [DATASITUACAO]              DATE            NULL,
    [DIAVENCIMENTO]             SMALLINT        NULL,
    [CODIGOCOBERTURA]           SMALLINT        NULL,
    [NOMECOBERTURA]             VARCHAR (50)    NULL,
    [VALORPREMIOLIQUIDO]        DECIMAL (19, 2) NULL,
    [VALORPREMIOBRUTO]          DECIMAL (19, 2) NULL,
    [VALORIOF]                  DECIMAL (19, 2) NULL,
    [PERIDICIDADEPAGAMENTO]     VARCHAR (10)    NULL,
    [SITUACAOPAGAMENTO]         VARCHAR (10)    NULL,
    [SITUACAOPROPOSTA]          SMALLINT        NULL,
    [SITUACAOCOBRANCA]          VARCHAR (10)    NULL,
    [MOTIVODASITUACAO]          VARCHAR (50)    NULL,
    [TIPOSEGURO]                SMALLINT        NULL,
    [QUANTIDADEPARCELAS]        SMALLINT        NULL,
    [VALORPRIMEIRAPARCELA]      DECIMAL (19, 2) NULL,
    [VALORDEMAISPARCELAS]       DECIMAL (19, 2) NULL
);

