CREATE TABLE [dbo].[emissao_1804] (
    [LIVRO]              FLOAT (53)     NULL,
    [PAGINA]             FLOAT (53)     NULL,
    [ORGAO]              NVARCHAR (255) NULL,
    [COD_RAMO]           FLOAT (53)     NULL,
    [RAMO]               NVARCHAR (255) NULL,
    [MES_DE_COMPETENCIA] FLOAT (53)     NULL,
    [PRODUTO]            FLOAT (53)     NULL,
    [UF]                 NVARCHAR (255) NULL,
    [APOLICE]            FLOAT (53)     NULL,
    [ENDOSSO]            FLOAT (53)     NULL,
    [CERTIFICADO]        FLOAT (53)     NULL,
    [PARCELA]            FLOAT (53)     NULL,
    [MOEDA]              NVARCHAR (255) NULL,
    [DT_EMISSAO]         FLOAT (53)     NULL,
    [DT_INICIO]          FLOAT (53)     NULL,
    [DT_TERMINO]         FLOAT (53)     NULL,
    [CPFCNPJ]            NVARCHAR (255) NULL,
    [SEGURADO]           NVARCHAR (255) NULL,
    [COD_SUSEP]          FLOAT (53)     NULL,
    [CORRETOR]           NVARCHAR (255) NULL,
    [LIDER_IMP_SEGURADA] FLOAT (53)     NULL,
    [COSS_IMP_SEGURADA]  FLOAT (53)     NULL,
    [RESS_IMP_SEGURADA]  FLOAT (53)     NULL,
    [LIDER_PREMIO TARIF] FLOAT (53)     NULL,
    [COSS_PREMIO TARIF]  FLOAT (53)     NULL,
    [RESS_PREMIO TARIF]  FLOAT (53)     NULL,
    [LIDER_DESCONTO]     FLOAT (53)     NULL,
    [COSS_DESCONTO]      FLOAT (53)     NULL,
    [LIDER_ADICIONAL]    FLOAT (53)     NULL,
    [COSS_ADICIONAL]     FLOAT (53)     NULL,
    [LIDER_CUSTO]        FLOAT (53)     NULL,
    [LIDER_IOF]          FLOAT (53)     NULL,
    [LIDER_COMISSAO]     FLOAT (53)     NULL,
    [COSS_COMISSAO]      FLOAT (53)     NULL,
    [RESS_COMISSAO]      FLOAT (53)     NULL,
    [LIDER_PREMIO TOTAL] FLOAT (53)     NULL,
    [COSS_PREMIO TOTAL]  FLOAT (53)     NULL,
    [RESS_PREMIO TOTAL]  FLOAT (53)     NULL,
    [REEMISSÃO]          NVARCHAR (255) NULL,
    [PropostaTratada]    VARCHAR (20)   NULL
);

