CREATE TABLE [dbo].[Financeiro_EF0310B_Premios] (
    [NumeroProduto]            VARCHAR (4)     NULL,
    [TipoCredito]              CHAR (2)        NULL,
    [NumeroContrato]           VARCHAR (20)    NULL,
    [CodigoESCNEG]             VARCHAR (10)    NULL,
    [CodigoUnoPv]              VARCHAR (50)    NULL,
    [CodigoUnoNum]             VARCHAR (10)    NULL,
    [CodigoUnoDv]              CHAR (1)        NULL,
    [NomeSegurado]             VARCHAR (60)    NULL,
    [CPFCNPJ]                  VARCHAR (15)    NULL,
    [DataContrato]             DATE            NULL,
    [DataInclusao]             DATE            NULL,
    [DataAmortizacao]          DATE            NULL,
    [PrazoVigencia]            VARCHAR (5)     NULL,
    [NumeroOrdemInclusao]      VARCHAR (10)    NULL,
    [NumeroRI]                 VARCHAR (5)     NULL,
    [IdentificacaoISMip]       CHAR (1)        NULL,
    [ISMip]                    DECIMAL (12, 2) NULL,
    [PremioMip]                DECIMAL (12, 2) NULL,
    [IOFMip]                   DECIMAL (9, 2)  NULL,
    [PremioMipAtrasado]        DECIMAL (12, 2) NULL,
    [IOFMipAtrasado]           DECIMAL (9, 2)  NULL,
    [IdentificacaoISDfi]       CHAR (1)        NULL,
    [ISDfi]                    DECIMAL (12, 2) NULL,
    [PremioDfi]                DECIMAL (12, 2) NULL,
    [IOFDfi]                   DECIMAL (9, 2)  NULL,
    [PremioDfiAtrasado]        DECIMAL (12, 2) NULL,
    [IOFDfiAtrasado]           DECIMAL (9, 2)  NULL,
    [IdentificacaoISInad]      CHAR (1)        NULL,
    [ISInad]                   DECIMAL (12, 2) NULL,
    [PremioInad]               DECIMAL (12, 2) NULL,
    [IOFInad]                  DECIMAL (9, 2)  NULL,
    [PremioInadAtrasado]       DECIMAL (12, 2) NULL,
    [IOFInadAtrasado]          DECIMAL (9, 2)  NULL,
    [PercentualResseguro]      DECIMAL (5, 2)  NULL,
    [ValorIsRessMip]           DECIMAL (12, 2) NULL,
    [ValorPrRessMipMes]        DECIMAL (9, 2)  NULL,
    [ValorPrRessMipAtrasado]   DECIMAL (9, 2)  NULL,
    [ValorIsRessDfi]           DECIMAL (12, 2) NULL,
    [ValorPrRessDfiMes]        DECIMAL (9, 2)  NULL,
    [ValorPrRessDfiAtrasado]   DECIMAL (9, 2)  NULL,
    [PercentualComissaoVenda]  DECIMAL (5, 2)  NULL,
    [ValorComissaoVenda]       DECIMAL (9, 2)  NULL,
    [PercentualRemuneracao]    DECIMAL (5, 2)  NULL,
    [ValorRemuneracaoMes]      DECIMAL (9, 2)  NULL,
    [ValorRemuneracaoAtrasado] DECIMAL (9, 2)  NULL,
    [PercentualComissaoFENAE]  DECIMAL (5, 2)  NULL,
    [ValorComissaoFENAE]       DECIMAL (9, 2)  NULL,
    [Logradouro]               VARCHAR (40)    NULL,
    [Numero]                   VARCHAR (5)     NULL,
    [Complemento]              VARCHAR (25)    NULL,
    [Bairro]                   VARCHAR (20)    NULL,
    [RendaPactuada]            DECIMAL (5, 2)  NULL,
    [TaxaJuros]                DECIMAL (5, 2)  NULL,
    [DataNascimento]           DATE            NULL,
    [Cidade]                   VARCHAR (25)    NULL,
    [UF]                       CHAR (2)        NULL,
    [CEP]                      VARCHAR (10)    NULL,
    [ValorFinanciamento]       DECIMAL (12, 2) NULL,
    [GrauHipot]                CHAR (1)        NULL,
    [PlanoReaj]                VARCHAR (10)    NULL,
    [CodigoEsp]                VARCHAR (5)     NULL,
    [CES]                      DECIMAL (7, 3)  NULL,
    [CodigoSubestipulante]     VARCHAR (10)    NULL,
    [DataArquivo]              DATE            NULL,
    [NomeArquivo]              VARCHAR (300)   NOT NULL,
    [DataHoraProcessamento]    DATETIME2 (7)   NOT NULL,
    [Codigo]                   BIGINT          NOT NULL,
    [IDProposta]               BIGINT          NULL,
    [NumeroContratoVar]        VARCHAR (30)    NULL
);


GO
CREATE NONCLUSTERED INDEX [nclidx_Financeiro_EF0310B_Premios]
    ON [dbo].[Financeiro_EF0310B_Premios]([NumeroContratoVar] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

