CREATE TABLE [dbo].[fp] (
    [NumeroProduto]            VARCHAR (4)     NULL,
    [TipoCredito]              CHAR (2)        NULL,
    [NumeroContrato]           VARCHAR (20)    NULL,
    [CodigoESCNEG]             VARCHAR (10)    NULL,
    [CodigoUnoPv]              VARCHAR (50)    NULL,
    [CodigoUnoNum]             VARCHAR (10)    NULL,
    [CodigoUnoDv]              CHAR (1)        NULL,
    [NomeSegurado]             VARCHAR (60)    NULL,
    [CPFCNPJ]                  VARCHAR (15)    NULL,
    [DataContrato]             DATE            NULL,
    [DataInclusao]             DATE            NULL,
    [DataAmortizacao]          DATE            NULL,
    [PrazoVigencia]            VARCHAR (5)     NULL,
    [NumeroOrdemInclusao]      VARCHAR (10)    NULL,
    [NumeroRI]                 VARCHAR (5)     NULL,
    [IdentificacaoISMip]       CHAR (1)        NULL,
    [ISMip]                    NUMERIC (12, 2) NULL,
    [PremioMip]                NUMERIC (12, 2) NULL,
    [IOFMip]                   NUMERIC (9, 2)  NULL,
    [PremioMipAtrasado]        NUMERIC (12, 2) NULL,
    [IOFMipAtrasado]           NUMERIC (9, 2)  NULL,
    [IdentificacaoISDfi]       CHAR (1)        NULL,
    [ISDfi]                    NUMERIC (12, 2) NULL,
    [PremioDfi]                NUMERIC (12, 2) NULL,
    [IOFDfi]                   NUMERIC (9, 2)  NULL,
    [PremioDfiAtrasado]        NUMERIC (12, 2) NULL,
    [IOFDfiAtrasado]           NUMERIC (9, 2)  NULL,
    [IdentificacaoISInad]      CHAR (1)        NULL,
    [ISInad]                   NUMERIC (12, 2) NULL,
    [PremioInad]               NUMERIC (12, 2) NULL,
    [IOFInad]                  NUMERIC (9, 2)  NULL,
    [PremioInadAtrasado]       NUMERIC (12, 2) NULL,
    [IOFInadAtrasado]          NUMERIC (9, 2)  NULL,
    [PercentualResseguro]      NUMERIC (5, 2)  NULL,
    [ValorIsRessMip]           NUMERIC (12, 2) NULL,
    [ValorPrRessMipMes]        NUMERIC (9, 2)  NULL,
    [ValorPrRessMipAtrasado]   NUMERIC (9, 2)  NULL,
    [ValorIsRessDfi]           NUMERIC (12, 2) NULL,
    [ValorPrRessDfiMes]        NUMERIC (9, 2)  NULL,
    [ValorPrRessDfiAtrasado]   NUMERIC (9, 2)  NULL,
    [PercentualComissaoVenda]  NUMERIC (5, 2)  NULL,
    [ValorComissaoVenda]       NUMERIC (9, 2)  NULL,
    [PercentualRemuneracao]    NUMERIC (5, 2)  NULL,
    [ValorRemuneracaoMes]      NUMERIC (9, 2)  NULL,
    [ValorRemuneracaoAtrasado] NUMERIC (9, 2)  NULL,
    [PercentualComissaoFENAE]  NUMERIC (5, 2)  NULL,
    [ValorComissaoFENAE]       NUMERIC (9, 2)  NULL,
    [Logradouro]               VARCHAR (40)    NULL,
    [Numero]                   VARCHAR (5)     NULL,
    [Complemento]              VARCHAR (25)    NULL,
    [Bairro]                   VARCHAR (20)    NULL,
    [RendaPactuada]            NUMERIC (5, 2)  NULL,
    [TaxaJuros]                NUMERIC (5, 2)  NULL,
    [DataNascimento]           DATE            NULL,
    [Cidade]                   VARCHAR (25)    NULL,
    [UF]                       CHAR (2)        NULL,
    [CEP]                      VARCHAR (10)    NULL,
    [ValorFinanciamento]       NUMERIC (12, 2) NULL,
    [GrauHipot]                CHAR (1)        NULL,
    [PlanoReaj]                VARCHAR (10)    NULL,
    [CodigoEsp]                VARCHAR (5)     NULL,
    [CES]                      NUMERIC (7, 3)  NULL,
    [CodigoSubestipulante]     VARCHAR (10)    NULL,
    [DataArquivo]              DATE            NULL,
    [NomeArquivo]              VARCHAR (300)   NOT NULL,
    [DataHoraProcessamento]    DATETIME2 (7)   NOT NULL,
    [Codigo]                   BIGINT          NOT NULL
);

