CREATE TABLE [dbo].[HML_vw_RegistroSinistro] (
    [CPF]                       VARCHAR (18)    NULL,
    [NC]                        VARCHAR (140)   NULL,
    [NumeroSinistro]            BIGINT          NULL,
    [DataAviso]                 DATE            NULL,
    [DataSinistro]              DATE            NULL,
    [NumeroProtocolo]           INT             NULL,
    [NumeroContrato]            VARCHAR (24)    NULL,
    [NumeroCertificado]         VARCHAR (20)    NOT NULL,
    [NumeroContratoResidencial] VARCHAR (30)    NULL,
    [DataInicioVigencia]        DATE            NULL,
    [DataFimVigencia]           DATE            NULL,
    [CodigoComercializado]      VARCHAR (5)     NOT NULL,
    [Descricao]                 VARCHAR (100)   NULL,
    [CodigoCobertura]           SMALLINT        NULL,
    [Cobertura]                 VARCHAR (70)    NULL,
    [ValorOperacao]             DECIMAL (19, 2) NULL,
    [DataMovimentoContabil]     DATE            NULL,
    [NomeBeneficiario]          VARCHAR (140)   NULL,
    [Operacao]                  VARCHAR (70)    NULL,
    [Causa]                     VARCHAR (40)    NULL,
    [Situacao]                  VARCHAR (20)    NULL,
    [Bairro]                    VARCHAR (80)    NULL,
    [Endereco]                  VARCHAR (150)   NULL,
    [Cidade]                    VARCHAR (80)    NULL,
    [UF]                        CHAR (2)        NULL,
    [CEP]                       VARCHAR (9)     NULL
);

