CREATE TABLE [dbo].[MailingKPN_TMP_2] (
    [CPFCNPJ]            VARCHAR (19)   NULL,
    [NomeCliente]        VARCHAR (150)  NULL,
    [CodigoBloco]        VARCHAR (2)    NULL,
    [NomeBloco]          VARCHAR (100)  NULL,
    [CodCampanha]        VARCHAR (50)   NULL,
    [NomeCampanha]       VARCHAR (50)   NOT NULL,
    [CodMailing]         VARCHAR (58)   NULL,
    [IDTipoCliente]      TINYINT        NULL,
    [ProdutoOferta]      VARCHAR (50)   NULL,
    [Telefone]           VARCHAR (20)   NULL,
    [OrdemTelefone]      INT            NOT NULL,
    [CPFCNPJ_NOFORMAT]   VARCHAR (8000) NULL,
    [Email]              VARCHAR (70)   NULL,
    [DataNascimento]     DATE           NULL,
    [IDIndicador]        INT            NULL,
    [IDAgenciaIndicacao] SMALLINT       NULL,
    [IDAgenciaCliente]   SMALLINT       NULL,
    [DataCalculo]        DATE           NULL,
    [IDVeiculo]          INT            NULL,
    [LINHATE]            BIGINT         NULL,
    [LINHAPRODUTO]       BIGINT         NULL,
    [Produto]            VARCHAR (100)  NULL,
    [Economiario]        BIT            NULL
);

