CREATE TABLE [dbo].[MarcosRibeiro] (
    [COD-FILIAL]                      FLOAT (53)     NULL,
    [Código BU]                       FLOAT (53)     NULL,
    [Código do produtor]              FLOAT (53)     NULL,
    [Numero apólice]                  FLOAT (53)     NULL,
    [Número Cerificado]               FLOAT (53)     NULL,
    [Número da parcela]               FLOAT (53)     NULL,
    [Número do bilhete]               FLOAT (53)     NULL,
    [Número do Endosso]               FLOAT (53)     NULL,
    [Ocorrencia do Histórico]         FLOAT (53)     NULL,
    [Tipo da Corretagem]              FLOAT (53)     NULL,
    [Código da operação]              FLOAT (53)     NULL,
    [Código do Ramo Fracionado]       FLOAT (53)     NULL,
    [ Valor Base ]                    FLOAT (53)     NULL,
    [ Percentual de Corretagem ]      FLOAT (53)     NULL,
    [ Valor da corretagem ]           FLOAT (53)     NULL,
    [Data do processamento]           DATETIME       NULL,
    [ro do recib]                     FLOAT (53)     NULL,
    [Código da filial]                FLOAT (53)     NULL,
    [Código do Subgrupo]              FLOAT (53)     NULL,
    [Código do Produto]               FLOAT (53)     NULL,
    [Código do Ponto de Venda]        FLOAT (53)     NULL,
    [Código do CEP do Ponto de Venda] FLOAT (53)     NULL,
    [Data do Calculo]                 DATETIME       NULL,
    [Data da quitação da Parcela]     DATETIME       NULL,
    [Número da proposta]              FLOAT (53)     NULL,
    [Nome do Segurado]                NVARCHAR (255) NULL,
    [ Aliquota de Tributação  ]       NVARCHAR (255) NULL
);

