CREATE TABLE [dbo].[MR303B_TEMP] (
    [Codigo]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [DataArquivo]              DATETIME        NULL,
    [NomeArquivo]              NVARCHAR (300)  NULL,
    [Nome]                     VARCHAR (300)   NULL,
    [CPF]                      CHAR (20)       NULL,
    [RG]                       VARCHAR (15)    NULL,
    [OrgaoExpedidor]           VARCHAR (300)   NULL,
    [Complemento]              VARCHAR (300)   NULL,
    [Endereco]                 VARCHAR (300)   NULL,
    [Bairro]                   VARCHAR (300)   NULL,
    [Cidade]                   VARCHAR (300)   NULL,
    [Estado]                   VARCHAR (300)   NULL,
    [CEP]                      NVARCHAR (300)  NULL,
    [DDD]                      NVARCHAR (300)  NULL,
    [Telefone]                 NVARCHAR (20)   NULL,
    [DDDComercial]             NVARCHAR (10)   NULL,
    [TelefoneComercial]        NVARCHAR (20)   NULL,
    [DDDCelular]               NVARCHAR (10)   NULL,
    [TelefoneCelular]          NVARCHAR (20)   NULL,
    [Email]                    NVARCHAR (200)  NULL,
    [NumeroAgencia]            VARCHAR (10)    NULL,
    [NomeAgencia]              VARCHAR (80)    NULL,
    [EmpregadoCaixa]           VARCHAR (100)   NULL,
    [ApoliceAnterior]          VARCHAR (30)    NULL,
    [Bonus_Renovacao]          DECIMAL (12, 2) NULL,
    [Desconto_Fidelidade]      DECIMAL (12, 2) NULL,
    [Desconto_Publico]         DECIMAL (12, 2) NULL,
    [Desconto_Agrupamento]     DECIMAL (12, 2) NULL,
    [Total_Desconto]           DECIMAL (12, 2) NULL,
    [Total_Desconto_Concebido] DECIMAL (12, 2) NULL,
    [Premio_Total]             DECIMAL (12, 2) NULL,
    [Termino_Vigencia]         DATE            NULL,
    [QuantidadeParcelas]       INT             NULL,
    [Mala_Direta]              VARCHAR (300)   NULL,
    [Valor_Primeira_Parcela]   DECIMAL (12, 2) NULL,
    [Valor_Demais_Parcelas]    DECIMAL (12, 2) NULL,
    [IS_Total]                 DECIMAL (12, 2) NULL,
    [Cobertura_I]              VARCHAR (50)    NULL,
    [IS_I]                     DECIMAL (12, 2) NULL,
    [Premio_I]                 DECIMAL (12, 2) NULL,
    [Cobertura_II]             VARCHAR (50)    NULL,
    [IS_II]                    DECIMAL (12, 2) NULL,
    [Premio_II]                DECIMAL (12, 2) NULL,
    [Cobertura_III]            VARCHAR (50)    NULL,
    [IS_III]                   DECIMAL (12, 2) NULL,
    [Premio_III]               DECIMAL (12, 2) NULL,
    [Cobertura_IV]             VARCHAR (50)    NULL,
    [IS_IV]                    DECIMAL (12, 2) NULL,
    [Premio_IV]                DECIMAL (12, 2) NULL,
    [Cobertura_V]              VARCHAR (50)    NULL,
    [IS_V]                     DECIMAL (12, 2) NULL,
    [Premio_V]                 DECIMAL (12, 2) NULL,
    [Cobertura_VI]             VARCHAR (50)    NULL,
    [IS_VI]                    DECIMAL (12, 2) NULL,
    [Premio_VI]                DECIMAL (12, 2) NULL,
    [Cobertura_VII]            VARCHAR (50)    NULL,
    [IS_VII]                   DECIMAL (12, 2) NULL,
    [Premio_VII]               DECIMAL (12, 2) NULL,
    [Cobertura_VIII]           VARCHAR (50)    NULL,
    [IS_VIII]                  DECIMAL (12, 2) NULL,
    [Premio_VIII]              DECIMAL (12, 2) NULL,
    [Cobertura_IX]             VARCHAR (50)    NULL,
    [IS_IX]                    DECIMAL (12, 2) NULL,
    [Premio_IX]                DECIMAL (12, 2) NULL
);


GO
CREATE CLUSTERED INDEX [idx_MR303B_TEMP]
    ON [dbo].[MR303B_TEMP]([Codigo] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

