CREATE TABLE [dbo].[OD_ODONTO_PF_tmp] (
    [ID]                     INT           NOT NULL,
    [NOME_SUBESTIPULANTE]    VARCHAR (60)  NULL,
    [CODIGO_SEGURADO]        VARCHAR (50)  NULL,
    [CPF_SEGURADO]           VARCHAR (50)  NULL,
    [CPF_TITULAR]            VARCHAR (50)  NULL,
    [NOME_SEGURADO]          VARCHAR (150) NULL,
    [ELEGIBILIDADE_SEGURADO] VARCHAR (50)  NULL,
    [SITUACAO_SEGURADO]      VARCHAR (50)  NULL,
    [DATA_CANCELAMENTO]      VARCHAR (50)  NULL,
    [GRAU_PARENTESCO]        VARCHAR (50)  NULL,
    [DATA_NASCIMENTO]        VARCHAR (50)  NULL,
    [DATA_ADESAO]            VARCHAR (50)  NULL,
    [SEXO]                   VARCHAR (50)  NULL,
    [NUMERO_PROPOSTA]        VARCHAR (50)  NULL,
    [ESTADO_CIVIL]           VARCHAR (50)  NULL,
    [FORMA_PAGAMENTO]        VARCHAR (50)  NULL,
    [MODALIDADE]             VARCHAR (50)  NULL,
    [DDD_TELEFONE]           VARCHAR (50)  NULL,
    [TELEFONE_1]             VARCHAR (50)  NULL,
    [TIPO_TELEFONE_1]        VARCHAR (50)  NULL,
    [TELEFONE_2]             VARCHAR (50)  NULL,
    [TIPO_TELEFONE_2]        VARCHAR (50)  NULL,
    [TELEFONE_3]             VARCHAR (50)  NULL,
    [TIPO_TELEFONE_3]        VARCHAR (50)  NULL,
    [CEP]                    VARCHAR (50)  NULL,
    [LOGRADOURO]             VARCHAR (50)  NULL,
    [NUMERO]                 VARCHAR (50)  NULL,
    [COMPLEMENTO]            VARCHAR (50)  NULL,
    [BAIRRO]                 VARCHAR (50)  NULL,
    [LOCALIDADE]             VARCHAR (50)  NULL,
    [UF]                     VARCHAR (50)  NULL,
    [EMAIL]                  VARCHAR (50)  NULL,
    [BANCO]                  VARCHAR (50)  NULL,
    [NUMERO_AGENCIA]         VARCHAR (50)  NULL,
    [UF_AGENCIA]             VARCHAR (50)  NULL,
    [CODIGO_PLANO]           VARCHAR (50)  NULL,
    [NOME_PLANO]             VARCHAR (50)  NULL,
    [INICIO_VIGENCIA]        VARCHAR (50)  NULL,
    [FIM_VIGENCIA]           VARCHAR (50)  NULL,
    [VALOR_MENSAL]           VARCHAR (50)  NULL,
    [DATA_ARQUIVO]           DATE          NOT NULL,
    [NOME_ARQUIVO]           VARCHAR (150) NOT NULL,
    [CPFTRATADO]             AS            ((((((substring([CPF_SEGURADO],(1),(3))+'.')+substring([CPF_SEGURADO],(4),(3)))+'.')+substring([CPF_SEGURADO],(7),(3)))+'-')+right([CPF_SEGURADO],(2)))
);

