CREATE TABLE [dbo].[Paullyanna] (
    [NumeroProposta]              VARCHAR (20)    NULL,
    [NumeroContrato]              VARCHAR (20)    NOT NULL,
    [DataEmissao]                 DATE            NULL,
    [NumeroEndosso]               INT             NULL,
    [DataInicioVigencia]          DATE            NULL,
    [DataFimVigencia]             DATE            NULL,
    [CodigoComercializado]        VARCHAR (5)     NOT NULL,
    [Descricao]                   VARCHAR (100)   NULL,
    [Cliente]                     VARCHAR (140)   NULL,
    [CEP]                         VARCHAR (9)     NULL,
    [TipoLogadouro]               VARCHAR (1)     NOT NULL,
    [Endereco]                    VARCHAR (150)   NULL,
    [Numeracao]                   VARCHAR (1)     NOT NULL,
    [UF]                          CHAR (2)        NULL,
    [Cidade]                      VARCHAR (80)    NULL,
    [Bairro]                      VARCHAR (80)    NULL,
    [CPFCNPJ]                     VARCHAR (18)    NULL,
    [Cidade Local Risco]          VARCHAR (1)     NOT NULL,
    [Estado Local Risco]          VARCHAR (1)     NOT NULL,
    [CodigoCobertura]             SMALLINT        NULL,
    [ImportanciaSegurada]         DECIMAL (19, 2) NULL,
    [AreaSegurada]                VARCHAR (1)     NOT NULL,
    [DataRisco]                   VARCHAR (1)     NOT NULL,
    [% Franquia]                  VARCHAR (1)     NOT NULL,
    [ValorFranquia]               DECIMAL (19, 2) NULL,
    [ValorBaseComissao]           DECIMAL (38, 6) NULL,
    [ValorComissaoPAR]            DECIMAL (38, 6) NULL,
    [Vencimento Primeira Parcela] VARCHAR (1)     NOT NULL,
    [TelefoneResidencial]         VARCHAR (40)    NULL,
    [TelefoneComercial]           VARCHAR (14)    NULL,
    [NomePropriedade]             VARCHAR (1)     NOT NULL,
    [EnderecoRisco]               VARCHAR (1)     NOT NULL,
    [Ocupacao]                    VARCHAR (1)     NOT NULL,
    [DiaVencimento]               TINYINT         NULL,
    [QuantidadeParcelas]          TINYINT         NULL,
    [DataProposta]                DATE            NULL,
    [Data Cancelamento]           VARCHAR (8)     NOT NULL,
    [TipoEndosso]                 VARCHAR (50)    NULL,
    [DataComissao]                DATE            NULL
);

