CREATE TABLE [dbo].[Prestamista_Diario_TEMP] (
    [ID]                       BIGINT          NOT NULL,
    [UF]                       VARCHAR (2)     NULL,
    [CEP]                      VARCHAR (8)     NULL,
    [DDD]                      VARCHAR (4)     NULL,
    [MES_REFERENCIA_MOVIMENTO] VARCHAR (8)     NULL,
    [MES_GERACAO_ARQUIVO]      VARCHAR (8)     NULL,
    [COD_PRODUTO]              VARCHAR (4)     NULL,
    [COD_TIPO_REPASSE]         VARCHAR (1)     NULL,
    [SUREG_CONCESSAO]          VARCHAR (2)     NOT NULL,
    [AGENCIA_CONCESSAO]        VARCHAR (4)     NOT NULL,
    [OPERACAO_APLICACAO]       VARCHAR (4)     NOT NULL,
    [NUM_CONTRATO]             VARCHAR (18)    NOT NULL,
    [NUM_DV_CONTRATO]          VARCHAR (2)     NOT NULL,
    [CONTRATO]                 VARCHAR (24)    NULL,
    [COD_MODALIDADE_OPER]      VARCHAR (4)     NOT NULL,
    [COD_CANAL]                VARCHAR (4)     NULL,
    [NOME_CANAL]               VARCHAR (15)    NULL,
    [NOME_CLIENTE]             VARCHAR (50)    NULL,
    [DTA_CONCESSAO_CONTR]      DATE            NOT NULL,
    [DTA_TERMINO_CONTR]        DATE            NOT NULL,
    [VALOR_CONTRATO]           DECIMAL (18, 8) NOT NULL,
    [VALOR_SEGURO]             DECIMAL (18, 8) NOT NULL,
    [TIPO_PESSOA]              VARCHAR (1)     NOT NULL,
    [NUM_CPF_CGC]              VARCHAR (12)    NOT NULL,
    [TAXA_APLICADA]            DECIMAL (5, 2)  NOT NULL,
    [COD_NAT_EMPRESA]          VARCHAR (2)     NOT NULL,
    [EST_CONTRATO_ORIGEM]      VARCHAR (18)    NOT NULL,
    [COD_NAT_PROFISSIONAL]     VARCHAR (4)     NOT NULL,
    [PRZ_VENC_CONTRATO]        VARCHAR (3)     NOT NULL,
    [DT_NASCIMENTO]            DATE            NOT NULL,
    [IDADE]                    VARCHAR (3)     NULL,
    [SEXO]                     VARCHAR (1)     NULL,
    [ESTADO_CIVIL]             VARCHAR (2)     NULL,
    [ENDERECO]                 VARCHAR (50)    NULL,
    [COMPL_ENDERECO]           VARCHAR (30)    NULL,
    [CIDADE]                   VARCHAR (30)    NULL,
    [TELEFONE]                 VARCHAR (9)     NULL,
    [EMAIL]                    VARCHAR (35)    NULL,
    [COD_MATRICULA]            VARCHAR (7)     NULL,
    [TIPO_CORRESPONDENTE]      VARCHAR (2)     NULL,
    [COD_CORRESPONDENTE]       VARCHAR (8)     NULL,
    [DV_CORRESPONDENTE]        VARCHAR (1)     NULL,
    [NomeArquivo]              VARCHAR (50)    NOT NULL,
    [DataArquivo]              DATE            NOT NULL
);

