CREATE TABLE [dbo].[Proposta_COL] (
    [NumeroProposta]            VARCHAR (20)    NOT NULL,
    [NomeSeguradora]            VARCHAR (100)   NULL,
    [CodigoSeguradora]          VARCHAR (6)     NULL,
    [DescricaoProduto]          VARCHAR (100)   NULL,
    [CodigoProduto]             VARCHAR (5)     NOT NULL,
    [NumeroApolice]             VARCHAR (20)    NULL,
    [NumeroEndosso]             INT             NULL,
    [ApoliceAnterior]           VARCHAR (20)    NULL,
    [SituacaoEndosso]           VARCHAR (20)    NULL,
    [DataInicioVigenciaEndosso] DATE            NULL,
    [DataFimVigenciaEndosso]    DATE            NULL,
    [DataEmissao]               DATE            NULL,
    [DataVenda]                 DATE            NULL,
    [DataProposta]              DATE            NULL,
    [DataSituacao]              DATE            NULL,
    [CodigoCobertura]           SMALLINT        NOT NULL,
    [NomeCobertura]             VARCHAR (70)    NOT NULL,
    [ValorPremioLiquido]        NUMERIC (16, 2) NULL,
    [ValorPremioBruto]          NUMERIC (16, 2) NULL,
    [ValorIOF]                  DECIMAL (19, 2) NULL,
    [PeriodicidadePagamento]    VARCHAR (20)    NOT NULL,
    [SiglaSituacaoProposta]     CHAR (3)        NOT NULL,
    [DescricaoSituacaoProposta] VARCHAR (100)   NOT NULL,
    [CodigoMotivo]              SMALLINT        NULL,
    [DescricaoMotivo]           VARCHAR (100)   NULL,
    [TipoSeguro]                VARCHAR (35)    NULL,
    [QuantidadeParcelas]        TINYINT         NULL
);

