CREATE TABLE [dbo].[Proposta_Saude_TEMP] (
    [ID]                                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [IDContrato]                         BIGINT          NULL,
    [IDProduto]                          INT             NULL,
    [IDProdutoAnterior]                  INT             NULL,
    [IDProdutoSIGPF]                     TINYINT         NULL,
    [IDSeguradora]                       SMALLINT        CONSTRAINT [DF_Proposta_Saude_IDSeguradora] DEFAULT ((18)) NOT NULL,
    [NumeroProposta]                     VARCHAR (20)    NOT NULL,
    [NumeroPropostaEMISSAO]              VARCHAR (20)    NULL,
    [IDPeriodicidadePagamento]           TINYINT         NULL,
    [CanalVendaPAR]                      VARCHAR (5)     NULL,
    [DataProposta]                       DATE            NULL,
    [DataInicioVigencia]                 DATE            NULL,
    [DataFimVigencia]                    DATE            NULL,
    [IDFuncionario]                      INT             NULL,
    [Valor]                              DECIMAL (24, 4) NULL,
    [RendaIndividual]                    DECIMAL (24, 4) NULL,
    [RendaFamiliar]                      DECIMAL (24, 4) NULL,
    [IDAgenciaVenda]                     SMALLINT        NULL,
    [DataSituacao]                       DATE            NULL,
    [IDSituacaoProposta]                 INT             NULL,
    [IDSituacaoCobranca]                 INT             NULL,
    [IDTipoMotivo]                       SMALLINT        NULL,
    [TipoDado]                           VARCHAR (80)    NOT NULL,
    [DataArquivo]                        DATE            NOT NULL,
    [ValorPremioBrutoEmissao]            NUMERIC (16, 2) NULL,
    [ValorPremioLiquidoEmissao]          NUMERIC (16, 2) NULL,
    [ValorPremioBrutoCalculado]          NUMERIC (16, 2) NULL,
    [ValorPremioLiquidoCalculado]        NUMERIC (16, 2) NULL,
    [ValorPagoAcumulado]                 NUMERIC (16, 2) NULL,
    [ValorPremioTotal]                   NUMERIC (16, 2) NULL,
    [RenovacaoAutomatica]                VARCHAR (1)     NULL,
    [PercentualDesconto]                 NUMERIC (5, 2)  NULL,
    [EmpresaConvenente]                  VARCHAR (40)    NULL,
    [MatriculaConvenente]                VARCHAR (8)     NULL,
    [OpcaoCobertura]                     VARCHAR (1)     NULL,
    [CodigoPlano]                        VARCHAR (4)     NULL,
    [DataAutenticacaoSICOB]              DATE            NULL,
    [AgenciaPagamentoSICOB]              VARCHAR (4)     NULL,
    [TarifaCobrancaSICOB]                NUMERIC (15, 2) NULL,
    [DataCreditoSASSESICOB]              DATE            NULL,
    [ValorComissaoSICOB]                 NUMERIC (15, 2) NULL,
    [PeriodicidadePagamento]             VARCHAR (2)     NULL,
    [OpcaoConjuge]                       VARCHAR (1)     NULL,
    [OrigemProposta]                     VARCHAR (2)     NULL,
    [DeclaracaoSaudeTitular]             VARCHAR (7)     NULL,
    [DeclaracaoSaudeConjuge]             VARCHAR (7)     NULL,
    [AposentadoriaInvalidez]             VARCHAR (1)     NULL,
    [CodigoSegmento]                     VARCHAR (4)     NULL,
    [SubGrupo]                           INT             NULL,
    [Nome]                               VARCHAR (60)    NULL,
    [CepResidencial]                     VARCHAR (8)     NULL,
    [EnderecoResidencial]                VARCHAR (60)    NULL,
    [CNPJCPF]                            VARCHAR (14)    NULL,
    [TipoLogradouroResidencial]          VARCHAR (7)     NULL,
    [NumeroEnderecoResidencial]          VARCHAR (5)     NULL,
    [ComplementoEnderecoResidencial]     VARCHAR (50)    NULL,
    [BairroResidencial]                  VARCHAR (30)    NULL,
    [CidadeResidencial]                  VARCHAR (15)    NULL,
    [EstadoResidencial]                  VARCHAR (2)     NULL,
    [DDDResidencial]                     VARCHAR (3)     NULL,
    [TelefoneResidencial]                VARCHAR (15)    NULL,
    [EMPRESA]                            VARCHAR (2)     NOT NULL,
    [NomeSeguradora]                     VARCHAR (60)    NOT NULL,
    [SeguradoraProtheus]                 VARCHAR (4)     NOT NULL,
    [CepCobranca]                        VARCHAR (8)     NULL,
    [EnderecoCobranca]                   VARCHAR (60)    NULL,
    [TipoLogradouroCobranca]             VARCHAR (7)     NULL,
    [NumeroEnderecoCobranca]             VARCHAR (5)     NULL,
    [ComplementoEnderecoCobranca]        VARCHAR (50)    NULL,
    [BairroCobranca]                     VARCHAR (30)    NULL,
    [CidadeCobranca]                     VARCHAR (15)    NULL,
    [EstadoCobranca]                     VARCHAR (2)     NULL,
    [DDDCobranca]                        VARCHAR (3)     NULL,
    [TelefoneCobranca]                   VARCHAR (15)    NULL,
    [CepCorrespondencia]                 VARCHAR (8)     NULL,
    [EnderecoCorrespondencia]            VARCHAR (60)    NULL,
    [TipoLogradouroCorrespondencia]      VARCHAR (7)     NULL,
    [NumeroEnderecoCorrespondencia]      VARCHAR (5)     NULL,
    [ComplementoEnderecoCorrespondencia] VARCHAR (50)    NULL,
    [BairroCorrespondencia]              VARCHAR (30)    NULL,
    [CidadeCorrespondencia]              VARCHAR (15)    NULL,
    [EstadoCorrespondencia]              VARCHAR (2)     NULL,
    [DDDCorrespondencia]                 VARCHAR (3)     NULL,
    [TelefoneCorrespondencia]            VARCHAR (15)    NULL,
    [Email]                              VARCHAR (120)   NULL,
    [EmailComercial]                     VARCHAR (120)   NULL,
    [SegmentoProtheus]                   VARCHAR (4)     NOT NULL,
    [CodigoFormaPagamento]               VARCHAR (4)     NOT NULL,
    [Banco]                              SMALLINT        NOT NULL,
    [Agencia]                            VARCHAR (10)    NOT NULL,
    [Operacao]                           VARCHAR (10)    NOT NULL,
    [ContaCorrente]                      VARCHAR (20)    NOT NULL,
    [DiaVencimento]                      TINYINT         NULL,
    [CodigoRamoPAR]                      VARCHAR (2)     NOT NULL,
    [NumeroContrato]                     VARCHAR (20)    NULL,
    [Coparticipacao]                     INT             NULL,
    [IDTipoAdesao]                       INT             NULL,
    [DataNascimento]                     DATE            NULL,
    [IDSexo]                             TINYINT         NULL,
    [IDEstadoCivil]                      TINYINT         NULL,
    [Identidade]                         VARCHAR (15)    NULL,
    [OrgaoExpedidor]                     VARCHAR (5)     NULL,
    [DataExpedicaoRG]                    DATE            NULL,
    [DescricaoSegmento]                  VARCHAR (30)    NULL,
    [DescricaoCanal]                     VARCHAR (30)    NULL,
    [StatusProposta]                     INT             NOT NULL,
    [NomeCanal]                          VARCHAR (20)    NOT NULL,
    CONSTRAINT [PK_PROPOSTA_TEMP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE)
);


GO
CREATE NONCLUSTERED INDEX [idx_NDX_NumeroProposta_Saude_TEMP]
    ON [dbo].[Proposta_Saude_TEMP]([NumeroProposta] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

