CREATE TABLE [dbo].[PS_CRED_CONS_PRESTAMISTA_temp] (
    [ID]                  BIGINT        NOT NULL,
    [CONTRATO]            VARCHAR (255) NULL,
    [CPF_CGC]             VARCHAR (255) NULL,
    [NUM_CONTROLE_CPF]    VARCHAR (255) NULL,
    [NUM_DEPENDENTE]      VARCHAR (255) NULL,
    [DTA_LIBERACAO]       VARCHAR (255) NULL,
    [VAL_CONTRATO]        VARCHAR (255) NULL,
    [COD_SUREG]           VARCHAR (255) NULL,
    [COD_AGENCIA]         VARCHAR (255) NULL,
    [COD_TIPO_CONTRATO]   VARCHAR (255) NULL,
    [COD_CANAL_CONCESSAO] VARCHAR (255) NULL,
    [COD_CONVENENTE]      VARCHAR (255) NULL,
    [COD_CORRESPONDENTE]  VARCHAR (255) NULL,
    [SEGURO]              VARCHAR (255) NULL,
    [VAL_SEGURO]          VARCHAR (255) NULL,
    [SITUACAO_CONTRATO]   VARCHAR (255) NULL,
    [MATRICULA]           VARCHAR (255) NULL,
    [NOME_FUNCIONARIO]    VARCHAR (255) NULL,
    [DataArquivo]         DATE          NULL,
    [NomeArquivo]         VARCHAR (150) NULL,
    [CPFTRATADO]          VARCHAR (267) NULL
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150310-161031]
    ON [dbo].[PS_CRED_CONS_PRESTAMISTA_temp]([CPFTRATADO] ASC) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

