CREATE TABLE [dbo].[SIMULADOR_AUTO_BKP_UPDATE_BU] (
    [ID]                              INT             NOT NULL,
    [IDSituacaoCalculo]               TINYINT         NULL,
    [DataCalculo]                     DATE            NULL,
    [NumeroCalculo]                   INT             NULL,
    [DataInicioVigencia]              DATE            NULL,
    [CodModelo]                       INT             NULL,
    [IDVeiculo]                       INT             NULL,
    [Placa]                           VARCHAR (8)     NULL,
    [Chassis]                         VARCHAR (18)    NULL,
    [Ano]                             SMALLINT        NULL,
    [Carroceria]                      VARCHAR (40)    NULL,
    [IDAgenciaVenda]                  SMALLINT        NULL,
    [IDIndicador]                     INT             NULL,
    [CPFCNPJ]                         VARCHAR (19)    NULL,
    [NomeCliente]                     VARCHAR (150)   NULL,
    [TipoPessoa]                      CHAR (1)        NULL,
    [IDSexo]                          TINYINT         NULL,
    [DataNascimento]                  DATE            NULL,
    [IDTipoCliente]                   TINYINT         NULL,
    [IDEstadoCivil]                   TINYINT         NULL,
    [DDDTelefoneContato]              VARCHAR (3)     NULL,
    [TelefoneContato]                 VARCHAR (10)    NULL,
    [UF]                              CHAR (2)        NULL,
    [Cidade]                          VARCHAR (200)   NULL,
    [CEP]                             VARCHAR (10)    NULL,
    [Apelido]                         VARCHAR (100)   NULL,
    [IDClasseBonusAnterior]           TINYINT         NULL,
    [IDTipoSeguro]                    TINYINT         NULL,
    [IDFaixaMediaKMParticular]        TINYINT         NULL,
    [IDFaixaMediaKMComercial]         TINYINT         NULL,
    [EstendeCoberturaMenores]         BIT             NULL,
    [PrecisaVistoria]                 BIT             NULL,
    [ProdutoMulher]                   BIT             NULL,
    [Produto0Km]                      BIT             NULL,
    [IsentoFran1Sin]                  BIT             NULL,
    [IsentoFranEquip]                 BIT             NULL,
    [IsentoFranCarroc]                BIT             NULL,
    [Turbinado]                       BIT             NULL,
    [Blindado]                        BIT             NULL,
    [CobVidros]                       BIT             NULL,
    [CobDespesasExtras]               BIT             NULL,
    [CobLantFarRetro]                 BIT             NULL,
    [CobDanosMateriais]               DECIMAL (19, 2) NULL,
    [CobDanosMorais]                  DECIMAL (19, 2) NULL,
    [CobDanosCorporais]               DECIMAL (19, 2) NULL,
    [CobAPP]                          DECIMAL (19, 2) NULL,
    [DespesasMedHosp]                 DECIMAL (19, 2) NULL,
    [ValorPremio]                     DECIMAL (19, 2) NULL,
    [ValorFIPE]                       DECIMAL (19, 2) NULL,
    [IDFormaPagtoParcela1]            TINYINT         NULL,
    [IDFormaPagtoDemaisParcelas]      TINYINT         NULL,
    [IDPerfil_Qar]                    TINYINT         NULL,
    [IDAss24h]                        TINYINT         NULL,
    [IDCarroReserva]                  TINYINT         NULL,
    [IDTipoUsoVeiculo]                TINYINT         NULL,
    [IDFormaContratacao]              TINYINT         NULL,
    [IDTipoFranquia]                  TINYINT         NULL,
    [IDTipoRelacaoSegurado]           TINYINT         NULL,
    [IDTipoCarroReserva]              TINYINT         NULL,
    [QRRespondido]                    BIT             NULL,
    [QtdParcelas]                     TINYINT         NULL,
    [Email]                           VARCHAR (70)    NULL,
    [IDProposta]                      BIGINT          NULL,
    [IDContratoAnterior]              BIGINT          NULL,
    [Arquivo]                         VARCHAR (150)   NULL,
    [DataArquivo]                     DATE            NULL,
    [CPFCNPJ_NOFORMAT]                VARCHAR (8000)  NULL,
    [CPFCNPJ_BIGINT]                  BIGINT          NULL,
    [DataNascimentoPrincipalCondutor] DATE            NULL,
    [EstadoCivilPrincipalCondutor]    VARCHAR (20)    NULL,
    [PrincipalCondutorTrabalha]       VARCHAR (20)    NULL,
    [PrincipalCondutorEstuda]         VARCHAR (20)    NULL,
    [CadastroOpcionais]               VARCHAR (200)   NULL,
    [ValorFranquia]                   DECIMAL (19, 2) NULL,
    [TIPO_COMBUSTIVEL]                VARCHAR (50)    NULL,
    [UFPLACA]                         CHAR (2)        NULL,
    [CEPResidenciaEOMesmo]            VARCHAR (20)    NULL,
    [GuardaVeiculoGaragem]            VARCHAR (50)    NULL,
    [CPFPrincipalCondutor]            VARCHAR (20)    NULL,
    [NomePrincipalCondutor]           VARCHAR (200)   NULL,
    [SexoPrincipalCondutor]           VARCHAR (20)    NULL,
    [CodigoFipe]                      VARCHAR (10)    NULL,
    [CodFipe_Fabricante]              VARCHAR (3)     NULL,
    [CodFipe_Modelo]                  VARCHAR (3)     NULL,
    [CodFipe_ModeloDV]                VARCHAR (1)     NULL,
    [Rowversion]                      ROWVERSION      NOT NULL,
    [CPFCNPJ_CI_AS]                   VARCHAR (19)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

