CREATE TABLE [dbo].[SSD_Consulta2] (
    [SUK_ENDOSSO_FINANCEIRO]       INT              NOT NULL,
    [NUM_ENDOSSO]                  INT              NOT NULL,
    [DTH_EMISSAO_ENDOSSO]          DATETIME         NOT NULL,
    [COD_TIPO_ENDOSSO]             CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [COD_TIPO_MOVIMENTO_EF]        SMALLINT         NOT NULL,
    [COD_RAMO_EMISSOR_EF]          SMALLINT         NOT NULL,
    [DTH_INI_VIGENCIA_EF]          DATETIME         NOT NULL,
    [DTH_FIM_VIGENCIA_EF]          DATETIME         NOT NULL,
    [VLR_PREMIO_TARIFARIO_EF]      DECIMAL (15, 2)  NOT NULL,
    [VLR_PREMIO_LIQUIDO_EF]        DECIMAL (15, 2)  NOT NULL,
    [VLR_IOF_EF]                   DECIMAL (15, 2)  NOT NULL,
    [VLR_PREMIO_BRUTO_EF]          DECIMAL (15, 2)  NOT NULL,
    [DTH_OPERACAO_EF]              DATETIME         NOT NULL,
    [COD_OPERACAO_EF]              SMALLINT         NOT NULL,
    [COD_SUBGRUPO_EF]              SMALLINT         NOT NULL,
    [COD_FILIAL]                   SMALLINT         NOT NULL,
    [COD_MODALIDADE_EF]            SMALLINT         NOT NULL,
    [DTH_ATUALIZACAO_MV]           DATETIME         NOT NULL,
    [VLR_PREMIO_BRUTO_MV]          DECIMAL (15, 2)  NULL,
    [VLR_PREMIO_LIQUIDO_MV]        DECIMAL (21, 8)  NULL,
    [VLR_IOF_MV]                   DECIMAL (15, 10) NULL,
    [PCT_PART_CORRETOR]            DECIMAL (5, 2)   NULL,
    [PCT_COM_CORRETOR]             DECIMAL (5, 2)   NULL,
    [NOM_PRODUTOR]                 VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_BIL_CERTIF]               DECIMAL (15)     NULL,
    [NUM_PROPOSTA_SIVPF]           NVARCHAR (4000)  NULL,
    [NUM_APOLICE]                  DECIMAL (15)     NULL,
    [COD_SUBGRUPO]                 SMALLINT         NULL,
    [IND_ORIGEM_REGISTRO]          CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_PARCELA]                  INT              NULL,
    [VLR_PREMIO_PARCELA]           DECIMAL (15, 2)  NULL,
    [VLR_PREMIO_LIQUIDO_PARCELA]   DECIMAL (21, 8)  NULL,
    [VLR_IOF_PARCELA]              DECIMAL (15, 10) NULL,
    [VLR_PREMIO_VG]                DECIMAL (15, 2)  NULL,
    [VLR_PREMIO_AP]                DECIMAL (15, 2)  NULL,
    [VLR_TARIFA]                   DECIMAL (15, 2)  NULL,
    [VLR_BALCAO]                   DECIMAL (15, 2)  NULL,
    [DTH_BAIXA_PARCELA]            DATETIME         NULL,
    [NUM_TITULO]                   DECIMAL (13)     NULL,
    [COD_TIPO_MOVIMENTO]           SMALLINT         NULL,
    [COD_ORIGEM_PAGAMENTO]         CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_PRODUTO_SIAS]             SMALLINT         NULL,
    [COD_PRODUTO_SIVPF]            SMALLINT         NULL,
    [NOM_PRODUTO_SIAS]             VARCHAR (8000)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NOM_PRODUTO_SIVPF]            VARCHAR (8000)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CLIENTE_PE]               INT              NULL,
    [NUM_OCORR_ENDERECO_PE]        SMALLINT         NULL,
    [NOM_PESSOA_PE]                VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PE]              VARCHAR (20)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PE]            DATETIME         NULL,
    [COD_SEXO_PE]                  CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PE]          CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PE]          VARCHAR (30)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PE]           CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PE]                 VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PE]            VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PE]       VARCHAR (10)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PE]         CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PE]             DATETIME         NULL,
    [COD_DDD_TELEFONE_PE]          SMALLINT         NULL,
    [COD_TELEFONE_PE]              INT              NULL,
    [COD_DDD_CELULAR_PE]           SMALLINT         NULL,
    [COD_CELULAR_PE]               INT              NULL,
    [COD_CBO_PE]                   INT              NULL,
    [DES_ENDERECO_PE]              VARCHAR (255)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PE]                VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PE]                VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PE]                    CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PE]  VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PE]                SMALLINT         NULL,
    [COD_CEP_PE]                   VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PE]                 SMALLINT         NULL,
    [COD_AGENCIA_PE]               SMALLINT         NULL,
    [NUM_CONTA_PE]                 DECIMAL (15)     NULL,
    [NUM_DV_CONTA_PE]              SMALLINT         NULL,
    [NUM_OPERACAO_CONTA_PE]        SMALLINT         NULL,
    [COD_ORIGEM_PESSOA_PE]         SMALLINT         NULL,
    [COD_CLIENTE_PSE]              INT              NULL,
    [NUM_OCORR_ENDERECO_PSE]       SMALLINT         NULL,
    [NOM_PESSOA_PSE]               VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PSE]             VARCHAR (20)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PSE]           DATETIME         NULL,
    [COD_SEXO_PSE]                 CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PSE]         CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PSE]         VARCHAR (30)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PSE]          CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PSE]                VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PSE]           VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PSE]      VARCHAR (10)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PSE]        CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PSE]            DATETIME         NULL,
    [COD_DDD_TELEFONE_PSE]         SMALLINT         NULL,
    [COD_TELEFONE_PSE]             INT              NULL,
    [COD_DDD_CELULAR_PSE]          SMALLINT         NULL,
    [COD_CELULAR_PSE]              INT              NULL,
    [COD_CBO_PSE]                  INT              NULL,
    [DES_ENDERECO_PSE]             VARCHAR (255)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PSE]               VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PSE]               VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PSE]                   CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PSE] VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PSE]               SMALLINT         NULL,
    [COD_CEP_PSE]                  VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PSE]                SMALLINT         NULL,
    [COD_AGENCIA_PSE]              SMALLINT         NULL,
    [NUM_CONTA_PSE]                DECIMAL (15)     NULL,
    [NUM_DV_CONTA_PSE]             SMALLINT         NULL,
    [NUM_OPERACAO_CONTA_PSE]       SMALLINT         NULL,
    [COD_ORIGEM_PSESSOA_PSE]       SMALLINT         NULL,
    [COD_CLIENTE_PS]               INT              NULL,
    [NUM_OCORR_ENDERECO_PS]        SMALLINT         NULL,
    [NOM_PESSOA_PS]                VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_CPF_CNPJ_PS]              VARCHAR (20)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_NASCIMENTO_PS]            DATETIME         NULL,
    [COD_SEXO_PS]                  CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_ESTADO_CIVIL_PS]          CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ESTADO_CIVIL_PS]          VARCHAR (30)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [IND_TIPO_PESSOA_PS]           CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_EMAIL_PS]                 VARCHAR (200)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IDENTIDADE_PS]            VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_ORGAO_EXPEDIDOR_PS]       VARCHAR (10)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_EXPEDIDORA_PS]         CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DTH_EXPEDICAO_PS]             DATETIME         NULL,
    [COD_DDD_TELEFONE_PS]          SMALLINT         NULL,
    [COD_TELEFONE_PS]              INT              NULL,
    [COD_DDD_CELULAR_PS]           SMALLINT         NULL,
    [COD_CELULAR_PS]               INT              NULL,
    [COD_CBO_PS]                   INT              NULL,
    [DES_ENDERECO_PS]              VARCHAR (255)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_BAIRRO_PS]                VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_CIDADE_PS]                VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_UF_PS]                    CHAR (2)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DES_COMPLEMENTO_ENDERECO_PS]  VARCHAR (100)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NUM_IMOVEL_PS]                SMALLINT         NULL,
    [COD_CEP_PS]                   VARCHAR (15)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [COD_BANCO_PS]                 SMALLINT         NULL,
    [COD_AGENCIA_PS]               SMALLINT         NULL,
    [NUM_CONTA_PS]                 DECIMAL (15)     NULL,
    [NUM_DV_CONTA_PS]              SMALLINT         NULL,
    [NUM_OPERACAO_CONTA_PS]        SMALLINT         NULL,
    [COD_ORIGEM_PESSOA_PS]         SMALLINT         NULL,
    [NomeArquivo]                  VARCHAR (150)    NULL,
    [DataArquivo]                  DATE             NULL
);

