CREATE TABLE [dbo].[Temp_BaseAdesaoLoterico] (
    [CODIGO]      FLOAT (53)     NULL,
    [CL]          NVARCHAR (255) NULL,
    [ESCNEG]      FLOAT (53)     NULL,
    [UF]          NVARCHAR (255) NULL,
    [AGEN]        FLOAT (53)     NULL,
    [APOLICE]     FLOAT (53)     NULL,
    [CNPJ]        FLOAT (53)     NULL,
    [DTINI]       DATETIME       NULL,
    [DTTER]       DATETIME       NULL,
    [DTEMIS]      DATETIME       NULL,
    [NR#ENDOS]    FLOAT (53)     NULL,
    [PRM-INC]     FLOAT (53)     NULL,
    [PRM-VEND]    FLOAT (53)     NULL,
    [PRM-DAN]     FLOAT (53)     NULL,
    [PRM-PARAL]   FLOAT (53)     NULL,
    [PRM-ALUG]    FLOAT (53)     NULL,
    [PRM-TUM]     FLOAT (53)     NULL,
    [PRM-VID]     FLOAT (53)     NULL,
    [PRM-VAL]     FLOAT (53)     NULL,
    [PRM-VALP]    FLOAT (53)     NULL,
    [PRM-MMU]     FLOAT (53)     NULL,
    [PRM-SPR]     FLOAT (53)     NULL,
    [PRM-RCGV]    FLOAT (53)     NULL,
    [PRM-RCOL]    FLOAT (53)     NULL,
    [PRM-EACT]    FLOAT (53)     NULL,
    [PCL]         FLOAT (53)     NULL,
    [PAG]         FLOAT (53)     NULL,
    [TOT-PRM-EMI] FLOAT (53)     NULL,
    [TOT-PRM-PAG] FLOAT (53)     NULL,
    [TOT-PRM-MES] FLOAT (53)     NULL,
    [IS-INC]      FLOAT (53)     NULL,
    [IS-VEND]     FLOAT (53)     NULL,
    [IS-DAN]      FLOAT (53)     NULL,
    [IS-PARAL]    FLOAT (53)     NULL,
    [IS-ALUG]     FLOAT (53)     NULL,
    [IS-TUM]      FLOAT (53)     NULL,
    [IS-VID]      FLOAT (53)     NULL,
    [IS-VAL]      FLOAT (53)     NULL,
    [IS-VALP]     FLOAT (53)     NULL,
    [IS-MMU]      FLOAT (53)     NULL,
    [IS-SPR]      FLOAT (53)     NULL,
    [IS-RCGV]     FLOAT (53)     NULL,
    [IS-RCOL]     FLOAT (53)     NULL,
    [IS-EACT]     FLOAT (53)     NULL,
    [TX-INC]      FLOAT (53)     NULL,
    [TX-VEND]     FLOAT (53)     NULL,
    [TX-DAN]      FLOAT (53)     NULL,
    [TX-PARAL]    FLOAT (53)     NULL,
    [TX-ALUG]     FLOAT (53)     NULL,
    [TX-TUM]      FLOAT (53)     NULL,
    [TX-VID]      FLOAT (53)     NULL,
    [TX-VAL]      FLOAT (53)     NULL,
    [TX-VALP]     FLOAT (53)     NULL,
    [TX-MMU]      FLOAT (53)     NULL,
    [TX-SPR]      FLOAT (53)     NULL,
    [TX-RCGV]     FLOAT (53)     NULL,
    [TX-RCOL]     FLOAT (53)     NULL,
    [TX-EACT]     FLOAT (53)     NULL,
    [DATA]        DATETIME       NULL,
    [SITUACAO]    NVARCHAR (255) NULL,
    [VLR]         FLOAT (53)     NULL,
    [y]           FLOAT (53)     NULL,
    [PROD]        FLOAT (53)     NULL,
    [produto]     NVARCHAR (255) NULL,
    [SITUACAO 2]  NVARCHAR (255) NULL,
    [F66]         NVARCHAR (255) NULL,
    [F67]         NVARCHAR (255) NULL,
    [F68]         NVARCHAR (255) NULL
);

