CREATE TABLE [dbo].[Temp_Celulares_SF_SULA] (
    [TERVIG]                         DATETIME       NULL,
    [APOLICE]                        FLOAT (53)     NULL,
    [CPF_BIGINT]                     FLOAT (53)     NULL,
    [SEGURADO]                       NVARCHAR (255) NULL,
    [FONE_BU]                        FLOAT (53)     NULL,
    [CELULAR_BU]                     FLOAT (53)     NULL,
    [EMAIL]                          NVARCHAR (255) NULL,
    [VEICULO]                        NVARCHAR (255) NULL,
    [PLACA]                          NVARCHAR (255) NULL,
    [DataFimVigencia]                DATETIME       NULL,
    [MES]                            NVARCHAR (255) NULL,
    [IdContrato]                     NVARCHAR (255) NULL,
    [ElegivelRA__c]                  NVARCHAR (255) NULL,
    [IdOportunidade]                 NVARCHAR (255) NULL,
    [Agendamento]                    FLOAT (53)     NULL,
    [ContatoPosAgendamento]          FLOAT (53)     NULL,
    [ContatoPosAgendamento7d]        FLOAT (53)     NULL,
    [ContatoPosAgendamento24h]       FLOAT (53)     NULL,
    [ContatoPosAgendamento7d_ag0a7]  FLOAT (53)     NULL,
    [ContatoPosAgendamento24h_ag0a7] FLOAT (53)     NULL,
    [CPF_CNPJ__c]                    NVARCHAR (255) NULL,
    [AccountId]                      NVARCHAR (255) NULL,
    [Celular_codigo2__pc]            NVARCHAR (255) NULL,
    [PersonMobilePhone]              NVARCHAR (255) NULL,
    [Phone]                          FLOAT (53)     NULL,
    [FONE_BU1]                       FLOAT (53)     NULL,
    [CELULAR_BU1]                    FLOAT (53)     NULL,
    [CELULAR_SA]                     FLOAT (53)     NULL,
    [TELEFONE_SA]                    FLOAT (53)     NULL,
    [F30]                            NVARCHAR (255) NULL
);

