CREATE TABLE [dbo].[Temp_AcompanhaRenovacaoAuto_2] (
    [DataArquivoProposta]                DATE            NOT NULL,
    [DataCreditoSASSESICOB]              DATE            NULL,
    [DataEmissaoProposta]                DATE            NULL,
    [DataFimVigenciaProposta]            DATE            NULL,
    [DataInicioVigenciaProposta]         DATE            NULL,
    [DataProposta]                       DATE            NULL,
    [DataSituacaoContratual]             DATE            NULL,
    [DataVenda]                          DATE            NULL,
    [IDAgenciaVenda]                     SMALLINT        NULL,
    [IDContrato]                         BIGINT          NULL,
    [IDProduto]                          INT             NULL,
    [IDProdutoSIGPF]                     TINYINT         NULL,
    [IDSeguradoraProposta]               SMALLINT        NOT NULL,
    [IDSituacaoProposta]                 TINYINT         NULL,
    [Valor]                              DECIMAL (24, 4) NULL,
    [TipoDado]                           VARCHAR (80)    NOT NULL,
    [ValorPremioBrutoEmissao]            NUMERIC (16, 2) NULL,
    [ID]                                 BIGINT          NOT NULL,
    [IDContratoAnterior]                 BIGINT          NULL,
    [IDProposta]                         BIGINT          NULL,
    [IDSeguradora]                       SMALLINT        NOT NULL,
    [IDRamo]                             SMALLINT        NULL,
    [NumeroContrato]                     VARCHAR (24)    NULL,
    [CodigoFonteProdutora]               SMALLINT        NULL,
    [NumeroBilhete]                      VARCHAR (20)    NULL,
    [NumeroSICOB]                        VARCHAR (9)     NULL,
    [DataEmissao]                        DATE            NULL,
    [DataInicioVigencia]                 DATE            NULL,
    [DataFimVigencia]                    DATE            NULL,
    [DataCancelamento]                   DATE            NULL,
    [ValorPremioLiquido]                 DECIMAL (19, 2) NULL,
    [ValorPremioTotal]                   DECIMAL (19, 2) NULL,
    [DataFimVigenciaAtual]               DATE            NULL,
    [ValorPremioTotalAtual]              DECIMAL (19, 2) NULL,
    [ValorPremioLiquidoAtual]            DECIMAL (19, 2) NULL,
    [IDSituacaoEndosso]                  TINYINT         NULL,
    [QuantidadeParcelas]                 TINYINT         NULL,
    [IDAgencia]                          SMALLINT        NULL,
    [IDIndicador]                        INT             NULL,
    [IDIndicadorGerente]                 INT             NULL,
    [IDIndicadorSuperintendenteRegional] INT             NULL,
    [CodigoMoedaSegurada]                SMALLINT        NULL,
    [CodigoMoedaPremio]                  SMALLINT        NULL,
    [LayoutRisco]                        VARCHAR (10)    NULL,
    [DataArquivo]                        DATE            NOT NULL,
    [Arquivo]                            VARCHAR (80)    NOT NULL,
    [NomeTomador]                        VARCHAR (140)   NULL,
    [EnderecoLocalRisco]                 VARCHAR (200)   NULL,
    [BairroLocalRisco]                   VARCHAR (100)   NULL,
    [CidadeLocalRisco]                   VARCHAR (100)   NULL,
    [UFLocalRisco]                       VARCHAR (2)     NULL,
    [NomeEmpreendimento]                 VARCHAR (100)   NULL,
    [CodigoCorretor1]                    VARCHAR (50)    NULL,
    [CNPJCorretor1]                      VARCHAR (20)    NULL,
    [RazaoSocialCorretor1]               VARCHAR (100)   NULL,
    [CodigoCorretor2]                    VARCHAR (50)    NULL,
    [CNPJCorretor2]                      VARCHAR (50)    NULL,
    [RazaoSocialCorretor2]               VARCHAR (100)   NULL,
    [Data]                               DATE            NULL
);

