CREATE TABLE [dbo].[Temp_Teste_Mailing_BackSeg] (
    [NOME_CAMPANHA]             VARCHAR (1)   NOT NULL,
    [CODIGO_CAMPANHA]           VARCHAR (1)   NOT NULL,
    [CODIGO_MAILING]            VARCHAR (1)   NOT NULL,
    [NOME_CLIENTE]              VARCHAR (200) NULL,
    [CPF]                       CHAR (14)     NULL,
    [DDDTelefone1]              VARCHAR (2)   COLLATE Latin1_General_CI_AS NULL,
    [Telefone1]                 VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [DDDTelefone2]              VARCHAR (2)   COLLATE Latin1_General_CI_AS NULL,
    [Telefone2]                 VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [DDDTelefone3]              VARCHAR (3)   COLLATE Latin1_General_CI_AS NULL,
    [Telefone3]                 VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [DDDTelefone4]              VARCHAR (2)   COLLATE Latin1_General_CI_AS NULL,
    [Telefone4]                 VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [COD_TIPO_CLIENTE]          VARCHAR (1)   NOT NULL,
    [TIPO_CLIENTE]              VARCHAR (200) NULL,
    [ORIGEM_CLIENTE]            VARCHAR (1)   NOT NULL,
    [DATA_CONTATO_CS]           DATE          NULL,
    [DATA_COTACAO_CS]           DATE          NULL,
    [MODELO_VEICULO]            VARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [PLACA_VEICULO]             VARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [VALOR_PREMIO_BRUTO]        VARCHAR (1)   NOT NULL,
    [MOTIVO_RECUSA]             VARCHAR (1)   NOT NULL,
    [TIPO_SEGURO]               VARCHAR (20)  COLLATE Latin1_General_CI_AS NULL,
    [DATA_INICIO_VIGENCIA]      INT           NULL,
    [AGENCIA_COTACAO_CS]        VARCHAR (MAX) COLLATE Latin1_General_CI_AS NULL,
    [NUMERO_COTACAO_CS]         VARCHAR (1)   NOT NULL,
    [ValorFIPE]                 VARCHAR (1)   NOT NULL,
    [TipoPessoa]                VARCHAR (1)   NOT NULL,
    [Sexo]                      VARCHAR (1)   NOT NULL,
    [BONUS_ANTERIOR]            VARCHAR (1)   NOT NULL,
    [CEP]                       VARCHAR (MAX) COLLATE Latin1_General_CI_AS NULL,
    [ESTADO_CIVIL]              VARCHAR (1)   NOT NULL,
    [Email]                     VARCHAR (MAX) COLLATE Latin1_General_CI_AS NULL,
    [TIPO_COND_SEGURADO]        VARCHAR (1)   NOT NULL,
    [DATA_NASC]                 VARCHAR (1)   NOT NULL,
    [ANO_MODELO]                VARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [COD_FIPE]                  VARCHAR (1)   NOT NULL,
    [USO_VEICULO]               VARCHAR (1)   NOT NULL,
    [BLINDADO]                  VARCHAR (1)   NOT NULL,
    [CHASSI]                    VARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [FORMA_CONTRATACAO]         VARCHAR (1)   NOT NULL,
    [TIPO_FRANQUIA]             VARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [DANOS_MATERIAIS]           VARCHAR (1)   NOT NULL,
    [DANOS_MORAIS]              VARCHAR (1)   NOT NULL,
    [DANOS_CORPORAIS]           VARCHAR (1)   NOT NULL,
    [ASSIS_24_HRS]              VARCHAR (1)   NOT NULL,
    [CARRO_RESERVA]             VARCHAR (1)   NOT NULL,
    [GARANTIA_CARRO_RESERVA]    VARCHAR (1)   NOT NULL,
    [APP_PASSAGEIRO]            VARCHAR (1)   NOT NULL,
    [DESP_MEDICO_HOSP]          VARCHAR (1)   NOT NULL,
    [LANT_FAROIS_RETROVIS]      VARCHAR (1)   NOT NULL,
    [VIDROS]                    VARCHAR (1)   NOT NULL,
    [DESP_EXTRAORDINARIAS]      VARCHAR (1)   NOT NULL,
    [ESTENDER_COB_PARA_MENORES] VARCHAR (1)   NOT NULL,
    [DataMailing]               DATE          NULL
);

