CREATE TABLE [dbo].[Temp_CCA_Enriquecido] (
    [CNPJ]                  NVARCHAR (255) NULL,
    [RAZAO_SOCIAL]          NVARCHAR (255) NULL,
    [NOME_FANTASIA]         NVARCHAR (255) NULL,
    [DT_ABERTURA]           DATETIME       NULL,
    [SITUACAO_RECEITA]      NVARCHAR (255) NULL,
    [CD_CNAE]               FLOAT (53)     NULL,
    [DS_CNAE]               NVARCHAR (255) NULL,
    [PORTE]                 NVARCHAR (255) NULL,
    [FATURAMENTO_PRESUMIDO] NVARCHAR (255) NULL,
    [FAIXA_FUNCIONARIOS]    NVARCHAR (255) NULL,
    [TP_LOGRADOURO]         NVARCHAR (255) NULL,
    [LOGRADOURO]            NVARCHAR (255) NULL,
    [NUMERO]                FLOAT (53)     NULL,
    [COMPLEMENTO]           NVARCHAR (255) NULL,
    [BAIRRO]                NVARCHAR (255) NULL,
    [CIDADE]                NVARCHAR (255) NULL,
    [UF]                    NVARCHAR (255) NULL,
    [CEP]                   FLOAT (53)     NULL,
    [DDD1]                  VARCHAR (2)    NULL,
    [TELEFONE1]             VARCHAR (20)   NULL,
    [DDD2]                  VARCHAR (2)    NULL,
    [TELEFONE2]             VARCHAR (20)   NULL,
    [DDD3]                  VARCHAR (2)    NULL,
    [TELEFONE3]             VARCHAR (20)   NULL,
    [NOME_DECISOR]          NVARCHAR (255) NULL,
    [CPF_DECISOR]           FLOAT (53)     NULL,
    [EMAIL1_DECISOR]        NVARCHAR (255) NULL,
    [EMAIL2_DECISOR]        NVARCHAR (255) NULL,
    [EMAIL3_DECISOR]        NVARCHAR (255) NULL
);

