CREATE TABLE [dbo].[Temp_emissaoauto_2] (
    [ANO]               VARCHAR (200) NULL,
    [MÊS]               VARCHAR (200) NULL,
    [APOLICE]           VARCHAR (200) NULL,
    [CPF_CNPJ]          VARCHAR (200) NULL,
    [ENDOSSO]           VARCHAR (200) NULL,
    [PRODUTO_AGRUPADO]  VARCHAR (200) NULL,
    [PREMIO LIQUIDO]    VARCHAR (200) NULL,
    [VLR ADICIONAL]     VARCHAR (200) NULL,
    [VLR CUSTO EMISSAO] VARCHAR (200) NULL,
    [VLR DO IOF ]       VARCHAR (200) NULL,
    [PREMIO  TOTAL]     VARCHAR (200) NULL,
    [DT EMISSAO]        VARCHAR (200) NULL,
    [PRODUTO]           VARCHAR (200) NULL,
    [DIA EMISSAO]       VARCHAR (200) NULL,
    [ INICIO VIGENCIA]  VARCHAR (200) NULL,
    [ TERMINO VIGENCIA] VARCHAR (200) NULL,
    [AGENCIA]           VARCHAR (200) NULL,
    [TIPO DE SEGURO]    VARCHAR (200) NULL,
    [TIPO DE RENOVAÇÃO] VARCHAR (200) NULL,
    [CIA  RENOV]        VARCHAR (200) NULL
);

