CREATE TABLE [dbo].[temp_baseMarcao] (
    [ID]                        INT             NOT NULL,
    [NOME_CAMPANHA]             VARCHAR (100)   COLLATE Latin1_General_CI_AS NULL,
    [COD_CAMPANHA]              VARCHAR (16)    COLLATE Latin1_General_CI_AS NULL,
    [COD_MAILING]               VARCHAR (MAX)   COLLATE Latin1_General_CI_AS NULL,
    [NOME]                      VARCHAR (150)   NULL,
    [cpf]                       VARCHAR (14)    COLLATE Latin1_General_CI_AS NULL,
    [DDD1]                      VARCHAR (2)     NULL,
    [FONE1]                     VARCHAR (9)     NULL,
    [DDD2]                      VARCHAR (2)     COLLATE Latin1_General_CI_AS NULL,
    [FONE2]                     VARCHAR (9)     COLLATE Latin1_General_CI_AS NULL,
    [DDD3]                      VARCHAR (2)     COLLATE Latin1_General_CI_AS NULL,
    [FONE3]                     VARCHAR (9)     COLLATE Latin1_General_CI_AS NULL,
    [DDD4]                      VARCHAR (2)     COLLATE Latin1_General_CI_AS NULL,
    [FONE4]                     VARCHAR (9)     COLLATE Latin1_General_CI_AS NULL,
    [TIPO_DE_CLIENTE]           VARCHAR (100)   COLLATE Latin1_General_CI_AI NULL,
    [TIPO_CLIENTE]              VARCHAR (11)    COLLATE Latin1_General_CI_AS NOT NULL,
    [ORIGEM_CLIENTE]            VARCHAR (26)    COLLATE Latin1_General_CI_AI NOT NULL,
    [DATA_CONTATO_EFETIVO]      DATETIME        NULL,
    [DATA_COTACAO_CS]           DATE            NULL,
    [MODELO_VEICULO]            VARCHAR (100)   NULL,
    [Placa_VEICULO]             VARCHAR (8)     NULL,
    [Valor]                     NUMERIC (19, 2) NULL,
    [MOTIVO_RECUSA]             VARCHAR (100)   COLLATE Latin1_General_CI_AI NULL,
    [TIPO_SEGURO]               VARCHAR (35)    NULL,
    [DATA_INICIO_VIGENCIA]      DATE            NULL,
    [AGENCIA_COTACAO_CS]        SMALLINT        NULL,
    [NUMERO_COTACAO_CS]         INT             NULL,
    [VALOR_FIPE]                NUMERIC (19, 2) NULL,
    [TIPO_PESSOA]               VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [SEXO]                      VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [BONUS_ANTERIOR]            TINYINT         NULL,
    [CEP]                       VARCHAR (10)    NULL,
    [ESTADO_CIVIL]              VARCHAR (30)    NULL,
    [EMAIL]                     VARCHAR (50)    NULL,
    [TIPO_COND_SEGURADO]        VARCHAR (60)    NULL,
    [DATA_NASC]                 DATE            NULL,
    [ANO_MODELO]                SMALLINT        NULL,
    [COD_FIPE]                  INT             NULL,
    [USO_VEICULO]               VARCHAR (60)    NULL,
    [BLINDADO]                  VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [CHASSI]                    VARCHAR (18)    NULL,
    [FORMA_CONTRATAÇÃO]         VARCHAR (60)    NULL,
    [FRANQUIA]                  VARCHAR (15)    NULL,
    [DANOS_MATERIAIS]           NUMERIC (19, 2) NULL,
    [DANOS_MORAIS]              NUMERIC (19, 2) NULL,
    [DANOS_CORPORAIS]           NUMERIC (19, 2) NULL,
    [ASSIS_24_HRS]              TINYINT         NULL,
    [CARRO_RESERVA]             TINYINT         NULL,
    [GARANTIA_CARRO_RESERVA]    VARCHAR (60)    NULL,
    [APP_PASSAGEIRO]            NUMERIC (19, 2) NULL,
    [DESP_MEDICO_HOSP]          NUMERIC (19, 2) NULL,
    [LANT_FAROIS_RETROVIS]      VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [VIDROS]                    VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [DESP_EXTRAORDINARIAS]      VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [ESTENDER_COB_PARA_MENORES] VARCHAR (1)     COLLATE Latin1_General_CI_AS NOT NULL,
    [DATA_MAILING]              DATETIME        NOT NULL
);

