CREATE TABLE [dbo].[Temp_ProvisoesBoxMarco] (
    [COD_FILIAL]             VARCHAR (10)    NULL,
    [Cod_Empresa]            VARCHAR (10)    NULL,
    [Cod_produtor]           VARCHAR (20)    NULL,
    [Item1]                  FLOAT (53)      NULL,
    [Item2]                  FLOAT (53)      NULL,
    [Num_parcela]            FLOAT (53)      NULL,
    [Num_bilhete]            FLOAT (53)      NULL,
    [Item3]                  FLOAT (53)      NULL,
    [Num_ocorr_hist]         FLOAT (53)      NULL,
    [Tipo_corretagem]        FLOAT (53)      NULL,
    [Cod_operacao]           FLOAT (53)      NULL,
    [Cod_ramo_frac]          FLOAT (53)      NULL,
    [Vlr_base]               FLOAT (53)      NULL,
    [Percent_corretagem]     FLOAT (53)      NULL,
    [Valor_corretagem]       FLOAT (53)      NULL,
    [Data_processamento]     DATETIME        NULL,
    [Num_recibo]             FLOAT (53)      NULL,
    [Cod_filial2]            FLOAT (53)      NULL,
    [Cod_subgrupo]           FLOAT (53)      NULL,
    [Cod_produto]            FLOAT (53)      NULL,
    [Cod_Agencia_venda]      FLOAT (53)      NULL,
    [Cod_cep_venda]          FLOAT (53)      NULL,
    [Data_calculo]           DATETIME        NULL,
    [Data_quitacao_parcela]  DATETIME        NULL,
    [Num_proposta]           FLOAT (53)      NULL,
    [Nome_segurado]          FLOAT (53)      NULL,
    [Aliquota_de_tributacao] FLOAT (53)      NULL,
    [vlr_base_F]             DECIMAL (19, 2) NULL,
    [vlr_corretagem_F]       DECIMAL (19, 2) NULL
);

