CREATE TABLE [dbo].[Temp_Oportunidades_SemMarca] (
    [AccountId]                  INT             NULL,
    [CPF]                        VARCHAR (18)    NULL,
    [DevAnoModeloVeiculo__c]     SMALLINT        NULL,
    [DevAnoFabricacaoVeiculo__c] SMALLINT        NULL,
    [DevDataVencimento__c]       DATE            NULL,
    [DevDiasParaVencer__c]       INT             NULL,
    [DevElegivelRA__c]           INT             NULL,
    [DevModeloVeiculo__c]        VARCHAR (100)   NULL,
    [DevNumeroApolice__c]        VARCHAR (24)    NULL,
    [DevPlacaVeiculo__c]         CHAR (8)        NULL,
    [DevProduto__c]              VARCHAR (4)     NOT NULL,
    [BillingCountry]             VARCHAR (6)     NOT NULL,
    [BillingCountryCode]         VARCHAR (2)     NOT NULL,
    [NumeroApoliceAnterior]      VARCHAR (20)    NULL,
    [CodigoSeguradora]           INT             NULL,
    [DataProposta]               DATE            NULL,
    [CodigoComercializado]       VARCHAR (5)     NULL,
    [ProdutoComercializado]      VARCHAR (100)   NULL,
    [Chassis]                    VARCHAR (18)    NULL,
    [DataInicioVigencia]         DATE            NULL,
    [NumeroProposta]             VARCHAR (20)    NULL,
    [QuantidadeParcelas]         INT             NULL,
    [ValorPremioLiquido]         DECIMAL (38, 2) NULL,
    [ValorPremioTotal]           DECIMAL (38, 2) NULL,
    [CodigoUnidade]              SMALLINT        NULL,
    [NomeUnidade]                VARCHAR (100)   NULL,
    [MatriculaIndicador]         VARCHAR (8)     NULL,
    [NomeIndicador]              VARCHAR (100)   NULL,
    [CPFIndicador]               CHAR (14)       NULL,
    [Tipo_de_seguro__c]          VARCHAR (9)     NOT NULL,
    [Renovacao__c]               VARCHAR (10)    NOT NULL,
    [MarcaVeiculo__c]            NCHAR (18)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ModeloVeiculo__c]           NCHAR (18)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ano_Modelo_de_Veiculo__c]   NCHAR (18)      COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Numero_da_proposta__c]      VARCHAR (20)    NULL,
    [StatusContrato__c]          VARCHAR (5)     NOT NULL,
    [Forma_de_pagamento__c]      VARCHAR (6)     NOT NULL,
    [Tipo_cliente_Simulador]     VARCHAR (60)    NULL,
    [Marca__c]                   NVARCHAR (80)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DataEmissao]                DATE            NULL,
    [Tipo_de_Veiculo__c]         NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

