CREATE TABLE [dbo].[testecertificado] (
    [IDErrada]                           BIGINT           NULL,
    [IDPropostaCerto]                    BIGINT           NOT NULL,
    [NumeroProposta]                     VARCHAR (20)     NOT NULL,
    [CodigoComercializado]               VARCHAR (5)      NOT NULL,
    [DataEmissao]                        DATE             NULL,
    [NumeroParcelaPositivo]              SMALLINT         NULL,
    [DataEfetivacaoPositivo]             DATE             NULL,
    [ValorPositivo]                      DECIMAL (24, 10) NULL,
    [ValorNegativo]                      DECIMAL (24, 10) NULL,
    [linha]                              BIGINT           NULL,
    [ID]                                 INT              NOT NULL,
    [IDContrato]                         BIGINT           NULL,
    [IDProposta]                         BIGINT           NULL,
    [IDSeguradora]                       SMALLINT         NOT NULL,
    [NumeroCertificado]                  VARCHAR (20)     NOT NULL,
    [NumeroSICOB]                        VARCHAR (9)      NULL,
    [CPF]                                VARCHAR (18)     NULL,
    [NomeCliente]                        VARCHAR (140)    NULL,
    [DataNascimento]                     DATE             NULL,
    [IDAgencia]                          SMALLINT         NULL,
    [MatriculaIndicador]                 VARCHAR (20)     NULL,
    [MatriculaIndicadorGerente]          VARCHAR (20)     NULL,
    [MatriculaSuperintendenteRegional]   VARCHAR (20)     NULL,
    [MatriculaFuncionarioCaixa]          VARCHAR (20)     NULL,
    [DataInicioVigencia]                 DATE             NULL,
    [DataFimVigencia]                    DATE             NULL,
    [DataCancelamento]                   DATE             NULL,
    [ValorPremioBruto]                   DECIMAL (19, 2)  NULL,
    [ValorPremioLiquido]                 DECIMAL (19, 2)  NULL,
    [IDIndicador]                        INT              NULL,
    [IDIndicadorGerente]                 INT              NULL,
    [IDIndicadorSuperintendenteRegional] INT              NULL,
    [IDFuncionarioCaixa]                 INT              NULL,
    [IDTipoSegurado]                     INT              NULL,
    [CodigoMoedaSegurada]                SMALLINT         NULL,
    [CodigoMoedaPremio]                  SMALLINT         NULL,
    [TipoBeneficio]                      CHAR (1)         NULL,
    [DataArquivo]                        DATE             NOT NULL,
    [Arquivo]                            VARCHAR (80)     NOT NULL
);

