CREATE TABLE [dbo].[tmp_BLACKLIST_MAILINGS] (
    [CPF] VARCHAR (20) NULL
);


GO
CREATE CLUSTERED INDEX [IDX_CL_tmp_BLACKLIST_MAILINGS]
    ON [dbo].[tmp_BLACKLIST_MAILINGS]([CPF] ASC) WITH (FILLFACTOR = 90);

