CREATE TABLE [dbo].[tmp_MAILING_ENVIADO_AUTO_KPN] (
    [CPF]          VARCHAR (20) NULL,
    [Data_Mailing] DATETIME     NULL
);


GO
CREATE CLUSTERED INDEX [IDX_CL_tmp_MAILING_ENVIADO_AUTO_KPN]
    ON [dbo].[tmp_MAILING_ENVIADO_AUTO_KPN]([CPF] ASC) WITH (FILLFACTOR = 90);

