CREATE TABLE [dbo].[TOP_FIELD] (
    [FIELD_TABLE] VARCHAR (64) CONSTRAINT [TOP_FIELD_FIELD_TABLE_DF] DEFAULT ('                                                                ') NOT NULL,
    [FIELD_NAME]  VARCHAR (32) CONSTRAINT [TOP_FIELD_FIELD_NAME_DF] DEFAULT ('                                ') NOT NULL,
    [FIELD_TYPE]  VARCHAR (2)  CONSTRAINT [TOP_FIELD_FIELD_TYPE_DF] DEFAULT ('  ') NOT NULL,
    [FIELD_PREC]  VARCHAR (4)  CONSTRAINT [TOP_FIELD_FIELD_PREC_DF] DEFAULT ('    ') NOT NULL,
    [FIELD_DEC]   VARCHAR (4)  CONSTRAINT [TOP_FIELD_FIELD_DEC_DF] DEFAULT ('    ') NOT NULL
) ON [PRIMARY];

