CREATE TABLE [dbo].[unidadohistorico_backup_20150603] (
    [ID]                         INT           IDENTITY (1, 1) NOT NULL,
    [IDUnidade]                  SMALLINT      NULL,
    [Codigo]                     SMALLINT      NULL,
    [Nome]                       VARCHAR (100) NOT NULL,
    [IDTipoUnidade]              SMALLINT      NULL,
    [IDFilialPARCorretora]       SMALLINT      NULL,
    [IDFilialFaturamento]        SMALLINT      NULL,
    [IDUnidadeEscritorioNegocio] SMALLINT      NULL,
    [Endereco]                   VARCHAR (100) NULL,
    [Bairro]                     VARCHAR (50)  NULL,
    [CEP]                        CHAR (8)      NULL,
    [DDD]                        CHAR (4)      NULL,
    [DataCriacao]                DATE          NULL,
    [DataExtincao]               DATE          NULL,
    [DataAutomacao]              DATE          NULL,
    [Praca]                      TINYINT       NULL,
    [IDTipoPV]                   SMALLINT      NULL,
    [IDRetaguarda]               SMALLINT      NULL,
    [AutenticarPV]               TINYINT       NULL,
    [Porte]                      TINYINT       NULL,
    [Rota]                       TINYINT       NULL,
    [Impressa]                   SMALLINT      NULL,
    [Responsavel]                VARCHAR (40)  NULL,
    [CodigoEnderecamento]        CHAR (8)      NULL,
    [SiglaUnidade]               CHAR (8)      NULL,
    [CanalVoz]                   SMALLINT      NULL,
    [JusticaFederal]             CHAR (1)      NULL,
    [DataFimOperacao]            DATE          NULL,
    [ClassePV]                   CHAR (1)      NULL,
    [NomeMunicipio]              VARCHAR (35)  NULL,
    [UFMunicipio]                CHAR (2)      NULL,
    [Telefone1]                  CHAR (9)      NULL,
    [TipoTelefone1]              CHAR (5)      NULL,
    [Telefone2]                  CHAR (9)      NULL,
    [TipoTelefone2]              CHAR (5)      NULL,
    [Telefone3]                  CHAR (9)      NULL,
    [TipoTelefone3]              CHAR (5)      NULL,
    [Telefone4]                  CHAR (9)      NULL,
    [TipoTelefone4]              CHAR (5)      NULL,
    [Telefone5]                  CHAR (9)      NULL,
    [TipoTelefone5]              CHAR (5)      NULL,
    [ASVEN]                      BIT           NOT NULL,
    [IBGE]                       NUMERIC (8)   NULL,
    [MatriculaGestor]            VARCHAR (20)  NULL,
    [CodigoNaFonte]              BIGINT        NOT NULL,
    [TipoDado]                   VARCHAR (30)  NOT NULL,
    [Arquivo]                    VARCHAR (80)  NOT NULL,
    [DataArquivo]                DATE          NOT NULL,
    [LastValue]                  BIT           NULL,
    [O]                          BIGINT        NULL
);

