

CREATE VIEW [Financeiro].[DimVisaoGerencial02_VisaoDespesa]
AS

WITH CTE_DESPVG2 AS (

	SELECT
		 LTRIM(RTRIM(CTS.CTS_CONTAG)) AS CD_AGRUPAMENTO_DESPESA_VG2
		,LEFT(LTRIM(RTRIM(CTS.CTS_CONTAG)), 2) AS CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
		,LTRIM(RTRIM(CTS.CTS_DESCCG)) AS DS_AGRUPAMENTO_DESPESA_VG2	--,CTS.CTS_ORDEM AS CD_ORDEM_EXIBICAO_VG2
	FROM [SCASE].[RBDF27].[dbo].[CTS010] CTS
	WHERE CTS.D_E_L_E_T_ = ''	--<> '*' 
	AND CTS.CTS_CODPLA = '002'	--VISÃO GERENCIAL 2 - AGRUPAMENTO POR DESPESA
	GROUP BY CTS.CTS_CONTAG, CTS.CTS_DESCCG		--, CTS.CTS_ORDEM
	--ORDER BY CTS_CONTAG

), CTE_NIVELVG2 AS (

	SELECT DISTINCT
		 NV2.CD_AGRUPAMENTO_DESPESA_VG2 AS CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
		,NV2.DS_AGRUPAMENTO_DESPESA_VG2 AS DS_NIVELI_AGRUPAMENTO_DESPESA_VG2
	FROM CTE_DESPVG2 NV2
	WHERE LEN(NV2.CD_AGRUPAMENTO_DESPESA_VG2) = 2

)

SELECT 
	 DV2.CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,DV2.DS_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,VG2.CD_AGRUPAMENTO_DESPESA_VG2
	,VG2.DS_AGRUPAMENTO_DESPESA_VG2
FROM CTE_DESPVG2 VG2
LEFT JOIN CTE_NIVELVG2 DV2 ON DV2.CD_NIVELI_AGRUPAMENTO_DESPESA_VG2 = VG2.CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
WHERE LEN(VG2.CD_AGRUPAMENTO_DESPESA_VG2) = 4
--ORDER BY 1, 2

UNION

SELECT
	 '-1' AS CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,'Não Informado' AS DS_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,'-1' AS CD_AGRUPAMENTO_DESPESA_VG2
	,'Não Informado' AS DS_AGRUPAMENTO_DESPESA_VG2

UNION

SELECT 
	 '999999' AS CD_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,'Pacote' AS DS_NIVELI_AGRUPAMENTO_DESPESA_VG2
	,'999999' AS CD_AGRUPAMENTO_DESPESA_VG2
	,'Pacote' AS DS_AGRUPAMENTO_DESPESA_VG2

