
CREATE VIEW [Financeiro].[DimVisaoGerencial03_VisaoPacote]
AS

WITH CTE_PACOTEVG3 AS (

	SELECT
		 LTRIM(RTRIM(CTS.CTS_CONTAG)) AS CD_AGRUPAMENTO_PACOTE_VG3
		,LEFT(LTRIM(RTRIM(CTS.CTS_CONTAG)), 2) AS CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
		,LTRIM(RTRIM(CTS.CTS_DESCCG)) AS DS_AGRUPAMENTO_PACOTE_VG3	--,CTS.CTS_ORDEM AS CD_ORDEM_EXIBICAO_VG2
	FROM [SCASE].[RBDF27].[dbo].[CTS010] CTS
	WHERE CTS.D_E_L_E_T_ = ''	--<> '*' 
	AND CTS.CTS_CODPLA = '003'	--VISÃO GERENCIAL 2 - AGRUPAMENTO POR DESPESA
	GROUP BY CTS.CTS_CONTAG, CTS.CTS_DESCCG		--, CTS.CTS_ORDEM
	--ORDER BY CTS_CONTAG

), CTE_NIVELVG3 AS (

	SELECT DISTINCT
		 NV3.CD_AGRUPAMENTO_PACOTE_VG3 AS CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
		,NV3.DS_AGRUPAMENTO_PACOTE_VG3 AS DS_NIVELI_AGRUPAMENTO_PACOTE_VG3
	FROM CTE_PACOTEVG3 NV3
	WHERE LEN(NV3.CD_AGRUPAMENTO_PACOTE_VG3) = 2

)

SELECT 
	 DV3.CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,DV3.DS_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,VG3.CD_AGRUPAMENTO_PACOTE_VG3
	,VG3.DS_AGRUPAMENTO_PACOTE_VG3
FROM CTE_PACOTEVG3 VG3
LEFT JOIN CTE_NIVELVG3 DV3 ON DV3.CD_NIVELI_AGRUPAMENTO_PACOTE_VG3 = VG3.CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
WHERE LEN(VG3.CD_AGRUPAMENTO_PACOTE_VG3) = 4
--ORDER BY 1, 2

UNION

SELECT
	 '-1' AS CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,'Não Informado' AS DS_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,'-1' AS CD_AGRUPAMENTO_PACOTE_VG3
	,'Não Informado' AS DS_AGRUPAMENTO_PACOTE_VG3

UNION

SELECT 
	 '999999' AS CD_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,'Pacote' AS DS_NIVELI_AGRUPAMENTO_PACOTE_VG3
	,'999999' AS CD_AGRUPAMENTO_PACOTE_VG3
	,'Pacote' AS DS_AGRUPAMENTO_PACOTE_VG3

