
CREATE VIEW [Financeiro].[DimVisaoGerencial04_VisaoBalanco]
AS

WITH CTE_BALANCOVG4 AS (

	SELECT
		 LTRIM(RTRIM(CTS.CTS_CONTAG)) AS CD_AGRUPAMENTO_BALANCO_VG4
		,LEFT(LTRIM(RTRIM(CTS.CTS_CONTAG)), 1) AS CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
		,LEFT(LTRIM(RTRIM(CTS.CTS_CONTAG)), 2) AS CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
		,LTRIM(RTRIM(CTS.CTS_DESCCG)) AS DS_AGRUPAMENTO_BALANCO_VG4	--,CTS.CTS_ORDEM AS CD_ORDEM_EXIBICAO_VG2
	FROM [SCASE].[RBDF27].[dbo].[CTS010] CTS
	WHERE CTS.D_E_L_E_T_ = ''	--<> '*' 
	AND CTS.CTS_CODPLA = '004'	--VISÃO GERENCIAL 04 - AGRUPAMENTO POR BALANÇO PATRIMONIAL
	GROUP BY CTS.CTS_CONTAG, CTS.CTS_DESCCG		--, CTS.CTS_ORDEM
	--ORDER BY CTS_CONTAG

), CTE_NIVEL1_VG4 AS (

	SELECT DISTINCT
		 NV4.CD_AGRUPAMENTO_BALANCO_VG4 AS CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
		,NV4.DS_AGRUPAMENTO_BALANCO_VG4 AS DS_NIVELI_AGRUPAMENTO_BALANCO_VG4
	FROM CTE_BALANCOVG4 NV4
	WHERE LEN(NV4.CD_AGRUPAMENTO_BALANCO_VG4) = 1

), CTE_NIVEL2_VG4 AS (

	SELECT DISTINCT
		 NV4.CD_AGRUPAMENTO_BALANCO_VG4 AS CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
		,NV4.DS_AGRUPAMENTO_BALANCO_VG4 AS DS_NIVELII_AGRUPAMENTO_BALANCO_VG4
	FROM CTE_BALANCOVG4 NV4
	WHERE LEN(NV4.CD_AGRUPAMENTO_BALANCO_VG4) = 2

)

SELECT 
	 N1B.CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,N1B.DS_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,N2B.CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,N2B.DS_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,VG4.CD_AGRUPAMENTO_BALANCO_VG4
	,VG4.DS_AGRUPAMENTO_BALANCO_VG4
FROM CTE_BALANCOVG4 VG4
LEFT JOIN CTE_NIVEL1_VG4 N1B ON N1B.CD_NIVELI_AGRUPAMENTO_BALANCO_VG4 = VG4.CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
LEFT JOIN CTE_NIVEL2_VG4 N2B ON N2B.CD_NIVELII_AGRUPAMENTO_BALANCO_VG4 = VG4.CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
WHERE LEN(VG4.CD_AGRUPAMENTO_BALANCO_VG4) > 2
--ORDER BY 1, 2

UNION

SELECT
	 '-1' AS CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,'Não Informado' AS DS_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,'-1' AS CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,'Não Informado' AS DS_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,'-1' AS CD_AGRUPAMENTO_BALANCO_VG4
	,'Não Informado' AS DS_AGRUPAMENTO_BALANCO_VG4

UNION

SELECT 
	 '999999' AS CD_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,'Pacote' AS DS_NIVELI_AGRUPAMENTO_BALANCO_VG4
	,'999999' AS CD_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,'Pacote' AS DS_NIVELII_AGRUPAMENTO_BALANCO_VG4
	,'999999' AS CD_AGRUPAMENTO_BALANCO_VG4
	,'Pacote' AS DS_AGRUPAMENTO_BALANCO_VG4

