
/*
	Autor: Luan Moreno M. Maciel
	Data de Criação: 05/05/2014,
*/

/*******************************************************************************
Nome: Corporativo.Dados.proc_InsereMR_Mailing
*******************************************************************************/
CREATE PROCEDURE Dados.proc_InsereMR_Mailing
AS
BEGIN TRY		
 
DECLARE @PontoDeParada AS VARCHAR(400) = 0
DECLARE @MaiorCodigo AS BIGINT
DECLARE @ParmDefinition NVARCHAR(500)
DECLARE @COMANDO AS NVARCHAR(MAX)

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MR303B_TEMP]') AND type in (N'U') /*ORDER BY NAME*/)
	DROP TABLE [dbo].[MR303B_TEMP];

CREATE TABLE [dbo].[MR303B_TEMP]
(
	[Codigo] [bigint] IDENTITY(1,1) NOT NULL,
	[DataArquivo] [datetime] NULL,
	[NomeArquivo] [nvarchar](300) NULL,
	[Nome] [varchar](300) NULL,
	[CPF] [char](20) NULL,
	[RG] [varchar](15) NULL,
	[OrgaoExpedidor] [varchar](300) NULL,
	[Complemento] [varchar](300) NULL,
	[Endereco] [varchar](300) NULL,
	[Bairro] [varchar](300) NULL,
	[Cidade] [varchar](300) NULL,
	[Estado] [varchar](300) NULL,
	[CEP] [nvarchar](300) NULL,
	[DDD] [nvarchar](300) NULL,
	[Telefone] [nvarchar](20) NULL,
	[DDDComercial] [nvarchar](10) NULL,
	[TelefoneComercial] [nvarchar](20) NULL,
	[DDDCelular] [nvarchar](10) NULL,
	[TelefoneCelular] [nvarchar](20) NULL,
	[Email] [nvarchar](200) NULL,
	[NumeroAgencia] [varchar](10) NULL,
	[NomeAgencia] [varchar](80) NULL,
	[EmpregadoCaixa] [varchar](100) NULL,
	[ApoliceAnterior] [varchar](30) NULL,
	[Bonus_Renovacao] [decimal](12, 2) NULL,
	[Desconto_Fidelidade] [decimal](12, 2) NULL,
	[Desconto_Publico] [decimal](12, 2) NULL,
	[Desconto_Agrupamento] [decimal](12, 2) NULL,
	[Total_Desconto] [decimal](12, 2) NULL,
	[Total_Desconto_Concebido] [decimal](12, 2) NULL,
	[Premio_Total] [decimal](12, 2) NULL,
	[Termino_Vigencia] [date] NULL,
	[QuantidadeParcelas] [int] NULL,
	[Mala_Direta] [varchar](300) NULL,
	[Valor_Primeira_Parcela] [decimal](12, 2) NULL,
	[Valor_Demais_Parcelas] [decimal](12, 2) NULL,
	[IS_Total] [decimal](12, 2) NULL,
	[Cobertura_I] [varchar](50) NULL,
	[IS_I] [decimal](12, 2) NULL,
	[Premio_I] [decimal](12, 2) NULL,
	[Cobertura_II] [varchar](50) NULL,
	[IS_II] [decimal](12, 2) NULL,
	[Premio_II] [decimal](12, 2) NULL,
	[Cobertura_III] [varchar](50) NULL,
	[IS_III] [decimal](12, 2) NULL,
	[Premio_III] [decimal](12, 2) NULL,
	[Cobertura_IV] [varchar](50) NULL,
	[IS_IV] [decimal](12, 2) NULL,
	[Premio_IV] [decimal](12, 2) NULL,
	[Cobertura_V] [varchar](50) NULL,
	[IS_V] [decimal](12, 2) NULL,
	[Premio_V] [decimal](12, 2) NULL,
	[Cobertura_VI] [varchar](50) NULL,
	[IS_VI] [decimal](12, 2) NULL,
	[Premio_VI] [decimal](12, 2) NULL,
	[Cobertura_VII] [varchar](50) NULL,
	[IS_VII] [decimal](12, 2) NULL,
	[Premio_VII] [decimal](12, 2) NULL,
	[Cobertura_VIII] [varchar](50) NULL,
	[IS_VIII] [decimal](12, 2) NULL,
	[Premio_VIII] [decimal](12, 2) NULL,
	[Cobertura_IX] [varchar](50) NULL,
	[IS_IX] [decimal](12, 2) NULL,
	[Premio_IX] [decimal](12, 2) NULL
)
 /*Criação de Índices*/  
CREATE CLUSTERED INDEX idx_MR303B_TEMP ON [dbo].[MR303B_TEMP]
( 
  Codigo ASC
)       

SELECT @PontoDeParada = PontoParada
FROM ControleDados.PontoParada
WHERE NomeEntidade = 'MR303B_Mailing'


/*********************************************************************************************************************/               
/*Recuperação do Maior Código do Retorno*/
/*********************************************************************************************************************/
SET @COMANDO = 'INSERT INTO [dbo].[MR303B_TEMP]
						( 
								[DataArquivo],
								[NomeArquivo],
								[Nome],
								[CPF],
								[RG],
								[OrgaoExpedidor],
								[Complemento],
								[Endereco],
								[Bairro],
								[Cidade],
								[Estado],
								[CEP],
								[DDD],
								[Telefone],
								[DDDComercial],
								[TelefoneComercial],
								[DDDCelular],
								[TelefoneCelular],
								[Email],
								[NumeroAgencia],
								[NomeAgencia],
								[EmpregadoCaixa],
								[ApoliceAnterior],
								[Bonus_Renovacao],
								[Desconto_Fidelidade],
								[Desconto_Publico],
								[Desconto_Agrupamento],
								[Total_Desconto],
								[Total_Desconto_Concebido],
								[Premio_Total],
								[Termino_Vigencia],
								[QuantidadeParcelas],
								[Mala_Direta],
								[Valor_Primeira_Parcela],
								[Valor_Demais_Parcelas],
								[IS_Total],
								[Cobertura_I],
								[IS_I],
								[Premio_I],
								[Cobertura_II],
								[IS_II],
								[Premio_II],
								[Cobertura_III],
								[IS_III],
								[Premio_III],
								[Cobertura_IV],
								[IS_IV],
								[Premio_IV],
								[Cobertura_V],
								[IS_V],
								[Premio_V],
								[Cobertura_VI],
								[IS_VI],
								[Premio_VI],
								[Cobertura_VII],
								[IS_VII],
								[Premio_VII],
								[Cobertura_VIII],
								[IS_VIII],
								[Premio_VIII],
								[Cobertura_IX],
								[IS_IX],
								[Premio_IX]      
					   )
                SELECT 
								[DataArquivo],
								[NomeArquivo],
								[Nome],
								[CPF],
								[RG],
								[OrgaoExpedidor],
								[Complemento],
								[Endereco],
								[Bairro],
								[Cidade],
								[Estado],
								[CEP],
								[DDD],
								[Telefone],
								[DDDComercial],
								[TelefoneComercial],
								[DDDCelular],
								[TelefoneCelular],
								[Email],
								[NumeroAgencia],
								[NomeAgencia],
								[EmpregadoCaixa],
								[ApoliceAnterior],
								[Bonus_Renovacao],
								[Desconto_Fidelidade],
								[Desconto_Publico],
								[Desconto_Agrupamento],
								[Total_Desconto],
								[Total_Desconto_Concebido],
								[Premio_Total],
								[Termino_Vigencia],
								[QuantidadeParcelas],
								[Mala_Direta],
								[Valor_Primeira_Parcela],
								[Valor_Demais_Parcelas],
								[IS_Total],
								[Cobertura_I],
								[IS_I],
								[Premio_I],
								[Cobertura_II],
								[IS_II],
								[Premio_II],
								[Cobertura_III],
								[IS_III],
								[Premio_III],
								[Cobertura_IV],
								[IS_IV],
								[Premio_IV],
								[Cobertura_V],
								[IS_V],
								[Premio_V],
								[Cobertura_VI],
								[IS_VI],
								[Premio_VI],
								[Cobertura_VII],
								[IS_VII],
								[Premio_VII],
								[Cobertura_VIII],
								[IS_VIII],
								[Premio_VIII],
								[Cobertura_IX],
								[IS_IX],
								[Premio_IX]   
                FROM OPENQUERY ([OBERON], 
                ''EXEC [FENAE].[Corporativo].[proc_RecuperaMR_Mailing] ''''' + @PontoDeParada + ''''''') PRP'

EXEC (@COMANDO)     

SELECT @MaiorCodigo = MAX(Codigo)
FROM [dbo].[MR303B_TEMP]


SET @COMANDO = '' 

WHILE @MaiorCodigo IS NOT NULL
BEGIN 

/*
SELECT *
FROM [dbo].[MR303B_TEMP]

SELECT *
FROM Corporativo.Dados.MR303B_Mailing
*/

MERGE INTO Corporativo.Dados.MR303B_Mailing AS T
USING 
(
	SELECT  [Codigo] AS ID,
			[DataArquivo],
			[NomeArquivo],
			[Nome],
			[CPF],
			[RG],
			[OrgaoExpedidor],
			[Complemento],
			[Endereco],
			[Bairro],
			[Cidade],
			[Estado],
			[CEP],
			[DDD],
			[Telefone],
			[DDDComercial],
			[TelefoneComercial],
			[DDDCelular],
			[TelefoneCelular],
			[Email],
			[NumeroAgencia],
			[NomeAgencia],
			[EmpregadoCaixa],
			[ApoliceAnterior],
			[Bonus_Renovacao],
			[Desconto_Fidelidade],
			[Desconto_Publico],
			[Desconto_Agrupamento],
			[Total_Desconto],
			[Total_Desconto_Concebido],
			[Premio_Total],
			[Termino_Vigencia],
			[QuantidadeParcelas],
			[Mala_Direta],
			[Valor_Primeira_Parcela],
			[Valor_Demais_Parcelas],
			[IS_Total],
			[Cobertura_I],
			[IS_I],
			[Premio_I],
			[Cobertura_II],
			[IS_II],
			[Premio_II],
			[Cobertura_III],
			[IS_III],
			[Premio_III],
			[Cobertura_IV],
			[IS_IV],
			[Premio_IV],
			[Cobertura_V],
			[IS_V],
			[Premio_V],
			[Cobertura_VI],
			[IS_VI],
			[Premio_VI],
			[Cobertura_VII],
			[IS_VII],
			[Premio_VII],
			[Cobertura_VIII],
			[IS_VIII],
			[Premio_VIII],
			[Cobertura_IX],
			[IS_IX],
			[Premio_IX]   
	FROM [dbo].[MR303B_TEMP]
) AS S
ON S.ID = T.ID
WHEN MATCHED THEN
	UPDATE
		SET [DataArquivo] = COALESCE(S.[DataArquivo], T.[DataArquivo]),
			[NomeArquivo] = COALESCE(S.[NomeArquivo], T.[NomeArquivo]),
			[Nome] = COALESCE(S.[Nome], T.[Nome]),
			[CPF] = COALESCE(S.[CPF], T.[CPF]),
			[RG] = COALESCE(S.[RG], T.[RG]),
			[OrgaoExpedidor] = COALESCE(S.[OrgaoExpedidor], T.[OrgaoExpedidor]),
			[Complemento] = COALESCE(S.[Complemento], T.[Complemento]),
			[Endereco] = COALESCE(S.[Endereco], T.[Endereco]),
			[Bairro] = COALESCE(S.[Bairro], T.[Bairro]),
			[Cidade] = COALESCE(S.[Cidade], T.[Cidade]),
			[Estado] = COALESCE(S.[Estado], T.[Estado]),
			[CEP] = COALESCE(S.[CEP], T.[CEP]),
			[DDD] = COALESCE(S.[DDD], T.[DDD]),
			[Telefone] = COALESCE(S.[Telefone], T.[Telefone]),
			[DDDComercial] = COALESCE(S.[DDDComercial], T.[DDDComercial]),
			[TelefoneComercial] = COALESCE(S.[TelefoneComercial], T.[TelefoneComercial]),
			[DDDCelular] = COALESCE(S.[DDDCelular], T.[DDDCelular]),
			[TelefoneCelular] = COALESCE(S.[TelefoneCelular], T.[TelefoneCelular]),
			[Email] = COALESCE(S.[Email], T.[Email]),
			[NumeroAgencia] = COALESCE(S.[NumeroAgencia], T.[NumeroAgencia]),
			[NomeAgencia] = COALESCE(S.[NomeAgencia], T.[NomeAgencia]),
			[EmpregadoCaixa] = COALESCE(S.[EmpregadoCaixa], T.[EmpregadoCaixa]),
			[ApoliceAnterior] = COALESCE(S.[ApoliceAnterior], T.[ApoliceAnterior]),
			[Bonus_Renovacao] = COALESCE(S.[Bonus_Renovacao], T.[Bonus_Renovacao]),
			[Desconto_Fidelidade] = COALESCE(S.[Desconto_Fidelidade], T.[Desconto_Fidelidade]),
			[Desconto_Publico] = COALESCE(S.[Desconto_Publico], T.[Desconto_Publico]),
			[Desconto_Agrupamento] = COALESCE(S.[Desconto_Agrupamento], T.[Desconto_Agrupamento]),
			[Total_Desconto] = COALESCE(S.[Total_Desconto], T.[Total_Desconto]),
			[Total_Desconto_Concebido] = COALESCE(S.[Total_Desconto_Concebido], T.[Total_Desconto_Concebido]),
			[Premio_Total] = COALESCE(S.[Premio_Total], T.[Premio_Total]),
			[Termino_Vigencia] = COALESCE(S.[Termino_Vigencia], T.[Termino_Vigencia]),
			[QuantidadeParcelas] = COALESCE(S.[QuantidadeParcelas], T.[QuantidadeParcelas]),
			[Mala_Direta] = COALESCE(S.[Mala_Direta], T.[Mala_Direta]),
			[Valor_Primeira_Parcela] = COALESCE(S.[Valor_Primeira_Parcela], T.[Valor_Primeira_Parcela]),
			[Valor_Demais_Parcelas] = COALESCE(S.[Valor_Demais_Parcelas], T.[Valor_Demais_Parcelas]),
			[IS_Total] = COALESCE(S.[IS_Total], T.[IS_Total]),
			[Cobertura_I] = COALESCE(S.[Cobertura_I], T.[Cobertura_I]),
			[IS_I] = COALESCE(S.[IS_I], T.[IS_I]),
			[Premio_I] = COALESCE(S.[Premio_I], T.[Premio_I]),
			[Cobertura_II] = COALESCE(S.[Cobertura_II], T.[Cobertura_II]),
			[IS_II] = COALESCE(S.[IS_II], T.[IS_II]),
			[Premio_II] = COALESCE(S.[Premio_II], T.[Premio_II]),
			[Cobertura_III] = COALESCE(S.[Cobertura_III], T.[Cobertura_III]),
			[IS_III] = COALESCE(S.[IS_III], T.[IS_III]),
			[Premio_III] = COALESCE(S.[Premio_III], T.[Premio_III]),
			[Cobertura_IV] = COALESCE(S.[Cobertura_IV], T.[Cobertura_IV]),
			[IS_IV] = COALESCE(S.[IS_IV], T.[IS_IV]),
			[Premio_IV] = COALESCE(S.[Premio_IV], T.[Premio_IV]),
			[Cobertura_V] = COALESCE(S.[Cobertura_V], T.[Cobertura_V]),
			[IS_V] = COALESCE(S.[IS_V], T.[IS_V]),
			[Premio_V] = COALESCE(S.[Premio_V], T.[Premio_V]),
			[Cobertura_VI] = COALESCE(S.[Cobertura_VI], T.[Cobertura_VI]),
			[IS_VI] = COALESCE(S.[IS_VI], T.[IS_VI]),
			[Premio_VI] = COALESCE(S.[Premio_VI], T.[Premio_VI]),
			[Cobertura_VII] = COALESCE(S.[Cobertura_VII], T.[Cobertura_VII]),
			[IS_VII] = COALESCE(S.[IS_VII], T.[IS_VII]),
			[Premio_VII] = COALESCE(S.[Premio_VII], T.[Premio_VII]),
			[Cobertura_VIII] = COALESCE(S.[Cobertura_VIII], T.[Cobertura_VIII]),
			[IS_VIII] = COALESCE(S.[IS_VIII], T.[IS_VIII]),
			[Premio_VIII] = COALESCE(S.[Premio_VIII], T.[Premio_VIII]), 
			[Cobertura_IX] = COALESCE(S.[Cobertura_IX], T.[Cobertura_IX]), 
			[IS_IX] = COALESCE(S.[IS_IX], T.[IS_IX]), 
			[Premio_IX] = COALESCE(S.[Premio_IX], T.[Premio_IX])
WHEN NOT MATCHED THEN
	INSERT (ID,
			[DataArquivo],
			[NomeArquivo],
			[Nome],
			[CPF],
			[RG],
			[OrgaoExpedidor],
			[Complemento],
			[Endereco],
			[Bairro],
			[Cidade],
			[Estado],
			[CEP],
			[DDD],
			[Telefone],
			[DDDComercial],
			[TelefoneComercial],
			[DDDCelular],
			[TelefoneCelular],
			[Email],
			[NumeroAgencia],
			[NomeAgencia],
			[EmpregadoCaixa],
			[ApoliceAnterior],
			[Bonus_Renovacao],
			[Desconto_Fidelidade],
			[Desconto_Publico],
			[Desconto_Agrupamento],
			[Total_Desconto],
			[Total_Desconto_Concebido],
			[Premio_Total],
			[Termino_Vigencia],
			[QuantidadeParcelas],
			[Mala_Direta],
			[Valor_Primeira_Parcela],
			[Valor_Demais_Parcelas],
			[IS_Total],
			[Cobertura_I],
			[IS_I],
			[Premio_I],
			[Cobertura_II],
			[IS_II],
			[Premio_II],
			[Cobertura_III],
			[IS_III],
			[Premio_III],
			[Cobertura_IV],
			[IS_IV],
			[Premio_IV],
			[Cobertura_V],
			[IS_V],
			[Premio_V],
			[Cobertura_VI],
			[IS_VI],
			[Premio_VI],
			[Cobertura_VII],
			[IS_VII],
			[Premio_VII],
			[Cobertura_VIII],
			[IS_VIII],
			[Premio_VIII],
			[Cobertura_IX],
			[IS_IX],
			[Premio_IX] )

	VALUES (ID,
			[DataArquivo],
			[NomeArquivo],
			[Nome],
			[CPF],
			[RG],
			[OrgaoExpedidor],
			[Complemento],
			[Endereco],
			[Bairro],
			[Cidade],
			[Estado],
			[CEP],
			[DDD],
			[Telefone],
			[DDDComercial],
			[TelefoneComercial],
			[DDDCelular],
			[TelefoneCelular],
			[Email],
			[NumeroAgencia],
			[NomeAgencia],
			[EmpregadoCaixa],
			[ApoliceAnterior],
			[Bonus_Renovacao],
			[Desconto_Fidelidade],
			[Desconto_Publico],
			[Desconto_Agrupamento],
			[Total_Desconto],
			[Total_Desconto_Concebido],
			[Premio_Total],
			[Termino_Vigencia],
			[QuantidadeParcelas],
			[Mala_Direta],
			[Valor_Primeira_Parcela],
			[Valor_Demais_Parcelas],
			[IS_Total],
			[Cobertura_I],
			[IS_I],
			[Premio_I],
			[Cobertura_II],
			[IS_II],
			[Premio_II],
			[Cobertura_III],
			[IS_III],
			[Premio_III],
			[Cobertura_IV],
			[IS_IV],
			[Premio_IV],
			[Cobertura_V],
			[IS_V],
			[Premio_V],
			[Cobertura_VI],
			[IS_VI],
			[Premio_VI],
			[Cobertura_VII],
			[IS_VII],
			[Premio_VII],
			[Cobertura_VIII],
			[IS_VIII],
			[Premio_VIII],
			[Cobertura_IX],
			[IS_IX],
			[Premio_IX]);

/*************************************************************************************/
/*Atualização do Ponto de Parada, Maior Código*/
/*************************************************************************************/
SET @PontoDeParada = @MaiorCodigo
  
UPDATE ControleDados.PontoParada 
SET PontoParada = @MaiorCodigo
WHERE NomeEntidade = 'MR303B_Mailing'


TRUNCATE TABLE [dbo].[MR303B_TEMP] 
    
/*********************************************************************************************************************/               
/*Recuperação do Maior Código*/
/*********************************************************************************************************************/

SET @COMANDO = 'INSERT INTO [dbo].[MR303B_TEMP]
						( 
								[DataArquivo],
								[NomeArquivo],
								[Nome],
								[CPF],
								[RG],
								[OrgaoExpedidor],
								[Complemento],
								[Endereco],
								[Bairro],
								[Cidade],
								[Estado],
								[CEP],
								[DDD],
								[Telefone],
								[DDDComercial],
								[TelefoneComercial],
								[DDDCelular],
								[TelefoneCelular],
								[Email],
								[NumeroAgencia],
								[NomeAgencia],
								[EmpregadoCaixa],
								[ApoliceAnterior],
								[Bonus_Renovacao],
								[Desconto_Fidelidade],
								[Desconto_Publico],
								[Desconto_Agrupamento],
								[Total_Desconto],
								[Total_Desconto_Concebido],
								[Premio_Total],
								[Termino_Vigencia],
								[QuantidadeParcelas],
								[Mala_Direta],
								[Valor_Primeira_Parcela],
								[Valor_Demais_Parcelas],
								[IS_Total],
								[Cobertura_I],
								[IS_I],
								[Premio_I],
								[Cobertura_II],
								[IS_II],
								[Premio_II],
								[Cobertura_III],
								[IS_III],
								[Premio_III],
								[Cobertura_IV],
								[IS_IV],
								[Premio_IV],
								[Cobertura_V],
								[IS_V],
								[Premio_V],
								[Cobertura_VI],
								[IS_VI],
								[Premio_VI],
								[Cobertura_VII],
								[IS_VII],
								[Premio_VII],
								[Cobertura_VIII],
								[IS_VIII],
								[Premio_VIII],
								[Cobertura_IX],
								[IS_IX],
								[Premio_IX]      
					   )
                SELECT 
                       [DataArquivo],
								[NomeArquivo],
								[Nome],
								[CPF],
								[RG],
								[OrgaoExpedidor],
								[Complemento],
								[Endereco],
								[Bairro],
								[Cidade],
								[Estado],
								[CEP],
								[DDD],
								[Telefone],
								[DDDComercial],
								[TelefoneComercial],
								[DDDCelular],
								[TelefoneCelular],
								[Email],
								[NumeroAgencia],
								[NomeAgencia],
								[EmpregadoCaixa],
								[ApoliceAnterior],
								[Bonus_Renovacao],
								[Desconto_Fidelidade],
								[Desconto_Publico],
								[Desconto_Agrupamento],
								[Total_Desconto],
								[Total_Desconto_Concebido],
								[Premio_Total],
								[Termino_Vigencia],
								[QuantidadeParcelas],
								[Mala_Direta],
								[Valor_Primeira_Parcela],
								[Valor_Demais_Parcelas],
								[IS_Total],
								[Cobertura_I],
								[IS_I],
								[Premio_I],
								[Cobertura_II],
								[IS_II],
								[Premio_II],
								[Cobertura_III],
								[IS_III],
								[Premio_III],
								[Cobertura_IV],
								[IS_IV],
								[Premio_IV],
								[Cobertura_V],
								[IS_V],
								[Premio_V],
								[Cobertura_VI],
								[IS_VI],
								[Premio_VI],
								[Cobertura_VII],
								[IS_VII],
								[Premio_VII],
								[Cobertura_VIII],
								[IS_VIII],
								[Premio_VIII],
								[Cobertura_IX],
								[IS_IX],
								[Premio_IX]   
                FROM OPENQUERY ([OBERON], 
                ''EXEC [FENAE].[Corporativo].[proc_RecuperaMR_Mailing] ''''' + @PontoDeParada + ''''''') PRP'

EXEC (@COMANDO)      

SELECT @MaiorCodigo = MAX(Codigo)
FROM [dbo].[MR303B_TEMP]
                
END

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MR303B_TEMP]') AND type in (N'U') /*ORDER BY NAME*/)
	DROP TABLE [dbo].[MR303B_TEMP];			

END TRY                
BEGIN CATCH
	
  EXEC CleansingKit.dbo.proc_RethrowError	
  RETURN @@ERROR	

END CATCH


--	EXEC Corporativo.Dados.proc_InsereMR_Mailing

--SELECT *
--FROM Dados.MR303B_Mailing
