
/*******************************************************************************
	Nome: Fenae.proc_RecuperaAtendimentoPARIndica
	
	Descrição: Essa procedure vai consultar os dados de indicações contidas no arquivo PARIndica e importadas para  o banco FENAE
		
	Parâmetros de entrada:

	Retorno:
	ResultSet com informações que preencherão a tabela temporária que fará o merge com a Dados.AtendimentoPARIndica
	
*******************************************************************************/
CREATE PROCEDURE [Dados].[proc_RecuperaAtendimentoPARIndica]

AS

 SELECT *  FROM  OPENQUERY ([OBERON],'
 ;WITH PRPVEICULO1 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_1 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_1 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_1 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_1 IS NOT NULL),
PRPVEICULO2 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_2 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_2 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_2 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_2 IS NOT NULL),
PRPVEICULO3 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_3 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_3 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_3 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_3 IS NOT NULL),
PRPVEICULO4 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_4 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_4 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_4 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_4 IS NOT NULL),
PRPVEICULO5 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_5 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_5 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_5 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_5 IS NOT NULL),
PRPVEICULO6 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_6 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_6 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_6 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_6 IS NOT NULL),
PRPVEICULO7 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_7 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_7 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_7 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_7 IS NOT NULL),
PRPVEICULO8 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_8 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_8 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_8 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_8 IS NOT NULL),
PRPVEICULO9 AS (SELECT DATA_NASCIMENTO AS DataNascimento,PROTOCOLO as Protocolo,CPFCNPJ as CPF,NOME_CLIENTE as NomeCliente,NUMERO_PROPOSTA_9 as NumeroProposta,TRY_PARSE(VALOR_PREMIO_FINAL_9 AS DECIMAL(18,6)) AS ValorPremioFinal,TRY_PARSE(VALOR_PREMIO_SEM_DESCONTO_5 AS DECIMAL(18,6))  as ValorPremioSemDesconto FROM [FENAE].[dbo].[VendasAuto_KPN] WHERE QTD_PARCELAS_9 IS NOT NULL)
SELECT Protocolo,CPF,NomeCliente,  NumeroProposta, ValorPremioFinal,ValorPremioSemDesconto,DataNascimento
 FROM  (SELECT * FROM PRPVEICULO1 V1
UNION ALL
SELECT * FROM PRPVEICULO2 V2
UNION ALL
SELECT * FROM PRPVEICULO3 V3
UNION ALL
SELECT * FROM PRPVEICULO4 V4
UNION ALL
SELECT * FROM PRPVEICULO5 V5
UNION ALL
SELECT * FROM PRPVEICULO6 V6
UNION ALL
SELECT * FROM PRPVEICULO7 V7
UNION ALL
SELECT * FROM PRPVEICULO8 V8
UNION ALL
SELECT * FROM PRPVEICULO9 V9) X 

')



