CREATE TABLE [Qlikview].[StageDMFinanceiro_Budget] (
    [IDSTGDMFIM_Budget]          INT             IDENTITY (1, 1) NOT NULL,
    [ANO_MES_COMPETENCIA]        INT             NULL,
    [CD_PLANO_CONTAS]            BIGINT          NULL,
    [CD_CENTRO_CUSTO]            BIGINT          NULL,
    [VL_ORCADO]                  DECIMAL (19, 2) NULL,
    [CD_AGRUPAMENTO_AREA_VG1]    VARCHAR (6)     NULL,
    [CD_AGRUPAMENTO_DESPESA_VG2] VARCHAR (6)     NULL,
    [CD_AGRUPAMENTO_PACOTE_VG3]  VARCHAR (6)     NULL,
    [CD_AGRUPAMENTO_BALANCO_VG4] VARCHAR (6)     NULL,
    [CD_EMPRESA_ORIGEM]          VARCHAR (2)     NULL,
    [CD_EMPRESA]                 VARCHAR (2)     NULL,
    [CD_NIVELI_PRODUTOS]         VARCHAR (10)    NULL,
    [DS_NIVELI_PRODUTOS]         VARCHAR (100)   NULL,
    [CD_NIVELII_PRODUTOS]        VARCHAR (10)    NULL,
    [DS_NIVELII_PRODUTOS]        VARCHAR (100)   NULL,
    [CD_NIVELIII_PRODUTOS]       VARCHAR (10)    NULL,
    [DS_NIVELIII_PRODUTOS]       VARCHAR (100)   NULL,
    [CD_PRODUTO_COMERCIALIZADO]  VARCHAR (10)    NULL,
    [DS_PRODUTO_COMERCIALIZADO]  VARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([IDSTGDMFIM_Budget] ASC) ON [PRIMARY]
);

