CREATE TABLE [PowerBI].[HomologacaoTimeVendasDMSF] (
    [IDTimeVendasDMSF]         INT           IDENTITY (1, 1) NOT NULL,
    [ChaveUnicaTMV]            VARCHAR (200) NULL,
    [IDTMV]                    VARCHAR (18)  NULL,
    [CodigoAgencia]            VARCHAR (10)  NULL,
    [Agencia]                  VARCHAR (255) NULL,
    [TipoUnidade]              VARCHAR (20)  NULL,
    [Ano]                      INT           NULL,
    [Mes]                      INT           NULL,
    [DataReferencia]           DATE          NULL,
    [QtdVendasTotal_DM]        INT           NULL,
    [QtdVendasTotal_SF]        INT           NULL,
    [VerificaQtdVendasTotal]   INT           NULL,
    [QtdFuncionarios_DM]       INT           NULL,
    [QtdFuncionarios_SF]       INT           NULL,
    [VerificaQtdFuncionarios]  INT           NULL,
    [QtdRegistro_DM]           INT           NULL,
    [QtdRegistro_SF]           INT           NULL,
    [VerificaQtdRegistro]      INT           NULL,
    [DataArquivo]              DATE          NULL,
    [ImagemValidacao]          VARCHAR (200) NULL,
    [StatusValidacao]          VARCHAR (20)  NULL,
    [DataAtualizacaoValidador] DATETIME      NULL,
    [DataFimEnvio]             DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([IDTimeVendasDMSF] ASC) ON [PRIMARY]
);

