CREATE TABLE [PowerBI].[HomologacaoIntAcumuladoDMQVSF] (
    [IDHomologIAC_DMQVSF]            INT             IDENTITY (1, 1) NOT NULL,
    [Ano]                            INT             NULL,
    [Mes]                            INT             NULL,
    [UnidadeCodigo]                  SMALLINT        NULL,
    [NomeAgencia]                    VARCHAR (100)   NULL,
    [Codigo]                         VARCHAR (10)    NULL,
    [NomeProduto]                    VARCHAR (100)   NULL,
    [AliasProduto]                   VARCHAR (50)    NULL,
    [MetaMesDM]                      DECIMAL (19, 2) NULL,
    [MetaMesQV]                      DECIMAL (19, 2) NULL,
    [MetaMesSF]                      DECIMAL (19, 2) NULL,
    [RealizadoMesDM]                 DECIMAL (19, 2) NULL,
    [RealizadoMesQV]                 DECIMAL (19, 2) NULL,
    [RealizadoMesSF]                 DECIMAL (19, 2) NULL,
    [MetaAcumuladaDM]                DECIMAL (19, 2) NULL,
    [MetaAcumuladaQV]                DECIMAL (19, 2) NULL,
    [MetaAcumuladaSF]                DECIMAL (19, 2) NULL,
    [RealizadoAcumuladoDM]           DECIMAL (19, 2) NULL,
    [RealizadoAcumuladoQV]           DECIMAL (19, 2) NULL,
    [RealizadoAcumuladoSF]           DECIMAL (19, 2) NULL,
    [VerificaMetaMesDMQV]            INT             NULL,
    [VerificaMetaMesDMSF]            INT             NULL,
    [VerificaRealizadoMesDMQV]       INT             NULL,
    [VerificaRealizadoMesDMSF]       INT             NULL,
    [VerificaMetaAcumuladaDMQV]      INT             NULL,
    [VerificaMetaAcumuladaDMSF]      INT             NULL,
    [VerificaRealizadoAcumuladoDMQV] INT             NULL,
    [VerificaRealizadoAcumuladoDMSF] INT             NULL,
    [FonteDados]                     VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([IDHomologIAC_DMQVSF] ASC) ON [PRIMARY]
);

