CREATE TABLE [PowerBI].[HomologacaoRealizeEmpregadoDMSF] (
    [IDRealizeEmpregadoDMSF]   INT             IDENTITY (1, 1) NOT NULL,
    [ChaveUnicaREM]            VARCHAR (200)   NULL,
    [IDREM]                    VARCHAR (18)    NULL,
    [CodigoAgencia]            VARCHAR (10)    NULL,
    [Agencia]                  VARCHAR (255)   NULL,
    [TipoUnidade]              VARCHAR (20)    NULL,
    [Ano]                      INT             NULL,
    [Mes]                      INT             NULL,
    [DataReferencia]           DATE            NULL,
    [TotalGapMes_DM]           DECIMAL (18, 2) NULL,
    [TotalGapMes_SF]           DECIMAL (18, 2) NULL,
    [VerificaTotalGapMes]      INT             NULL,
    [TotalGapSemestre_DM]      DECIMAL (18, 2) NULL,
    [TotalGapSemestre_SF]      DECIMAL (18, 2) NULL,
    [VerificaTotalGapSemestre] INT             NULL,
    [QtdRegistro_DM]           INT             NULL,
    [QtdRegistro_SF]           INT             NULL,
    [VerificaQtdRegistro]      INT             NULL,
    [DataArquivo]              DATE            NULL,
    [ImagemValidacao]          VARCHAR (200)   NULL,
    [StatusValidacao]          VARCHAR (20)    NULL,
    [DataAtualizacaoValidador] DATETIME        NULL,
    [DataFimEnvio]             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([IDRealizeEmpregadoDMSF] ASC) ON [PRIMARY]
);

