CREATE TABLE [PowerBI].[HomologacaoMetaFisicaDMQVSF] (
    [IDHomologMF_DMQVSF]            INT             IDENTITY (1, 1) NOT NULL,
    [Ano]                           INT             NULL,
    [Mes]                           INT             NULL,
    [UnidadeCodigo]                 SMALLINT        NULL,
    [NomeAgencia]                   VARCHAR (100)   NULL,
    [Codigo]                        VARCHAR (10)    NULL,
    [NomeProduto]                   VARCHAR (100)   NULL,
    [AliasProduto]                  VARCHAR (50)    NULL,
    [MetaDM]                        INT             NULL,
    [MetaQV]                        INT             NULL,
    [MetaSF]                        INT             NULL,
    [RealizadoDM]                   INT             NULL,
    [RealizadoQV]                   INT             NULL,
    [RealizadoSF]                   INT             NULL,
    [AtingimentoDM]                 NUMERIC (19, 2) NULL,
    [AtingimentoQV]                 NUMERIC (19, 2) NULL,
    [AtingimentoSF]                 DECIMAL (19, 2) NULL,
    [VerificaMetaDMQV]              INT             NULL,
    [VerificaMetaDMSF]              INT             NULL,
    [VerificaRealizadoDMQV]         INT             NULL,
    [VerificaRealizadoDMSF]         INT             NULL,
    [VerificaAtingimentoDMQV]       INT             NULL,
    [VerificaAtingimentoDMSF]       INT             NULL,
    [FonteDados]                    VARCHAR (50)    NULL,
    [DataAtualizacaoDMQV]           DATETIME        NULL,
    [DataAtualizacaoDMSF]           DATETIME        NULL,
    [DiferencaDiasAtualizacao]      INT             NULL,
    [MetaRecalculadaSFPD]           INT             NULL,
    [ValorMetaSFPD]                 INT             NULL,
    [VendaDiaSFPD]                  INT             NULL,
    [VerificaMetaRecalculadaDMSFPD] INT             NULL,
    [VerificaMetaDMSFPD]            INT             NULL,
    PRIMARY KEY CLUSTERED ([IDHomologMF_DMQVSF] ASC) ON [PRIMARY]
);

