CREATE TABLE [Financeiro].[Protheus_StageContabilidadeCT2] (
    [IDSTGContCT2]               INT           IDENTITY (1, 1) NOT NULL,
    [CT2_FILIAL]                 VARCHAR (2)   NOT NULL,
    [CT2_DATA]                   VARCHAR (8)   NOT NULL,
    [CT2_LOTE]                   VARCHAR (6)   NOT NULL,
    [CT2_SBLOTE]                 VARCHAR (3)   NOT NULL,
    [CT2_DOC]                    VARCHAR (6)   NOT NULL,
    [CT2_LINHA]                  VARCHAR (3)   NOT NULL,
    [CT2_MOEDLC]                 VARCHAR (2)   NOT NULL,
    [CT2_DC]                     VARCHAR (1)   NOT NULL,
    [CT2_DEBITO]                 VARCHAR (30)  NOT NULL,
    [CT2_CREDIT]                 VARCHAR (30)  NOT NULL,
    [CT2_DCD]                    VARCHAR (1)   NOT NULL,
    [CT2_DCC]                    VARCHAR (1)   NOT NULL,
    [CT2_VALOR]                  FLOAT (53)    NOT NULL,
    [CT2_MOEDAS]                 VARCHAR (5)   NOT NULL,
    [CT2_HP]                     VARCHAR (3)   NOT NULL,
    [CT2_HIST]                   VARCHAR (80)  NOT NULL,
    [CT2_CCD]                    VARCHAR (15)  NOT NULL,
    [CT2_CCC]                    VARCHAR (15)  NOT NULL,
    [CT2_ITEMD]                  VARCHAR (15)  NOT NULL,
    [CT2_ITEMC]                  VARCHAR (15)  NOT NULL,
    [CT2_CLVLDB]                 VARCHAR (15)  NOT NULL,
    [CT2_CLVLCR]                 VARCHAR (15)  NOT NULL,
    [CT2_ATIVDE]                 VARCHAR (40)  NOT NULL,
    [CT2_ATIVCR]                 VARCHAR (40)  NOT NULL,
    [CT2_EMPORI]                 VARCHAR (2)   NOT NULL,
    [CT2_FILORI]                 VARCHAR (2)   NOT NULL,
    [CT2_INTERC]                 VARCHAR (1)   NOT NULL,
    [CT2_IDENTC]                 VARCHAR (50)  NOT NULL,
    [CT2_TPSALD]                 VARCHAR (1)   NOT NULL,
    [CT2_SEQUEN]                 VARCHAR (10)  NOT NULL,
    [CT2_MANUAL]                 VARCHAR (1)   NOT NULL,
    [CT2_ORIGEM]                 VARCHAR (100) NOT NULL,
    [CT2_ROTINA]                 VARCHAR (10)  NOT NULL,
    [CT2_AGLUT]                  VARCHAR (1)   NOT NULL,
    [CT2_LP]                     VARCHAR (3)   NOT NULL,
    [CT2_SEQHIS]                 VARCHAR (3)   NOT NULL,
    [CT2_SEQLAN]                 VARCHAR (3)   NOT NULL,
    [CT2_DTVENC]                 VARCHAR (8)   NOT NULL,
    [CT2_SLBASE]                 VARCHAR (1)   NOT NULL,
    [CT2_DTLP]                   VARCHAR (8)   NOT NULL,
    [CT2_DATATX]                 VARCHAR (8)   NOT NULL,
    [CT2_TAXA]                   FLOAT (53)    NOT NULL,
    [CT2_VLR01]                  FLOAT (53)    NOT NULL,
    [CT2_VLR02]                  FLOAT (53)    NOT NULL,
    [CT2_VLR03]                  FLOAT (53)    NOT NULL,
    [CT2_VLR04]                  FLOAT (53)    NOT NULL,
    [CT2_VLR05]                  FLOAT (53)    NOT NULL,
    [CT2_CRCONV]                 VARCHAR (1)   NOT NULL,
    [CT2_CRITER]                 VARCHAR (4)   NOT NULL,
    [CT2_KEY]                    VARCHAR (200) NOT NULL,
    [CT2_SEGOFI]                 VARCHAR (10)  NOT NULL,
    [CT2_DTCV3]                  VARCHAR (8)   NOT NULL,
    [CT2_SEQIDX]                 VARCHAR (5)   NOT NULL,
    [CT2_CONFST]                 VARCHAR (1)   NOT NULL,
    [CT2_OBSCNF]                 VARCHAR (40)  NOT NULL,
    [CT2_USRCNF]                 VARCHAR (15)  NOT NULL,
    [CT2_DTCONF]                 VARCHAR (8)   NOT NULL,
    [CT2_HRCONF]                 VARCHAR (10)  NOT NULL,
    [CT2_MLTSLD]                 VARCHAR (20)  NOT NULL,
    [CT2_CTLSLD]                 VARCHAR (1)   NOT NULL,
    [CT2_CODPAR]                 VARCHAR (6)   NOT NULL,
    [CT2_NODIA]                  VARCHAR (10)  NOT NULL,
    [CT2_DIACTB]                 VARCHAR (2)   NOT NULL,
    [CT2_CODCLI]                 VARCHAR (6)   NOT NULL,
    [CT2_CODFOR]                 VARCHAR (6)   NOT NULL,
    [CT2_AT01DB]                 VARCHAR (20)  NOT NULL,
    [CT2_AT01CR]                 VARCHAR (20)  NOT NULL,
    [CT2_AT02DB]                 VARCHAR (20)  NOT NULL,
    [CT2_AT02CR]                 VARCHAR (20)  NOT NULL,
    [CT2_AT03DB]                 VARCHAR (20)  NOT NULL,
    [CT2_AT03CR]                 VARCHAR (20)  NOT NULL,
    [CT2_AT04DB]                 VARCHAR (20)  NOT NULL,
    [CT2_AT04CR]                 VARCHAR (20)  NOT NULL,
    [D_E_L_E_T_]                 VARCHAR (1)   NOT NULL,
    [R_E_C_N_O_]                 INT           NOT NULL,
    [R_E_C_D_E_L_]               INT           NOT NULL,
    [CT2_USERGI]                 VARCHAR (17)  NOT NULL,
    [CT2_USERGA]                 VARCHAR (17)  NOT NULL,
    [CT2_XCODVI]                 VARCHAR (3)   NULL,
    [CT2_XCODLI]                 VARCHAR (10)  NULL,
    [CT2_CTRLSD]                 VARCHAR (1)   NOT NULL,
    [CT2_MOEFDB]                 VARCHAR (2)   NOT NULL,
    [CT2_MOEFCR]                 VARCHAR (2)   NOT NULL,
    [CT2_XUSER]                  VARCHAR (6)   NULL,
    [CT2_XAPRNM]                 VARCHAR (25)  NULL,
    [CT2_XDATA]                  VARCHAR (8)   NULL,
    [CT2_XAPROV]                 VARCHAR (6)   NULL,
    [CT2_XUSRNM]                 VARCHAR (25)  NULL,
    [CT2_XDTAPR]                 VARCHAR (8)   NULL,
    [CT2_LANCSU]                 VARCHAR (3)   NOT NULL,
    [CT2_GRPDIA]                 VARCHAR (3)   NOT NULL,
    [CT2_LANC]                   VARCHAR (15)  NOT NULL,
    [CT2_DETALHE_EMPRESA_ORIGEM] VARCHAR (5)   NULL,
    PRIMARY KEY CLUSTERED ([IDSTGContCT2] ASC) WITH (FILLFACTOR = 90) ON [PRIMARY]
);

