CREATE TABLE [Financeiro].[RetornoBancarioSAF] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [CodBanco]         SMALLINT        NULL,
    [Lote]             VARCHAR (10)    NULL,
    [CodRegistro]      SMALLINT        NULL,
    [NSR]              VARCHAR (10)    NULL,
    [CodSegmento]      VARCHAR (5)     NULL,
    [TipoMovimento]    SMALLINT        NULL,
    [CodMovimento]     VARCHAR (3)     NULL,
    [Compensacao]      VARCHAR (5)     NULL,
    [CodBancoDest]     SMALLINT        NULL,
    [CodAgenciaDest]   VARCHAR (10)    NULL,
    [CodAgenciaDVDest] VARCHAR (2)     NULL,
    [ContaCorrente]    VARCHAR (20)    NULL,
    [ContaCorrenteDV]  VARCHAR (2)     NULL,
    [NomeFavorecido]   VARCHAR (60)    NULL,
    [DocEmpresa]       VARCHAR (10)    NULL,
    [DataVencimento]   DATE            NULL,
    [ValorLancamento]  DECIMAL (12, 2) NULL,
    [NumeroDocBanco]   VARCHAR (10)    NULL,
    [QtdeParcela]      VARCHAR (5)     NULL,
    [IndBloqueio]      VARCHAR (2)     NULL,
    [IndParcelamento]  VARCHAR (2)     NULL,
    [DiaVencimento]    SMALLINT        NULL,
    [NumeroParcela]    VARCHAR (5)     NULL,
    [DataEfetivacao]   DATE            NULL,
    [ValorEfetivado]   DECIMAL (12, 2) NULL,
    [FinalidadeDOC]    VARCHAR (5)     NULL,
    [AvisoFavorecido]  VARCHAR (10)    NULL,
    [CodOcorrencia]    VARCHAR (10)    NULL,
    [Ocorrencia01]     VARCHAR (100)   NULL,
    [Ocorrencia02]     VARCHAR (100)   NULL,
    [Ocorrencia03]     VARCHAR (100)   NULL,
    [Ocorrencia04]     VARCHAR (100)   NULL,
    [Ocorrencia05]     VARCHAR (100)   NULL,
    [AnoMes]           VARCHAR (6)     NULL,
    CONSTRAINT [PK_RetornoBancoSAF] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90)
);

