CREATE TABLE [Financeiro].[RetornoBancario] (
    [Codigo]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [CodigoBanco]                VARCHAR (4)     NULL,
    [LoteServico]                VARCHAR (10)    NULL,
    [CodigoRegistro]             VARCHAR (5)     NULL,
    [NSR]                        VARCHAR (5)     NULL,
    [CodigoSegmento]             VARCHAR (4)     NULL,
    [TipoMovimento]              VARCHAR (2)     NULL,
    [CodigoInstrucaoMovimento]   VARCHAR (4)     NULL,
    [CamaraCompensacao]          VARCHAR (4)     NULL,
    [CodigoBancoDestino]         VARCHAR (4)     NULL,
    [CodigoAgenciaDestino]       VARCHAR (10)    NULL,
    [DVAgenciaDestino]           VARCHAR (2)     NULL,
    [ContaCorrenteDestino]       INT             NULL,
    [DVContaDestino]             VARCHAR (2)     NULL,
    [NomeFavorecido]             VARCHAR (200)   NULL,
    [DocumentoEmpresa]           VARCHAR (20)    NULL,
    [DataVencimento]             VARCHAR (20)    NULL,
    [TipoMoeda]                  VARCHAR (30)    NULL,
    [QuantidadeMoeda]            VARCHAR (20)    NULL,
    [ValorLancamento]            DECIMAL (18, 2) NULL,
    [NumeroDocumentoBanco]       VARCHAR (20)    NULL,
    [QuantidadeParcelas]         VARCHAR (10)    NULL,
    [IndicadorBloqueio]          VARCHAR (2)     NULL,
    [IndicadorFormaParcelamento] VARCHAR (5)     NULL,
    [NumeroParcela]              VARCHAR (4)     NULL,
    [DataEfetivacao]             VARCHAR (15)    NULL,
    [ValorRealEfetivado]         VARCHAR (20)    NULL,
    [Informacao_II]              VARCHAR (50)    NULL,
    [FinalidadeDocumento]        VARCHAR (4)     NULL,
    [AvisoFavorecido]            VARCHAR (10)    NULL,
    [Ocorrencias]                VARCHAR (50)    NULL,
    [DescricaoOcorrencia]        VARCHAR (150)   NULL,
    [Ano]                        VARCHAR (10)    NULL,
    [Mes]                        VARCHAR (10)    NULL
);

