CREATE PARTITION FUNCTION [_dta_pf__1309](VARCHAR (100))
    AS RANGE
    FOR VALUES ('ATAULFO DE PAIVA, RJ', 'BOM JESUS', 'CASCAVEL, CE', 'CORBELIA, PR', 'FGTS FLORIANOPOLIS', 'IMPERATRIZ, MA', 'JOAO DIAS, SP', 'LARGO SANTA IFIGENIA, SP', 'NATIVIDADE, RJ', 'PAP CAT CAXIAS DO SUL', 'PETROBRAS SAO PAULO, SP', 'PRESIDENTE JOSE ALENCAR, MG', 'SANTA RITA DO SAPUCAI, MG', 'SIDROLANDIA', 'TUPI');

