CREATE PARTITION FUNCTION [_dta_pf__3138](VARCHAR (100))
    AS RANGE
    FOR VALUES ('BAGE, RS', 'CAMPO VERDE, MT', 'CORBELIA, PR', 'GANDU', 'JANUARIA, MG', 'LARGO SANTA IFIGENIA, SP', 'OLINDA, PE', 'PASSEIO SHOPPING, RJ', 'PRESIDENTE JOSE ALENCAR, MG', 'SAO JOAO CLIMACO, SP', 'TRES COROAS, RS');

